### ISSUE TITLE
不是私密连接

### ISSUE THREAD

**Issue by OneDirection9** [bannedbook/fanqiang#106]
最近更新了一下chrome，之后再翻墙就一直是“不是私密连接的错误”，求帮助

**Comment by theratlesnake** [comment]
证书的问题吧

**Comment by OneDirection9** [comment]
@theratlesnake 更新chrome之前还是能够翻墙的，更新之后就出现这个问题了。不过我改host了，无所谓了

**Comment by theratlesnake** [comment]
那就好，有问题积极反馈就行。

**Comment by bannedbook** [comment]
是用 goagent 翻的吗，试试看 用右键点击，以管理员身份启动

**Comment by OneDirection9** [comment]
@bannedbook 刚刚试了一下，还是现实不是私密连接，并且之前点展开，返回非安全链接，这个功能也没了，可能google的问题吧。不纠结了，就该host了，谢谢~
