### ISSUE TITLE
今天重装了系统，填入以上pac还是上不了google facebook等，快点更新pac啊

### ISSUE THREAD

**Issue by jacob2016s** [bannedbook/fanqiang#110]
另，手机上的禁闻浏览app也打不开里面的链接了。。
坐标：广东东莞， 时间：2017/4/24

**Comment by Alvin9999** [comment]
这个可以用https://coding.net/u/Alvin9999/p/pac/git/raw/master/pac1

**Comment by bannedbook** [comment]
我们的pac服务器更新了，请再试试看 [PAC翻墙](https://github.com/bannedbook/fanqiang/wiki/pacfq)
并请帮我们反馈使用效果，谢谢

**Comment by bannedbook** [comment]
禁闻浏览app 的服务端也更新了，请再试试看， 并请帮我们反馈使用效果，谢谢

**Comment by jacob2016s** [comment]
手机上的禁闻浏览app能够打开,但电脑上的pac仍然翻不了墙,上不了google facebook,用的chrome浏览器,win7系统昨天重装过..

**Comment by jacob2016s** [comment]
该网页无法正常运作

facebook.com 未发送任何数据。
ERR_EMPTY_RESPONSE

**Comment by bannedbook** [comment]
谢谢反馈，[禁闻代理(for PC)](https://github.com/killgfw/fg/raw/master/jw/jwd.zip)  ，请试试看这个禁闻代理是否可以用

**Comment by jacob2016s** [comment]
今天可以上网了,google,facebook,,bannedbook.org都打的开了.
谢谢!
