### ISSUE TITLE
网址为 http://p.dtwang.org/ 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。

### ISSUE THREAD

**Issue by yoyolucrecia** [bannedbook/fanqiang#112]
今天打开禁闻代理发现有3.0更新，更新之后就被360拦截了。
后来删掉原来的代理关掉了360，重新下载解压之后就打不开网站了，一直显示无法访问此网站。
哭瞎，求解决办法

**Comment by bannedbook** [comment]
更新到 3.1 版了，试试看如何
