### ISSUE TITLE
软件无法升级

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#113]
你们好，你们的软件无法升级。无论是：GoAgent翻墙升级还是GoAgent2翻墙都无法升级显示
![default](https://cloud.githubusercontent.com/assets/24630043/25563119/664c8ac6-2dc7-11e7-97ab-c300505c5013.jpg)
并且GoAgent翻墙无法翻墙。这个问题我很久之前就反应了，一直未解决。急盼解决。谢谢！

**Comment by bannedbook** [comment]
您好，首先要确保 GoAgent翻墙 或者 GoAgent2翻墙 成功，然后才能升级。
请问你GoAgent翻墙  或 GoAgent2翻墙 能够成功翻墙吗？

**Comment by iluvni** [comment]
GoAgent2能够成功翻墙 但不能升级，显示以上图片中的内容

**Comment by bannedbook** [comment]
有没有按此步骤执行？
升级步骤：
1、	右键单击 GoAgent翻墙.cmd 或GoAgent2翻墙.cmd，以管理员身份启动；
2、	启动后关闭Chrome浏览器；
3、	右键点GoAgent图标，设置IE代理，127.0.0.1:8087

设置IE代理后，用IE访问Google 看看能否正常访问

**Comment by iluvni** [comment]
执行步骤没有出错，设置IE代理后IE浏览器可以访问谷歌网站。

**Comment by iluvni** [comment]
请问是你们那里的问题还是我这边？如果是我这边可能是什么问题？麻烦帮我想想办法。谢谢！

**Comment by bannedbook** [comment]
这个  https://github.com/killgfw/fg/raw/master/fqb/ChromeGo.7z 是最新版，里面的chrome是最新版
