### ISSUE TITLE
你好，我使用你的软件浏览器无法升级

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#114]
你好，我使用你的软件浏览器无法升级，请求解决。谢谢

**Comment by bannedbook** [comment]
这个  https://github.com/killgfw/fg/raw/master/fqb/ChromeGo.7z 是最新版，里面的chrome是最新版

**Comment by iluvni** [comment]
谢谢

**Comment by iluvni** [comment]
o(︶︿︶)o 唉
