### ISSUE TITLE
禁闻3.1无法连接

### ISSUE THREAD

**Issue by wolfljj** [bannedbook/fanqiang#115]
禁闻3.1无法连接

**Comment by bannedbook** [comment]
您好，报什么错呢？ 可以截图看看吗

**Comment by wolfljj** [comment]
连接已重置
ERR_CONNECTION_RESET

**Comment by bannedbook** [comment]
请现在试试看如何

**Comment by wolfljj** [comment]
![jw](https://cloud.githubusercontent.com/assets/5014779/25648202/048272ec-2ffc-11e7-9533-1b55c472a9bd.png)
还是这个错误

**Comment by bannedbook** [comment]
访问什么网站,任何网站都不行吗?访问google 、facebook 可以吗

**Comment by wolfljj** [comment]
启动打开就直接是这个 没法儿访问任何网站

**Comment by bannedbook** [comment]
你直接用这个 代理  45.76.244.71 端口 25  翻墙试试看行不行

**Comment by Loveowner** [comment]
3.1版本还是不能使用，请求速解！

**Comment by bannedbook** [comment]
您好，上面提供的代理是3.1其中的一个代理，我的意思是让您直接测试那个代理，不用3.1不用软件，直接用那个代理看看行不行

**Comment by Loveowner** [comment]
你好，直接测试你提供的上面的代理也还是不行！！
之前禁闻代理2.9版本也不能使用了！！

**Comment by bannedbook** [comment]
我们查看了这个代理，有不少翻墙流量的。可能不同地区封锁情况不同的。
要不您试试这个 [Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)

**Comment by Loveowner** [comment]
习惯了禁闻代理，3。1版本什么时候能修复呢？

**Comment by bannedbook** [comment]
试试这个  [PAC翻墙](https://github.com/bannedbook/fanqiang/wiki/pacfq)
