### ISSUE TITLE
火狐firefox一键翻墙包PAC翻墙失效

### ISSUE THREAD

**Issue by terryandjing** [bannedbook/fanqiang#118]
无法访问FACEBOOK和YOUTUBE

**Comment by bannedbook** [comment]
现在试试看

**Comment by terryandjing** [comment]
今天一天都不行，提示
连接被重置

载入页面时与服务器的连接被重置。

    此站点暂时不可用或者太忙。请稍后再试。
    如果您无法载入任何页面，请检查您计算机的网络连接。
    如果您的计算机或网络受到防火墙或者代理服务器的保护，请确认 Firefox 已被授权访问网络。

**Comment by bannedbook** [comment]
要不试试 goagent 和蓝灯吧

**Comment by solutioned** [comment]
Duplicate of issue #109
