### ISSUE TITLE
Goagent 打开的 Chrome 浏览器和系统自带的难道不一样？

### ISSUE THREAD

**Issue by xueshengke** [bannedbook/fanqiang#122]
我遇到的问题具体是这样的：我用 goagent 运行，打开了一个 Chrome 浏览器，发现是只在这一个窗口里翻墙是有效的，可以另外再开一个 Chrome 窗口，而它是不能翻墙的。
这些都不是关键。
用 goagent 打开的 Chrome 窗口里面有些插件不能安装，比如我想装 Adblock plus，死活不成功，老是提示我 “无法将扩展程序目录移动到个人资料中”，但是奇怪的是有一些插件是可以安装的，比如 “Infinity”。而我用 Lantern 打开的 Chrome 也是同样的问题。
但是我用自带的浏览器，换一种翻墙方法，是可以安装所有插件的，所以我觉得问题在这个翻墙包里。

求给一个解决方案。非常感谢！

我使用的是 Chrome 一键翻墙包，PC：Windows 7，Chrome：57.0.2987.110 (64 bit)

**Comment by bannedbook** [comment]
你可以把翻墙包里的 Browser 目录改个名字，就会调用到系统的 Chrome 浏览器了

**Comment by xueshengke** [comment]
是 chrome-user-data 文件夹吗？我将它改名为 chrome-user-data-1，之后，再打开 goagent，又生成了一个 chrome-user-data 文件夹，然后还是单独打开了一个浏览器，还是安装不了 adblock plus 插件。

**Comment by bannedbook** [comment]
Browser 目录

**Comment by bannedbook** [comment]
如果你没有 Browser 目录 ,那就是调用的系统浏览器

**Comment by xueshengke** [comment]
有没有可能是有一部分插件被这个翻墙包禁了？因为有部分插件是可以安装的，所以我猜测包里某个文件给浏览器加了一个插件屏蔽的限制？求告知如何解决？

**Comment by bannedbook** [comment]
我们没有做这样的限制哦

**Comment by xueshengke** [comment]
换了一台电脑居然没有出现这种情况！哎，奇怪的问题，Anyway，感谢回答！
