### ISSUE TITLE
goagent更新到版本 58.0.3029.110就隐私设置错误，导入证书也无果，请问这是什么问题

### ISSUE THREAD

**Issue by abcats17** [bannedbook/fanqiang#123]

**Comment by bannedbook** [comment]
右键，以管理员身份启动

**Comment by abcats17** [comment]
恩，升级以后右键管理员身份启动不行
然后跟着说明导入也是不行
重新解压用初始版本就是正常的，一旦升级到最新的内核就是隐私设置错误

**Comment by bannedbook** [comment]
1.删除已导入的证书文件（windows下运行certmgr.msc和certlm.msc，然后删除goagent证书；mac下载钥匙串中删除证书）

    2.停止运行GoAgent(如果正在运行)

    3.删除Agent目录下的certs文件夹以及ca.crt证书文件

    4.去掉Agent根目录proxylib.py            中#cert.add_extensions([OpenSSL.crypto.X509Extension(b'subjectAltName',True, ', '.join('DNS: %s' % x for x in sans))])一行的#号注释

    5.重新右键，管理员身份启动运行GoAgent翻墙.cmd，将会产生新的ca.crt证书

    6.导入新生成的ca.crt证书，一般双击就可以了

    7.刷新浏览器，此时应该可以使用了，enjoys！

**Comment by abcats17** [comment]
实在是不好意思，照您的步骤完成后，还是出现之前的问题。。。TT

**Comment by bannedbook** [comment]
请下载新版 https://github.com/killgfw/fg/raw/master/fqb/ChromeGo.7z
启动goagent 时，右键，以管理员身份启动

**Comment by theratlesnake** [comment]
按照步骤可以成功啊，我已经解决了这个问题，是不是你哪一步搞错了？
