### ISSUE TITLE
禁闻3.1移动网络用户无法连接

### ISSUE THREAD

**Issue by xianzhi33** [bannedbook/fanqiang#125]
禁闻3.1移动网络用户无法连接

**Comment by bannedbook** [comment]
好像是这样，移动宽带下无法使用。只有电信和联通可以用。
晚一些时候或许考虑制作移动宽带专用的版本，敬请关注

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/issues/128

**Comment by bannedbook** [comment]
全面升级[Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)/[火狐firefox一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/%E7%81%AB%E7%8B%90firefox%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)(for PC)，集成N种翻墙软件，欢迎下载。
