### ISSUE TITLE
关于iphone翻墙

### ISSUE THREAD

**Issue by xiaxiazhu119** [bannedbook/fanqiang#126]
按教程在iphone的无线设置中设置pac地址：https://raw.githubusercontent.com/bannedbook/fanqiang/master/jw/new.pac
然后在safari中 打开a.dtwang.org
无法打开
请教如何解决

**Comment by bannedbook** [comment]
网友反馈,移动宽带下无法使用。电信和联通或许可以用。

**Comment by xiaxiazhu119** [comment]
我的电信的宽带
我输入的pac地址正确么
是否输入完了 就可以翻墙了

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/issues/128
