### ISSUE TITLE
iphone翻墙

### ISSUE THREAD

**Issue by gdsfz** [bannedbook/fanqiang#128]
我的是移动宽带，上午使用https://raw.githubusercontent.com/bannedbook/fanqiang/master/jw/new.pac 还能正常翻墙，下午突然就不行了

**Comment by bannedbook** [comment]
这个问题有点无解，有很多类似情况。
我们看服务器一直有流量，但与部分网友反馈用不了。
也有人反馈移动宽带不好使

**Comment by gdsfz** [comment]
现在又正常了

**Comment by bannedbook** [comment]
好的，恢复正常就好，欢迎继续反馈使用效果

**Comment by Wensibob** [comment]
移动的校园网这十多天依旧不行

**Comment by Alvin9999** [comment]
@Wensibob  试试这个pac地址https://raw.githubusercontent.com/Alvin9999/new-pac/master/pac

**Comment by Wensibob** [comment]
@Alvin9999 这个也不能用了吧

**Comment by Alvin9999** [comment]
@Wensibob 如果不能用，可以试试这款PAC版，内置4个PAC地址，可以切换使用。下载地址：https://github.com/Alvin9999/new-pac/wiki/PAC%E7%89%88

**Comment by Alvin9999** [comment]
这是电脑windows系统用的PAC版，截图：
![53pac1](https://user-images.githubusercontent.com/12132898/27774440-e6c746bc-5fc4-11e7-9415-4c0adee06202.PNG)
![53pac2](https://user-images.githubusercontent.com/12132898/27774441-e6ea5d5a-5fc4-11e7-9134-35469d70894c.PNG)

**Comment by Alvin9999** [comment]
如果是iphone手机，可以用这个[苹果手机SS翻墙教程](https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E6%89%8B%E6%9C%BA%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6)

**Comment by rickertanks** [comment]
推荐一个自用的shadowsocks  SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺~已屏蔽国内ip，需翻墙访问～
http://cp.dawangidc.com/aff.php?aff=523
购买服务后请看配置教程
https://fqjsjl.tumblr.com/

**Comment by dqdbwqn** [comment]
那就给各位推荐两个稳定的v pn吧，推荐用黄金青蛙的[VyprVPN](https://www.goldenfrog.com/zh/vyprvpn?offer_id=174&amp;aff_id=3008)或者[expressVPN](http://www.linkev.com/?a_fid=clover)，老品牌，你值得拥有 •ᴗ•
