### ISSUE TITLE
打开Google提示不是私密连接

### ISSUE THREAD

**Issue by Sitrone** [bannedbook/fanqiang#130]
提示
>您的连接不是私密连接
攻击者可能会试图从www.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID
自动向 Google 报告可能出现的安全事件的详细信息。隐私权政策  

然后就没法访问了，请问下，这个是什么问题？

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/issues/123

**Comment by Sitrone** [comment]
已解决，多谢
