### ISSUE TITLE
禁闻代理3.1版本什么时候能够恢复？其他的翻墙方式都太慢了！

### ISSUE THREAD

**Issue by Loveowner** [bannedbook/fanqiang#131]

**Comment by Alvin9999** [comment]
电脑的话，可以用我分享的PAC版，速度很快。下载地址：https://github.com/Alvin9999/new-pac/wiki/PAC%E7%89%88

**Comment by bannedbook** [comment]
全面升级[Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)/[火狐firefox一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/%E7%81%AB%E7%8B%90firefox%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)(for PC)，集成N种翻墙软件，欢迎下载。
