### ISSUE TITLE
pac、蓝灯番羽墙打不开谷歌学术？

### ISSUE THREAD

**Issue by caicaifearless** [bannedbook/fanqiang#132]
用的pac翻墙，前几天一直能用谷歌学术，但现在打不开，说是从我的电脑上检测到异常流量
另一台用蓝灯翻墙，也是说检测到异常流量，打不开谷歌学术

**Comment by bannedbook** [comment]
换goagent 可以吗

**Comment by bannedbook** [comment]
全面升级[Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)/[火狐firefox一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/%E7%81%AB%E7%8B%90firefox%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)(for PC)，集成N种翻墙软件，欢迎下载。
