### ISSUE TITLE
禁闻代理3.1 twitter不能上但yutube能上

### ISSUE THREAD

**Issue by Ryuu02** [bannedbook/fanqiang#134]

**Comment by Ryuu02** [comment]
![qq 20170604214012](https://cloud.githubusercontent.com/assets/29173179/26762116/e25c31f8-496e-11e7-82b9-461a766beeb4.jpg)

**Comment by bannedbook** [comment]
再试试

**Comment by bannedbook** [comment]
全面升级[Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)/[火狐firefox一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/%E7%81%AB%E7%8B%90firefox%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)(for PC)，集成N种翻墙软件，欢迎下载。
