### ISSUE TITLE
请提供包含老版本的蓝灯的翻墙包

### ISSUE THREAD

**Issue by xugaohui** [bannedbook/fanqiang#136]
请提供包含老版本的蓝灯的翻墙包,现在这个3.70老是用一会提示流量限制.而且还有巨大的bug,就是不能使用蓝灯pac翻墙功能了.谢谢.

**Comment by bannedbook** [comment]
抱歉，老版本的没有了

**Comment by Alvin9999** [comment]
@xugaohui  [lanter225版本](https://github.com/Alvin9999/new-pac/wiki/Lantern%E7%89%88)
