### ISSUE TITLE
如何部署多个appid？

### ISSUE THREAD

**Issue by steve-wanglin** [bannedbook/fanqiang#138]
如何部署多个appid？

**Comment by chrome001** [comment]
一个谷歌账号可以注册10个app，分别上传即可，注意用 |分割多个appid

**Comment by bannedbook** [comment]
最新版 ChromeGo 里面 \ipv6-Agent1\code\default\gae_proxy\server 目录下
用 uploader.bat 来上传
具体看目录下的
README.md
