### ISSUE TITLE
六月七号的更新我使用有问题

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#142]
你好，你在六月七号更新的软件，我这边只有那个单独的蓝灯可以出去。其余的都出不了。并且Firefly依旧被报毒。希望尽快解决。谢谢！

**Comment by bannedbook** [comment]
GoAgent2翻墙、GoAgent翻墙、PAC翻墙 都不行吗，程序都有什么提示？
goagent的黑色窗口里有什么信息

**Comment by iluvni** [comment]
都不行。提示什么我没留意。现在我还是用的5月19号的。

**Comment by Alvin9999** [comment]
试试这款[PAC版](https://github.com/Alvin9999/new-pac/wiki/PAC%E7%89%88)

![53pac1](https://user-images.githubusercontent.com/12132898/27774468-4b60a2a8-5fc5-11e7-8c69-0c9e5a15857b.PNG)
![53pac2](https://user-images.githubusercontent.com/12132898/27774469-4bd844fc-5fc5-11e7-8c44-63f3d9dca679.PNG)

**Comment by bannedbook** [comment]
全面升级[Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)/[火狐firefox一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/%E7%81%AB%E7%8B%90firefox%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)(for PC)，集成N种翻墙软件，欢迎下载。
