### ISSUE TITLE
请问使用goagent翻墙是否会被朝廷发现？

### ISSUE THREAD

**Issue by Jeremyshilintong** [bannedbook/fanqiang#143]
墙内用户访问被屏蔽的网站是否能被朝廷的监控系统检测到？

**Comment by bannedbook** [comment]
对一般翻墙浏览海外新闻的网友而言，朝廷采取的措施就是封堵，不会有特别制裁措施，因为翻墙的人太多

**Comment by qwas982** [comment]
@bannedbook bannedbook希望所有的翻墙方式都基于p2p,硬件软件操作系统.
比如具有硬件加速的p2p无线路由器,其CPU都有针对性的电路.拥有这种无线路由器的用户能自动组网,形成新的网络硬线路.不再受到运营商的限制.用新的线路链接到海外,不再经过大局域网.
操作系统,其内核都是p2p写的,有软路由模块.
软件有虚拟路由器,为了解决没有路由器硬件的用户也能连接.
基于p2p的汇编级程序语言.高级p2p编程语言等,发展壮大p2p翻墙社区.创造一个全新的体系.
