### ISSUE TITLE
iphone翻墙的pac地址

### ISSUE THREAD

**Issue by Agallochh** [bannedbook/fanqiang#144]
wifi里http代理地址是多少啊，谢谢

**Comment by bannedbook** [comment]
pac地址：

https://raw.githubusercontent.com/bannedbook/fanqiang/master/jw/new.pac

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/wiki/iphone%E7%BF%BB%E5%A2%99

**Comment by bmycbzq** [comment]
我试过上面那个，不好使。

**Comment by xubeng** [comment]
地址不行啊

**Comment by bannedbook** [comment]
https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E6%89%8B%E6%9C%BA%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6
