### ISSUE TITLE
中国电信商2月前将禁止个人VPN接入

### ISSUE THREAD

**Issue by Jeremyshilintong** [bannedbook/fanqiang#146]
据彭博新闻社星期一报道，中国政府通知电信运营商在2018年2月1日前截断个人用户对虚拟专用网络（VPN）的接入。
彭博社援引不愿透露身份的消息人士的话说，中国政府要求中国最大的三家国营电信公司——中国移动、中国联通、中国电信——禁止个人用户使用VPN。
目前不清楚这项命令对外国在华企业的影响。知情人士向彭博社表示，中国境内的企业可以租用国际专线，但必须将使用这一服务的信息备案。
彭博社援引美中贸易全国委员会副主席杰克·帕克（Jake Parker）的话说，首当其冲的应该是个人用户，但是他还表示：“在过去，任何试图切断公司内部VPN的做法都会导致企业不得不考虑减少或关闭在中国的经营，这是非常严重的问题。”
中国是世界上互联网审查制度最严厉的国家之一。国外许多主要新闻网站、国际社交媒体网站、甚至一些学术网站在中国国内都无法访问。VPN是中国普通网民绕开中国政府网络防火墙访问境外被禁网站的主要方式之一。这项命令将进一步阻断中国境内互联网用户自由上网的途径。
中国国家主席习近平2014年开始宣扬“网络主权”的概念。与此同时，中国政府正在加大防堵“网络防火长城”上的漏洞。
VPN运营在中国一直属于法律监管的灰色地带。中国工信部今年1月发布《关于清理规范互联网网络接入服务市场的通知》，禁止用户未经电信主管部门批准自行建立或租用VPN。《通知》下发后，受到中国网民欢迎的VPN服务提供商“GreenVPN”宣布，因“接上级监管部门通知”，7月1日停止服务。
另外，今年3月，中国重庆市修订网络监管行政处罚裁量基准，规定在重庆地区使用网络“翻墙”工具访问境外网站的个人可以被处以罚款，甚至追究刑事责任
摘自：https://www.bannedbook.org/bnews/headline/20170711/789819.html

请问如何应对？

**Comment by bannedbook** [comment]
我们这个不是VPN，不用担心啦

**Comment by ycountJavaXuan** [comment]
Closed !! 靠
在 2017年10月11日，11:42，如何翻墙 <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #146<https://github.com/bannedbook/fanqiang/issues/146>.
