### ISSUE TITLE
请问这该怎么解决

### ISSUE THREAD

**Issue by ccaabbddee** [bannedbook/fanqiang#147]
我是用Google AppEngine的新手，按照步骤来结果打开Google App Engine Launcher的Deploy后出现了deployment to google的界面，然后就没法进行了，请问是什么原因，该怎么办？

**Comment by Alvin9999** [comment]
建议用goprox来部署，参考教程：[自建appid和搜谷歌ip教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAappid%E5%92%8C%E6%90%9C%E8%B0%B7%E6%AD%8Cip%E6%95%99%E7%A8%8B%EF%BC%88GoAgent%E7%89%88%E5%92%8CGoProxy%E7%89%88%EF%BC%89)

**Comment by bannedbook** [comment]
最新版 ChromeGo 里面 \ipv6-Agent1\code\default\gae_proxy\server 目录下
用 uploader.bat 来上传
具体看目录下的
README.md
