### ISSUE TITLE
中国将禁止vpn服务续

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#148]
请问这个：今年3月，中国重庆市修订网络监管行政处罚裁量基准，规定在重庆地区使用网络“翻墙”工具访问境外网站的个人可以被处以罚款，甚至追究刑事责任。该怎么办？

**Comment by bannedbook** [comment]
努力推广翻墙，大家一起翻，法不责众

**Comment by gugejun** [comment]
# [只有伸长的梯子没有加厚的墙](https://github.com/bannedbook/fanqiang)

**Comment by Jeremyshilintong** [comment]
如果有人上门来抓你，你就塞红包打发他们走。

**Comment by anthony1989** [comment]
没有VPN我怎么用谷歌全家桶？墙是必须要翻的！
