### ISSUE TITLE
这两天是怎么了？

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#149]
我使用的软件这几天发现打开网页的速度极慢，有时干脆打不开。请求解决！谢谢！

**Comment by iluvni** [comment]
无论是GoAgent翻墙、GoAgent2翻墙还是pac蓝灯。GoAgent、2{（上传不了文件）翻墙黑框框里的信息是
![default](https://user-images.githubusercontent.com/24630043/28244518-793113de-6a1f-11e7-8a7b-29b98ab3cdee.jpg)

**Comment by Alvin9999** [comment]
如果不能翻墙，又特别想翻的话，可以试试这款[PAC版浏览器](https://github.com/Alvin9999/new-pac/wiki/PAC%E7%89%88)

![youtube2](https://user-images.githubusercontent.com/12132898/28258979-ae3ea5ea-6b06-11e7-8d9b-1aa3a57f6906.png)

**Comment by gugejun** [comment]
@Alvin9999   ##(大佬广告做的响当当，推广翻墙，给我往死里翻，同志们戳进来[往沟里翻](https://github.com/Alvin9999)

**Comment by bannedbook** [comment]
我们的一键翻墙包昨天刚刚更新，推荐更新试试看。
