### ISSUE TITLE
自建goagent服务器的问题

### ISSUE THREAD

**Issue by hoho1994** [bannedbook/fanqiang#152]
您好，我按照您提供的方法自建goagent服务器，在Google app engine里点击“deploy”后，浏览器未自动打开，信息框显示“Getting current resource limits”，请问该如何解决？

**Comment by Saujyun** [comment]
你解決了沒有？我也是這樣

**Comment by mymatrix2002** [comment]
@Saujyun@hoho1994
你们可以参考这个网址的自建appid和搜谷歌ip教程（GoAgent版和GoProxy版）
https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAappid%E5%92%8C%E6%90%9C%E8%B0%B7%E6%AD%8Cip%E6%95%99%E7%A8%8B%EF%BC%88GoAgent%E7%89%88%E5%92%8CGoProxy%E7%89%88%EF%BC%89
更加简单，不需要安装程序什么的
GoAgent和GoProxy都是同一个作者phuslu开发的，GoProxy目前依然在开发，GoAgent已经停止开发了。

**Comment by pppoooovip** [comment]
现在还行吗

**Comment by Saujyun** [comment]
非常感謝你，因為現在一直在用Chrome插件，所以就沒有怎樣去弄GoAgent

2017-10-13 21:13 GMT+08:00 pppoooovip <notifications@github.com>:

**Comment by bannedbook** [comment]
最新版 ChromeGo 里面 \ipv6-Agent1\code\default\gae_proxy\server 目录下
用 uploader.bat 来上传
具体看目录下的
README.md
