### ISSUE TITLE
无法获取火狐一键翻墙包

### ISSUE THREAD

**Issue by zmmj123** [bannedbook/fanqiang#153]
所有的链接都已经试过了，均不可以。能否请大家帮忙直接把文件发到我的邮件里，625046681@qq.com。或者还有没有更好的方法，非常感谢！
BT Sync下载：全新推出BT Sync下载，非常好用方便，永久自动同步，我们发布新版翻墙软件后，您会自动获得同步更新。BT Sync同步密钥: BG2G54AGRNPC5YXSTLQV5PNWL7ULYRIPC ，BT Sync（RESILIO SYNC）-下载神器，P2P同步利器和分布式网盘 --------软件无法下载！！！
Github下载：FirefoxFQ.7z -------------------------------网页无法打开！！！
mega网盘下载：FirefoxFQ.7z -------------------------------网页无法打开！！！
Google网盘下载(已墙，需翻墙下载)：FirefoxFQ.7z---------------------还未翻墙无法下载！！！
文件信息：文件名：FirefoxFQ.7z md5: c0d2d6e9f4bccbc87baa126d2c4de6f8，文件大小：83,356,761 字节 
更多翻墙软件 --------------------------------感觉火狐最好用，不想使用其它的！！！

**Comment by bannedbook** [comment]
可以百度搜索 ：
BT Sync 下载
下载一个BT Sync 软件
