### ISSUE TITLE
想了解shadowsocks技术，请提供教程。

### ISSUE THREAD

**Issue by Jeremyshilintong** [bannedbook/fanqiang#154]
想了解shadowsocks技术，请提供教程。

**Comment by Alvin9999** [comment]
[教程](https://github.com/Alvin9999/new-pac/wiki/ss%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7)

**Comment by ycountJavaXuan** [comment]
你们都怎么抄送给我的？？什么鬼？？？



在 2017年10月11日，11:39，如何翻墙 <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #154<https://github.com/bannedbook/fanqiang/issues/154>.

**Comment by bannedbook** [comment]
是不是你订阅过，你看你收到的email里面是否有取消订阅的链接。
你看上面说：You are receiving this because you are subscribed to this thread.
你点那个  unsubscribed 链接，取消订阅试试看
