### ISSUE TITLE
GOAGENT V3.2.3 教程使用中的问题

### ISSUE THREAD

**Issue by GrandArth** [bannedbook/fanqiang#155]
运行google app engine launcher时 deploy出现错误：
appcfg.py: error: Error parsing C:\Users\v2629\Desktop\goagent\app.yaml: mapping values are not allowed here
  in "C:\Users\v2629\Desktop\goagent\app.yaml", line 1, column 36.
2017-08-03 11:57:28 (Process exited with code 2)

app.yaml内容

application: goagent1-175703version: 1runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_gh/.*
  script: gae.application
  secure: optional

- url: /favicon.ico
  script: gae.application
  secure: optional

- url: /.*
  script: legacy.application
  secure: optional

libraries:
- name: pycrypto
  version: "latest"

**Comment by bannedbook** [comment]
最新版 ChromeGo 里面 \ipv6-Agent1\code\default\gae_proxy\server 目录下
用 uploader.bat 来上传
具体看目录下的
README.md
