### ISSUE TITLE
禁言代理和GoAgent刷YouTube记入数据吗

### ISSUE THREAD

**Issue by wwwwlau** [bannedbook/fanqiang#156]
请问 用这两个来刷mv播放量计数吗？？？
之前买了其他的vpn刷，结果问了发现并不计数。。。
希望能得到回复！！谢谢！！！
而且开了禁言代理之后，ip地址并没有变化诶还是显示中国的

**Comment by bannedbook** [comment]
这个不太清楚哦，可以用我们的翻墙包 试试看就知道啦
