### ISSUE TITLE
怎么不能翻了？

### ISSUE THREAD

**Issue by Jeremyshilintong** [bannedbook/fanqiang#157]
怎么不能翻了？

**Comment by bannedbook** [comment]
2017年10月10日全面升级[Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)/[火狐firefox一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/%E7%81%AB%E7%8B%90firefox%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)(for PC)，集成N种翻墙软件，欢迎下载。
