### ISSUE TITLE
hosts 不能翻墙了

### ISSUE THREAD

**Issue by yelianghuo** [bannedbook/fanqiang#159]
帮忙看看ｈｏｓｔｓ是否失效了　，麻烦了

**Comment by lanvsblue** [comment]
确实部分已经被墙

**Comment by bannedbook** [comment]
谢谢反馈，hosts文件更新了，请重新下载。
请帮忙看看更新后
https://usadns.info
https://cn.bannedbook.org
这2个网址可否打开
