### ISSUE TITLE
求2017年6月7日版的Chrome for XP

### ISSUE THREAD

**Issue by adazakura** [bannedbook/fanqiang#160]
想用firefly啊，更新了一下软件居然没了。

**Comment by adazakura** [comment]
有没有人可以发我邮箱，或者给个载点都可以，谢谢！
syxrb@yahoo.com

**Comment by bannedbook** [comment]
https://mega.nz/#!O0sFVTCI!uW08pWDFQpj8fDxhVxXdqP7s2hypBIWDhwY_kdfTca4

**Comment by adazakura** [comment]
谢谢老大！
