### ISSUE TITLE
翻墙翻不了了

### ISSUE THREAD

**Issue by zacbowdan** [bannedbook/fanqiang#162]
我用pAC自动代理，说服务器拒绝连接
蓝灯也不行
禁闻代理不行
貌似自由门和无界浏览目前有效
一键翻墙包全部失效
任何浏览器都不行
求帮助

**Comment by bannedbook** [comment]
2017年10月10日全面升级[Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)/[火狐firefox一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/%E7%81%AB%E7%8B%90firefox%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)(for PC)，集成N种翻墙软件，欢迎下载。
