### ISSUE TITLE
求Mac的谷歌翻墙插件！！！！

### ISSUE THREAD

**Issue by mikebar124** [bannedbook/fanqiang#163]
看到只有windows的，试了PAC没有成功，已装chrome浏览器，求Mac的插件～～～

**Comment by tanghui315** [comment]
https://fywall.cc   完全免费的插件，里面还提供ss账号，速度很快，多个地区的服务器可供选择和切换。youtube 高清不卡顿。

**Comment by bannedbook** [comment]
看这里
https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E7%94%B5%E8%84%91MAC%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6
