### ISSUE TITLE
关于manual.ini的问题

### ISSUE THREAD

**Issue by courser81** [bannedbook/fanqiang#164]
按照教程提示：
    请双击程序根目录的 GoAgent申请appid自建翻墙服务器 快捷方式查看申请appid教程。
申请的appid添加到Agent2文件夹的manual.ini中。

但是那个文件夹中没有这个文件，求大神指教，谢谢！

**Comment by bannedbook** [comment]
把proxy.ini复制后改名

**Comment by courser81** [comment]
也就是说改成manual.ini后直接把appid添加后不用再把文件名改回来了吗？谢谢

**Comment by bannedbook** [comment]
不要改回来的
