### ISSUE TITLE
原文被删除了！请大家转发！政府已经控制了GreatFire自由浏览和相关人员，使用自由浏览进行刑侦

### ISSUE THREAD

**Issue by guo392** [bannedbook/fanqiang#167]
原文已经被删除 https://github.com/greatfire/wiki/issues/196 请大家广泛转发！

## 我们对GitHub上残留的蛛丝马迹进行调查后发现政府已经控制了GreatFire自由浏览和相关人员以及所有账号密码，使用自由浏览进行刑侦，团队没有被控制的辟谣声明也是政府发布的，请大家务必小心！

证据如下

1 GreatFire先发布交界通报，后删除通报[进行辟谣]((https://github.com/greatfire/wiki/issues/194))。
GreatFire发布了GreatFire交接通告，表示已经将有关账号、代码、服务器和数据交接给相关开发机构继续开发。这应该是原团队的隐晦表示，实际上人员账号等已经被政府控制。
![image](https://user-images.githubusercontent.com/32114248/30621010-5309ef6c-9d98-11e7-8f28-d0ce10c235f4.png)
[交接公告的缓存](https://archive.fo/OyFNj#selection-835.31-835.61) 此交接通报已经被删除。
当政府意识到原开发团队偷偷表示团队已经被控制后，这个交界公告也被删除了。

2 GreatFire先通知下架纽约时报版面，当下架版面后，其删除了通报，再进行辟谣。而且政府不小心用同一个账号发表了辟谣和删除纽约时报，露出了马脚。
GreatFire之前发布“接到主管部分的通知，《纽约时报》应用含有违禁内容，立即进行一键关停。”  通知发布后，gfsupport这个账号把纽约时报的相关页面都删除了，截图如下
![image](https://user-images.githubusercontent.com/32114248/30620665-250ad664-9d96-11e7-9fcf-c09cbb8289d9.png)
而删除纽约时报的页面的和发布辟谣声明的是同一个账号。
![image](https://user-images.githubusercontent.com/32114248/30620684-5aaa980e-9d96-11e7-841e-005aabe046fc.png)

为什么GreatFire先发表通告表示下架纽约时报，下架后又发布辟谣声明呢？这是因为GreatFire在被调查时感觉时日无多，赶快发布声明自保。等到其被完全控制，账号密码都交给政府后，政府为了使用自由浏览的用户数据来进行秘密调查，发布了辟谣声明，防止打草惊蛇，但不小心使用了同一个账号，弄巧成拙。因为纽约时报有政府不喜欢的内容，而且不像自由浏览一样可以收集用户的Gmail和地理位置等数据，政府对其进行了删除，只留下一个自由浏览来继续秘密侦查。政府想要继续秘密调查，所以故意发布了一个辟谣声明。但是相关人员不不知道Github会公开进行删除操作的账号，使用了删除纽约时报版面的账号来发布辟谣声明，露出了马脚。

政府也意识到有些蛛丝马迹留在Github上，把之前原团队发的GreatFire下架纽约时报的通知也删除了，[缓存版本链接](https://archive.fo/wPqBw#selection-831.0-831.34) ，但是其不知道缓存是永远没办法删除滴。

3 自由浏览会自动获取身份信息、通讯录、位置信息、照片/媒体/文件、摄像头、麦克风、下载文件而不显示通知、开机启动、使用设备上的帐号和其他各种敏感权限。
![image](https://user-images.githubusercontent.com/32114248/30621354-38b4296e-9d9a-11e7-8f0e-82ecffa766b4.png)
![image](https://user-images.githubusercontent.com/32114248/30621376-4e1c5402-9d9a-11e7-97ec-299fa2d16208.png)
![image](https://user-images.githubusercontent.com/32114248/30621394-5d2738ea-9d9a-11e7-80bf-411c1eace4c6.png)
一个翻墙软件需要获取如此之多的敏感信息，就是为了方便政府追查某些翻墙人员。所以政府正在努力掩盖自由浏览是刑侦工具的事实。请大家务必小心！

**Comment by qwas982** [comment]
感谢告知.
哪里有压迫哪里就有反抗,

**Comment by ygsk10** [comment]
刚才发现[greatfire分析器](https://en.greatfire.org/contact)的公钥都已经过期了，Charlie Smith的在7/14/17, Martin Johnson的在9/20/17

**Comment by fbion** [comment]
mark
