### ISSUE TITLE
目前看来很多都不行了，只有蓝灯还行

### ISSUE THREAD

**Issue by Johnkyens** [bannedbook/fanqiang#168]
XXNET也扑街，功夫wang好像大升级了一次，已经投降买了lantern专业版

用这个YMG4FRT
买两年额外送三个月 一年送一个月

不想花钱没法，某风啥的又经常断线。。。真的无可奈何了

大神们如果接受众筹我也支持。。。

谁有能用都免费工具也希望交流下

**Comment by lon91ong** [comment]
XX-Net开启IPv6还能继续战斗，关键是[开启方法](https://github.com/XX-net/XX-Net/issues/6918)不挑食(ISP支持IPv6与否)

**Comment by bannedbook** [comment]
2017年10月10日全面升级Chrome一键翻墙包/火狐firefox一键翻墙包(for PC)，集成N种翻墙软件，欢迎下载。

**Comment by Xianmua** [comment]
额我这边的网络开不了ipv6，，，郁闷。挺好的xxnet，唉。bannedbook想必也是大牛，没想到现在还有能用的免费软件，，我还郁闷的就是，抛开真实性不谈，我不了解禁闻的真假。只是如此大张旗鼓地宣传禁闻，万一github被屏蔽了咋办？，，，我的github，，从技术上来说，我很佩服bannedbook大牛，向你学习，，

**Comment by charleshw** [comment]
蓝灯邀请码 JBKQY8 安卓系统9.0   浙江移动使用正常，台式机win10使用正常

**Comment by bannedbook** [comment]
全面升级[Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)/[火狐firefox一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/%E7%81%AB%E7%8B%90firefox%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)(for PC)，集成N种翻墙软件，欢迎下载。
