### ISSUE TITLE
[Errno 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by rapemeonFriday** [bannedbook/fanqiang#169]
显示这个502错误是怎么回事昂？小白求解，勉强看代码难道是isp被占用了？

**Comment by lon91ong** [comment]
目前使用XX-Net 开启IPv6挺好使，关键是这个[开启IPv6的方法](https://github.com/XX-net/XX-Net/issues/6918)对网络环境（ISP支持IPv6与否）无关，成功率很高

**Comment by rapemeonFriday** [comment]
所以这个问题502究竟是个什么问题呢？？XX-Net是什么昂。。。我很笨但是我很温油lol

**Comment by ycountJavaXuan** [comment]
——
502一般是网关错误。Bad Gateway

首先看看能不能ping通网关。
其次看看你有没有使用nginx。如果有使用的话看看nginx的日志信息。


XX-Net用来翻墙的




在 2017年10月8日，17:19，Rape Me on Friday <notifications@github.com<mailto:notifications@github.com>> 写道：


所以这个问题502究竟是个什么问题呢？？XX-Net是什么昂。。。我很笨但是我很温油lol

**Comment by bannedbook** [comment]
上传最新版，请下载更新
