### ISSUE TITLE
为什么完整版自带的谷歌chrome浏览器会崩溃？

### ISSUE THREAD

**Issue by Xianmua** [bannedbook/fanqiang#176]
如题，浏览器崩溃，界面直接是一片黑，打不开网站。然后我把原来解压的删了，重新解压下使用，就又好了，这是怎么回事呢？用了才两三个小时就崩溃了，bannedbook大佬知道怎么回事吗？
----
我刚才又重新打开了下，就又好了，自动崩溃，自动变好额，，，用着用着谷歌突然就连不上网了，，崩溃十几分钟就又变好了额，，浏览器已经崩溃好几次了

**Comment by bannedbook** [comment]
这个很难说啊

**Comment by 18428329295** [comment]
找不到 chrome.exe   不管是下的完整版还是简单版（电脑上也有谷歌浏览器）

**Comment by ycountJavaXuan** [comment]
你是windows么一般是在C:\Program Files (x86)\Google\Chrome\Application下面


在 2017年10月19日，15:42，18428329295 <notifications@github.com<mailto:notifications@github.com>> 写道：


找不到 chrome.exe 不管是下的完整版还是简单版（电脑上也有谷歌浏览器）

**Comment by 18428329295** [comment]
运行批处理文件时提示找不到

**Comment by bannedbook** [comment]
把程序不要放到包含中文和空格的路径，然后试试看
