### ISSUE TITLE
分享一个私藏很久的免费科学上网Chrome插件，飞岩插件，https://fywall.cc

### ISSUE THREAD

**Issue by tanghui315** [bannedbook/fanqiang#177]
分享一个私藏很久的免费科学上网Chrome插件，还提供ss账号，YouTube跑1080p不卡顿，真的好用。用的人很少，为了防止被封，据说此插件注册量有限制，先到先得。https://fywall.cc

**Comment by Robot-L** [comment]
试了一下，果然不错，谢题主分享，不过只能免费用100兆流量，注册的时候填写邀请码，可以多免费用3天，`5BD0001E758B3190E7B3B59057BD0B32`

**Comment by Linbubin** [comment]
@tanghui315 @Robot-L  现在还能上么？  我的已经不行了

**Comment by Robot-L** [comment]
@Linbubin 好像是挂了，插件的生命周期还是短啊，还是用github上的开源翻墙项目吧
