### ISSUE TITLE
系统一直提示windows找不到chrome.exe

### ISSUE THREAD

**Issue by xiaoqiangicon** [bannedbook/fanqiang#178]
我已经安装了Chrome，但是还是一直提示我找不到chrome.exe是什么情况呢。

**Comment by bannedbook** [comment]
程序不要放在有 中文 或 空格的路径下，然后再试试看

**Comment by xiaoqiangicon** [comment]
没有放在中文和空格的路径，之前装在c盘的application里了。应该不是要安装在d盘才有用吧。因为之前提示我d:/chrom没有找到，然后我把一些安装文件复制到了d盘，就没有再报这个错误。

**Comment by bannedbook** [comment]
是 下载的轻便版吗

**Comment by xiaoqiangicon** [comment]
是的，下载的是轻便版。

**Comment by bannedbook** [comment]
把chrome.exe所在的路径添加到系统环境变量 path 里面

**Comment by xiaoqiangicon** [comment]
刚才那个问题已解决，但是还是无法使用，cmd扫描ip显示系统找不到指定的路径。弹出的chrome界面也无法访问，这种情况可以通过自建流量解决吗？

**Comment by bannedbook** [comment]
你用哪个脚本启动的

**Comment by xiaoqiangicon** [comment]
GoAgent0翻墙.cmd这几个都试过了，还有firefly也试过，都是一样的错误。是不是因为我是自己复制的d:/chrom文件导致的呢？

**Comment by bannedbook** [comment]
你是把程序解压到了 d:\chrom 文件夹吗

**Comment by xiaoqiangicon** [comment]
没有，我的程序解压在了chrome download文件夹里面。也是在d盘

**Comment by bannedbook** [comment]
chrome download 中间的空格去掉试试看

**Comment by modrad** [comment]
请问，把chrome.exe所在的路径添加到系统环境变量 path 里面 这里说的path在哪里找？

**Comment by bannedbook** [comment]
Windows 7
在桌面上右键单击计算机图标。
从上下文菜单中选择属性。
单击高级系统设置链接。
单击环境变量。 在系统变量部分中，找到并选择 PATH 环境变量。 单击编辑。 ...
在编辑系统变量（或新建系统变量）窗口中，指定 PATH 环境变量的值。 单击确定。 ...

**Comment by modrad** [comment]
谢谢！@bannedbook

**Comment by xiaoqiangicon** [comment]
根据您的方法我已经能通过firefly上网，但是存在的问题使弹出的谷歌浏览器不能登录，新开页面也无法访问外网，请问这是正常的吗。另外我打开GoAgent0翻墙.cmd这几个脚本无法上网，cmd提示我第一次启动需要扫描ip，但是下一行是按任意键继续，按了键以后就关闭了。浏览器那边得到的是一个JSon格式的数据。

**Comment by bannedbook** [comment]
除了任意键继续那个窗口外，应该还有一个dos窗口，看另外一个dos窗口显示什么。
下载解压后进入Agent0\ip_Update文件夹运行一键更新ip文件来同步Agent0到最新的云端配置，其它Agent2、Agent3、GoProxy Quic版也需类似操作，建议不好用时即可尝试更新IP试试。Agent1和Agent4自动扫描IP无须手工更新。第一次启动时，请点右键，以管理员身份启动，否则可能出现https不是私密链接问题。

**Comment by xiaoqiangicon** [comment]
ip更新以后还是出现同样的问题。dos窗口显示的是no recent network activity，有时候是with good_addrs=0,bad_adds=152.good的数字一直是0，bad的数字是改变的。

**Comment by bannedbook** [comment]
chromego这个文件夹里面有：
Firefly翻墙.cmd
GoAgent0翻墙.cmd
GoAgent1翻墙.cmd
GoAgent2翻墙.cmd
GoAgent3翻墙.cmd
GoAgent4翻墙.cmd
ipv6-Agent0翻墙.cmd
ipv6-Agent1翻墙.cmd

GoGo翻墙.cmd
PAC翻墙.cmd
v2ray翻墙.cmd
蓝灯翻墙.cmd
这么多种翻墙方法，其中前面7个第一次启动时以右键，管理员身份启动。
2个ipv6的，先看对应的ipv6-Agent0翻墙.使用说明（必看）.rtf、ipv6-Agent1翻墙.使用说明（必看）.rtf 设置好ipv6环境再启动。

下载解压后进入Agent0\ip_Update文件夹运行一键更新ip文件来同步Agent0到最新的云端配置，其它Agent2、Agent3、GoProxy Quic版、ipv6-Agent0、ipv6-Agent1也需类似操作，建议不好用时即可尝试更新IP试试。Agent1和Agent4自动扫描IP无须手工更新。

每一个都试一试，肯定有能用的。尤其最新的2个ipv6方法，很多网友反馈都可用。

**Comment by saberys** [comment]
ChromeGo_Sky版的访问越来越慢了 怎么办？ 不稳定了

**Comment by bannedbook** [comment]
那就换 chromego 普通版，里面的agent3、蓝灯、v2ray翻墙还不错

**Comment by LiulegeBo** [comment]
压缩软件有密码，打不开。。

**Comment by bannedbook** [comment]
密码：
jww

**Comment by zhisheng1024** [comment]
你怎么把方法删了呀。。。。不久前按你方法改了什么导致我chrom快捷方式出问题了，现在想改回去，关键我忘了当时是怎么按你方法改的了？？？？

**Comment by bannedbook** [comment]
没删，都在上面

**Comment by zhihucocoa** [comment]
我也是按照你说的方法，设置过path环境变量了，chrome.exe也在，但是还是搜不到可能是怎么回事呢？

**Comment by zhihucocoa** [comment]
E:\Google\Chrome\Application\chrome.exe

这是位置，也没有中文和空格啊......

**Comment by bannedbook** [comment]
你开个命令行 窗口，自己 键入 chrome.exe 看看能不能找到

**Comment by 1836274669** [comment]
一直显示找不到文件win10

**Comment by 1836274669** [comment]
版主，win10解压后一直显示找不到chrome-gomaiter

**Comment by bannedbook** [comment]
程序不要放在有 中文 或 空格的路径下
还不行的话，chrome.exe 所在路径加到 系统 path 环境变量里面

**Comment by hexinliu** [comment]
打开蓝灯翻墙，就找不到lantern.exe  用v2ray翻墙，就找不到v2ray.exe   这是咋解决

**Comment by bannedbook** [comment]
程序不要解压到包含中文或空格的路径。关闭卸载国产杀毒安全软件再试试看

**Comment by hexinliu** [comment]
OK了  多谢

**Comment by fxwwww** [comment]
我可以在命令行中找到chrome.exe，也调了path，但是还是显示GoogleChrome打不开？这是怎么回事呢

**Comment by bannedbook** [comment]
打开命令行，执行下：
`%SystemRoot%\System32\reg.exe query "HKLM\Software\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe"`
看能不能找到 chrome.exe

**Comment by fxwwww** [comment]
找不到。。因为不是最新版本吗？

**Comment by bannedbook** [comment]
找不到，说明chrome没有正常安装好。重装一下chrome试试看

**Comment by fxwwww** [comment]
好的

**Comment by lys811074556** [comment]
大家好，我下载到电脑g盘里面，我能看见文件但就是打不开，一点击文件就出现闪屏闪退

**Comment by Alvin9999** [comment]
> 大家好，我下载到电脑g盘里面，我能看见文件但就是打不开，一点击文件就出现闪屏闪退

文件的解压路径换一下。

**Comment by carpediem187** [comment]
请问为什么我的解压后只有一个使用说明，以下你说的我都没找到呢
2个ipv6的，先看对应的ipv6-Agent0翻墙.使用说明（必看）.rtf、ipv6-Agent1翻墙.使用说明（必看）.rtf 设置好ipv6环境再启动。

下载解压后进入Agent0\ip_Update文件夹运行一键更新ip文件来同步Agent0到最新的云端配置，其它Agent2、Agent3、GoProxy Quic版、ipv6-Agent0、ipv6-Agent1也需类似操作，建议不好用时即可尝试更新IP试试。Agent1和Agent4自动扫描IP无须手工更新。

**Comment by carpediem187** [comment]
是要重新再下载一遍你的chromego包吗？

**Comment by carpediem187** [comment]
![crh0](https://github.com/bannedbook/fanqiang/assets/73506529/b7d41367-d0bc-4960-8fbb-bd7e342232e2)
这个s是最新的吧，那我在下载一次

**Comment by carpediem187** [comment]
> chromego这个文件夹里面有： Firefly翻墙.cmd GoAgent0翻墙.cmd GoAgent1翻墙.cmd GoAgent2翻墙.cmd GoAgent3翻墙.cmd GoAgent4翻墙.cmd ipv6-Agent0翻墙.cmd ipv6-Agent1翻墙.cmd
> 
> GoGo翻墙.cmd PAC翻墙.cmd v2ray翻墙.cmd 蓝灯翻墙.cmd 这么多种翻墙方法，其中前面7个第一次启动时以右键，管理员身份启动。 2个ipv6的，先看对应的ipv6-Agent0翻墙.使用说明（必看）.rtf、ipv6-Agent1翻墙.使用说明（必看）.rtf 设置好ipv6环境再启动。
> 
> 下载解压后进入Agent0\ip_Update文件夹运行一键更新ip文件来同步Agent0到最新的云端配置，其它Agent2、Agent3、GoProxy Quic版、ipv6-Agent0、ipv6-Agent1也需类似操作，建议不好用时即可尝试更新IP试试。Agent1和Agent4自动扫描IP无须手工更新。
> 
> 每一个都试一试，肯定有能用的。尤其最新的2个ipv6方法，很多网友反馈都可用。

哥，你这个最新版我怎么找不到啊，我下载了一个 1月27更新的chromego，里面还是没有这些啊

**Comment by bannedbook** [comment]
那不是最新版，最新版没有那些 Agent ipv6 之类的东西

**Comment by carpediem187** [comment]
![ttttttt208](https://github.com/bannedbook/fanqiang/assets/73506529/8684e5e9-973a-48df-8d63-c9666a54d052)
这个是最新版本吧

**Comment by bannedbook** [comment]
是

**Comment by carpediem187** [comment]
哥，我想问下有没有速度比较快的vpn，在colab上运行好慢啊，可以帮忙推荐下吗，

**Comment by bannedbook** [comment]
> 哥，我想问下有没有速度比较快的vpn，在colab上运行好慢啊，可以帮忙推荐下吗，

https://github.com/bannedbook/fanqiang/wiki/V2ray%E6%9C%BA%E5%9C%BA

**Comment by LancelotHolmes** [comment]
逐个试了，也没报错，但是打开chrome浏览器搜索也还是没有用，请问这种是什么原因呢？
![image](https://github.com/bannedbook/fanqiang/assets/15278783/b9bcecd8-7703-4818-a535-a613e43a77a9)

**Comment by gyy142** [comment]
为什么cmd里面显示windows找不到文件

**Comment by bannedbook** [comment]
找不到什么文件

**Comment by gyy142** [comment]
> 找不到什么文件

ip一直更新失败。说‘....wegt’不是命令，也不是程序无法运行
