### ISSUE TITLE
 chrome go 从昨晚就不能翻墙了，所有的翻墙软件都不行Firefox上个星期就不行了，蓝灯也不行

### ISSUE THREAD

**Issue by snapedumbledore** [bannedbook/fanqiang#179]
![default](https://user-images.githubusercontent.com/29865320/31944097-8351a860-b8fd-11e7-9990-6c95ecbdb7a6.png)

**Comment by genjigjj** [comment]
19大你懂的

**Comment by niuchawei** [comment]
厉害 那么大家现在在用啥？

**Comment by snapedumbledore** [comment]
这两天都没翻出去，很是无语啊

**Comment by jiubajiuma** [comment]
是啊   我也是  今天刚刚在这里找到一个方法进来   还不知道可以用多久

**Comment by snapedumbledore** [comment]
有没有人有资源啊，求分享

**Comment by Alvin9999** [comment]
https://github.com/Alvin9999/new-pac/wiki

**Comment by snapedumbledore** [comment]
非常感谢提供资源，然而我下载了五六个，只有自由门能用，而且速度不忍直视啊，还有其他的吗 @Alvin9999

**Comment by snapedumbledore** [comment]
更新了IP也没用

**Comment by Alvin9999** [comment]
@snapedumbledore  所有的软件都在主页上。

**Comment by terryandjing** [comment]
火狐一键翻墙包现在只有firefly能用了

**Comment by snapedumbledore** [comment]
![z mb ok e 94ym20fh9u b](https://user-images.githubusercontent.com/29865320/32054484-139256ec-ba91-11e7-8b32-2c4ae4ae05d3.png)
我的都是这种情况啊
![e yd0 a0hhw8_hi33u b](https://user-images.githubusercontent.com/29865320/32054727-02c1d24c-ba92-11e7-8875-38ace8448f17.png)

**Comment by snapedumbledore** [comment]
我这里firefly也不能用了..........

**Comment by Alvin9999** [comment]
@snapedumbledore  
Quic版更新ip后还是无法使用的话，建议优先尝试ipv6版，前提是电脑系统开启ipv6，软件说明文档有介绍，主页上介绍的更详细[开启ipv6方法](https://github.com/Alvin9999/new-pac/wiki/ipv6%E5%BC%80%E5%90%AF%E6%96%B9%E6%B3%95)

其次是v2ray版和kelphon版。别灰心，也许希望就在眼前。

**Comment by snapedumbledore** [comment]
嗯嗯，谢谢了，我试一下

**Comment by HiStandard** [comment]
我现在用GoAgent的IPv6版能够翻墙，新出的v2ray和Kelphon这两个软件还没试过

**Comment by Alvin9999** [comment]
@HiStandard  多备用几款软件，以备不时之需。

**Comment by HiStandard** [comment]
@Alvin9999 感谢您整理提供的这些软件，IPv4的IP段被共匪封的太厉害，之前我一直GoProxy自扫Google IP来翻墙，现在几百万的IP一个也扫不到了

**Comment by bannedbook** [comment]
可以先用这个 直连网址  https://git.io/gfree

**Comment by bannedbook** [comment]
klephon 似乎用不了，海外都不行

**Comment by terryandjing** [comment]
http://e33.j887.cf/
这个网址打不开，要先翻墙吗？

**Comment by bannedbook** [comment]
@terryandjing  给 juyuange@gmail.com  这个人反馈

**Comment by bannedbook** [comment]
2017年10月27日 升级Chrome一键翻墙包，增加了2个ipv6版的翻墙方法，以及v2ray翻墙，适合锁严重的地区。下载后请查看ipv6-Agent0翻墙.使用说明（必看）.rtf和ipv6-Agent1翻墙.使用说明（必看）.rtf和v2ray翻墙.使用说明（必看）.rtf。

**Comment by deadcn** [comment]
升级的可以用了, 可是youtubue视频几乎是慢得不行，要么就登不了。希望可以改善。谢谢。

**Comment by bannedbook** [comment]
升级了，请下载更新
