### ISSUE TITLE
已经不能正常使用了

### ISSUE THREAD

**Issue by xiaonaiping** [bannedbook/fanqiang#180]
china shanghai can't use it normally

**Comment by bannedbook** [comment]
2017年10月27日 升级Chrome一键翻墙包，增加了2个ipv6版的翻墙方法，以及v2ray翻墙，适合锁严重的地区。下载后请查看ipv6-Agent0翻墙.使用说明（必看）.rtf和ipv6-Agent1翻墙.使用说明（必看）.rtf和v2ray翻墙.使用说明（必看）.rtf。

**Comment by deadcn** [comment]
现在在没有翻墙的情况下，下载升级的数据包都非常难。速度慢得不行，慢到不断中断。

**Comment by bannedbook** [comment]
试试看这个新的下载链接
https://ipfs.io/ipns/QmdRaB7BPW4hE8UdNN5M6VdCTPG6c8AN269UrqjVYc42xC

**Comment by bannedbook** [comment]
更新了，请重新下载。
