### ISSUE TITLE
都不支持Mac啊...  心累

### ISSUE THREAD

**Issue by Zhulmin** [bannedbook/fanqiang#182]

**Comment by bannedbook** [comment]
可以试试 pac翻墙 https://github.com/bannedbook/fanqiang/wiki/pacfq

**Comment by Alvin9999** [comment]
可以试试[MAC翻墙方法](https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E7%94%B5%E8%84%91MAC%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6)

**Comment by ycountJavaXuan** [comment]
都是免费的么😀ོ
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 自由上网 <notifications@github.com>
发送时间: 2017年10月29日 09:18
收件人: bannedbook/fanqiang <fanqiang@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[bannedbook/fanqiang] 都不支持Mac啊... 心累 (#182)


可以试试MAC翻墙方法<https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E7%94%B5%E8%84%91MAC%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6>

**Comment by Alvin9999** [comment]
当然

**Comment by myh215** [comment]
能不能支持下mac啊
