### ISSUE TITLE
火狐与Chrome拥有同一个BT Sync同步密钥

### ISSUE THREAD

**Issue by just4look** [bannedbook/fanqiang#183]
火狐与Chrome拥有同一个BT Sync同步密钥，但同步的只有Chrome，请查验，谢谢！

**Comment by bannedbook** [comment]
谢谢提醒，因为火狐这次没有更新

**Comment by just4look** [comment]
原来都在里面，不好意思

**Comment by just4look** [comment]
我与国内的朋友试了，还是不能用，是不是我们做错了什么？

**Comment by bannedbook** [comment]
火狐 FirefoxFQ.7z 这次没有更新，是10月10更新的。
你的意思是 FirefoxFQ.7z  文件消失了吗

**Comment by just4look** [comment]
不是，你的包没有问题，文件在都正常。国内的朋友试了，翻不了墙。

**Comment by bannedbook** [comment]
有没有试新添加的2个ipv6版翻墙方法

**Comment by just4look** [comment]
不知道怎么添加，好像只是直接运行一键启动。

**Comment by just4look** [comment]
只是按照文档要求，一步一步做的。

**Comment by bannedbook** [comment]
chromego这个文件夹里面有：
Firefly翻墙.cmd
GoAgent0翻墙.cmd
GoAgent1翻墙.cmd
GoAgent2翻墙.cmd
GoAgent3翻墙.cmd
GoAgent4翻墙.cmd
ipv6-Agent0翻墙.cmd
ipv6-Agent1翻墙.cmd

GoGo翻墙.cmd
PAC翻墙.cmd
v2ray翻墙.cmd
蓝灯翻墙.cmd
这么多种翻墙方法，其中前面7个第一次启动时以右键，管理员身份启动。
2个ipv6的，先看对应的ipv6-Agent0翻墙.使用说明（必看）.rtf、ipv6-Agent1翻墙.使用说明（必看）.rtf 设置好ipv6环境再启动。

**Comment by just4look** [comment]
好，谢谢！

**Comment by bannedbook** [comment]
下载解压后进入Agent0\ip_Update文件夹运行一键更新ip文件来同步Agent0到最新的云端配置，其它Agent2、Agent3、GoProxy Quic版、ipv6-Agent0、ipv6-Agent1也需类似操作，建议不好用时即可尝试更新IP试试。Agent1和Agent4自动扫描IP无须手工更新。

**Comment by just4look** [comment]
这个与文档里一样的，我们再试试，谢谢！
