### ISSUE TITLE
是不是笔记本如果连接的是无线就不能用

### ISSUE THREAD

**Issue by weber0000** [bannedbook/fanqiang#184]
是不是笔记本如果连接的是无线就不能用

**Comment by bannedbook** [comment]
chromego这个文件夹里面有：
Firefly翻墙.cmd
GoAgent0翻墙.cmd
GoAgent1翻墙.cmd
GoAgent2翻墙.cmd
GoAgent3翻墙.cmd
GoAgent4翻墙.cmd
ipv6-Agent0翻墙.cmd
ipv6-Agent1翻墙.cmd

GoGo翻墙.cmd
PAC翻墙.cmd
v2ray翻墙.cmd
蓝灯翻墙.cmd
这么多种翻墙方法，其中前面7个第一次启动时以右键，管理员身份启动。
2个ipv6的，先看对应的ipv6-Agent0翻墙.使用说明（必看）.rtf、ipv6-Agent1翻墙.使用说明（必看）.rtf 设置好ipv6环境再启动。

下载解压后进入Agent0\ip_Update文件夹运行一键更新ip文件来同步Agent0到最新的云端配置，其它Agent2、Agent3、GoProxy Quic版、ipv6-Agent0、ipv6-Agent1也需类似操作，建议不好用时即可尝试更新IP试试。Agent1和Agent4自动扫描IP无须手工更新。

每一个都试一试，肯定有能用的。
