### ISSUE TITLE
Chrome61_GP_Quic (1)  用2天就不能用了

### ISSUE THREAD

**Issue by deadcn** [bannedbook/fanqiang#185]
Chrome61_GP_Quic (1)  用2天就不能用了。这2天都非常顺畅。今天打开电脑上时，发现google浏览不是单独启动的。本来点一键启动，是自动单独一个google窗口出来就可以链接上。现在合并到我电脑本身安装的谷歌浏览器，所以也就是上不了了。请问有什么办法解决。

**Comment by bannedbook** [comment]
下载 最新 chromego，里面已包含了 Quic版。

chromego这个文件夹里面有：
Firefly翻墙.cmd
GoAgent0翻墙.cmd
GoAgent1翻墙.cmd
GoAgent2翻墙.cmd
GoAgent3翻墙.cmd
GoAgent4翻墙.cmd
ipv6-Agent0翻墙.cmd
ipv6-Agent1翻墙.cmd

GoGo翻墙.cmd
PAC翻墙.cmd
v2ray翻墙.cmd
蓝灯翻墙.cmd
这么多种翻墙方法，其中前面7个第一次启动时以右键，管理员身份启动。
2个ipv6的，先看对应的ipv6-Agent0翻墙.使用说明（必看）.rtf、ipv6-Agent1翻墙.使用说明（必看）.rtf 设置好ipv6环境再启动。

下载解压后进入Agent0\ip_Update文件夹运行一键更新ip文件来同步Agent0到最新的云端配置，其它Agent2、Agent3、GoProxy Quic版、ipv6-Agent0、ipv6-Agent1也需类似操作，建议不好用时即可尝试更新IP试试。Agent1和Agent4自动扫描IP无须手工更新。

每一个都试一试，肯定有能用的。

**Comment by deadcn** [comment]
好，谢谢。 下载试试 看 ChromeGo.7z。
Chrome61_GP_Quic (1) 速度比较快。刚试了下，重新解压文件夹，再点一键启动，就有单独的翻墙的谷歌浏览器出来，就可以了。

**Comment by wjp8057** [comment]
解压密码是什么啊？

**Comment by weber0000** [comment]
jww
