### ISSUE TITLE
请教一下，卡在了“下载 goagent 并上传至 Google App Engine”，该如何解决？

### ISSUE THREAD

**Issue by nongxi** [bannedbook/fanqiang#188]
1.错误提示：appcfg.py: error: Error parsing F:\Goagent\goagent\goagent\app.yaml: mapping values are not allowed here，这是表示未在允许区域吗？
2.该怎么样解决比较好，前面一直是按照教程来做的，该安装的也安装了该上传的也上传了，但卡在了这里，该怎么样解决会比较好，表示下载的文件包括文件的位置都没有放在系统盘，放在了F盘下面，这样会有影响吗？

**Comment by bannedbook** [comment]
app.yaml 仔细检查这个文件，貌似说这个文件的格式不对

**Comment by nongxi** [comment]
重新试了一下貌似还是有点问题0.0

**Comment by bannedbook** [comment]
也可以试试这个新方法（有更新）：
[GoAgent 自建appid](https://github.com/bannedbook/fanqiang/wiki/GoAgent-v3.2.3---%E8%87%AA%E5%BB%BA%E7%BF%BB%E5%A2%99%E6%9C%8D%E5%8A%A1%E5%99%A8)
