### ISSUE TITLE
火狐更新到Firefox Quantum，无界插件不能用了，怎么办？

### ISSUE THREAD

**Issue by MXCYU** [bannedbook/fanqiang#190]
火狐更新到Firefox Quantum，无界插件不能用了，怎么办？

**Comment by wansheg** [comment]
jiasuqi.xyz

**Comment by 2848203063** [comment]
VPN收费系统
VPN主服务器 + 分服务器 + 网站管理 +流量控制系统 + 收费系统
搭建你自己的VPN服务器收费系统

http://148.163.171.13 

上TB租一个VPS 装个win2003 再装这个系统 就可以用了
使用有问题的联系QQ 2848203063
网上找到免费的，不用谢

**Comment by bannedbook** [comment]
把下载的压缩包，换个目录重新解压一下，还用老的
