### ISSUE TITLE
建议撤下萤火虫代理！

### ISSUE THREAD

**Issue by wukongtuwen** [bannedbook/fanqiang#196]
萤火虫代理完全没有flg相关网站，而且还有五毛网站，立场偏向性非常明显。打开的主页，还重点推荐了北风温云超的“翻墙后”站点，这个北风据说是大外宣特务。

所以说，这个代理，不但没有安全性，而且没有好的导向。完全不应该推荐，建议立即撤下。

**Comment by sevensky** [comment]
确实是，这款软件很危险
