### ISSUE TITLE
googleappengine安装包不能打开

### ISSUE THREAD

**Issue by lhsssss** [bannedbook/fanqiang#200]
打开安装包弹出对话框，上面显示“无法打开此安装程序包,请确认该程序包存在,并且有权访问它,或者与应用程序供应商联系,以确认这是一个有效的Windows Installer程序包”，应该如何解决？？

**Comment by bannedbook** [comment]
是什么安装包

**Comment by lhsssss** [comment]
GoogleAppEngine-1.9.50

**Comment by bannedbook** [comment]
GoogleAppEngine-1.9.50.msi 文件大小 57,552,896 字节  md5校验值：6a49d06eea39efc56ff07006fdf0963c

核对下文件下载完整了没

**Comment by lhsssss** [comment]
可以了　和你猜测的一样，没下载完整　谢谢～我继续往后走啦！！！
