### ISSUE TITLE
deploy后不能通过

### ISSUE THREAD

**Issue by lhsssss** [bannedbook/fanqiang#202]
app.yaml里的内容为

application: lhs001-187712
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_gh/.*
script: gae.application
secure: optional

- url: /favicon.ico
script: gae.application
secure: optional

- url: /.*
script: legacy.application
secure: optional

libraries:

name: pycrypto
version: "latest"

弹出窗口显示：
2017-12-03 15:27:45 Running command: "['E:\\phyton\\pythonw.exe', '-u', 'E:\\sdk\\appcfg.py', '--oauth2_credential_file=C:\\Users\\Liu Hongshen/.appcfg_oauth2_tokens', 'update', u'E:\\goagent\\goagent']"
Usage: appcfg.py [options] update <directory> | [file, ...]

appcfg.py: error: Error parsing E:\goagent\goagent\app.yaml: Unknown url handler type.
<URLMap 
    secure=default 
    static_files=None 
    application_readable=None 
    auth_fail_action=redirect 
    require_matching_file=None 
    static_dir=None 
    redirect_http_response_code=None 
    http_headers=None 
    url=/_gh/.* 
    script=None 
    upload=None 
    api_endpoint=None 
    expiration=None 
    position=None 
    login=optional 
    mime_type=None
    >
  in "E:\goagent\goagent\app.yaml", line 10, column 1.
2017-12-03 15:27:50 (Process exited with code 2)

You can close this window now.

请问这个怎么解决?

**Comment by bannedbook** [comment]
建议重新下载 goagent.zip ,从新编辑 app.yaml
用 editplus 或者 notpat++, 不要用notepad

**Comment by bannedbook** [comment]
也可以试试这个新方法（有更新）：
[GoAgent 自建appid](https://github.com/bannedbook/fanqiang/wiki/GoAgent-v3.2.3---%E8%87%AA%E5%BB%BA%E7%BF%BB%E5%A2%99%E6%9C%8D%E5%8A%A1%E5%99%A8)

**Comment by bannedbook** [comment]
最新版 ChromeGo 里面 \ipv6-Agent1\code\default\gae_proxy\server 目录下
用 uploader.bat 来上传
具体看目录下的
README.md
