### ISSUE TITLE
RSYNC 已和谐，如何同步fangqiang软件？

### ISSUE THREAD

**Issue by fartinthewind** [bannedbook/fanqiang#206]
首先感谢bannedbook君的分享。
如今RSYNC惨遭和谐，提示“没有可用的跟踪程序连接”，如何再次同步更新fangqiang内的软件出去领略大千世界？

**Comment by bannedbook** [comment]
试试这个 [使用 IPFS 来下载和传播翻墙软件](https://github.com/bannedbook/fanqiang/blob/master/ipfs-qanqiang.md)

**Comment by yiasoall** [comment]
<html>
<body>

推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>

**Comment by bannedbook** [comment]
[聊聊 GFW 如何封杀 Resilio Sync（BTSync）？以及如何【免翻墙】继续使用？](https://github.com/bannedbook/fanqiang/blob/master/RESILIO-SYNC/btfq.md)
