### ISSUE TITLE
GoogleAppEngine-1.9.50.msi无法打开此安装程序包

### ISSUE THREAD

**Issue by sippp** [bannedbook/fanqiang#208]
安装错误 请朋友们说说这是什么原因

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/issues/200

**Comment by bannedbook** [comment]
也可以试试这个新方法（有更新）：
[GoAgent 自建appid](https://github.com/bannedbook/fanqiang/wiki/GoAgent-v3.2.3---%E8%87%AA%E5%BB%BA%E7%BF%BB%E5%A2%99%E6%9C%8D%E5%8A%A1%E5%99%A8)
