### ISSUE TITLE
BT Sync 同步密钥无法同步

### ISSUE THREAD

**Issue by pinkchina** [bannedbook/fanqiang#216]
BT Sync同步密钥: BG2G54AGRNPC5YXSTLQV5PNWL7ULYRIPC ，安装完BT Sync，输入密钥后，一直显示无用户，无法同步！希望能够使用该软件同步！

**Comment by bannedbook** [comment]
看下这里 https://program-think.blogspot.com/2017/08/GFW-Resilio-Sync.html

**Comment by dajiba1024** [comment]
推荐一个自用的shadowsocks SS/SSR服务商，一直在用，速度杠杠的~|价|格|优|惠|低至5元/50G/月。在最近跑路关停潮日益严重的日子,依旧坚挺~已屏蔽国内ip，需翻墙访问～
http://cp.dawangidc.com/aff.php?aff=523
购买服务后请看配置教程
https://fqjsjl.tumblr.com/
