### ISSUE TITLE
你的软件对网络营运商是否有要求？

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#221]
请问你的软件会不会有网络营运商使用不了？我的意思是电信网络可以用，但联通网络就不能使用！有没有要求？

**Comment by bannedbook** [comment]
不同的运营商不同地区都可能有不同的情况，只能自己试试看啦。

下载 最新 chromego，里面已包含了 Quic版。

chromego这个文件夹里面有：
Firefly翻墙.cmd
GoAgent0翻墙.cmd
GoAgent1翻墙.cmd
GoAgent2翻墙.cmd
GoAgent3翻墙.cmd
GoAgent4翻墙.cmd
ipv6-Agent0翻墙.cmd
ipv6-Agent1翻墙.cmd

GoGo翻墙.cmd
PAC翻墙.cmd
v2ray翻墙.cmd
蓝灯翻墙.cmd
这么多种翻墙方法，其中前面7个第一次启动时以右键，管理员身份启动。
2个ipv6的，先看对应的ipv6-Agent0翻墙.使用说明（必看）.rtf、ipv6-Agent1翻墙.使用说明（必看）.rtf 设置好ipv6环境再启动。

下载解压后进入Agent0\ip_Update文件夹运行一键更新ip文件来同步Agent0到最新的云端配置，其它Agent2、Agent3、GoProxy Quic版、ipv6-Agent0、ipv6-Agent1也需类似操作，建议不好用时即可尝试更新IP试试。Agent1和Agent4自动扫描IP无须手工更新。

每一个都试一试，肯定有能用的。

**Comment by iluvni** [comment]
还有这五种 
GoAgent0翻墙.cmd
GoAgent1翻墙.cmd
GoAgent2翻墙.cmd
GoAgent3翻墙.cmd
GoAgent4翻墙.cmd只有GoAgent0翻墙.cmd能打开，别的都不行现在没有办法升级谷歌浏览器。请问怎么办？

**Comment by bannedbook** [comment]
看压缩包里带的：Chrome内核升级方法.rtf

**Comment by iluvni** [comment]
1、	右键单击 GoAgent翻墙.cmd 或GoAgent2翻墙.cmd，以管理员身份启动；
2、	启动后关闭Chrome浏览器；
3、	右键点GoAgent图标，设置IE代理，127.0.0.1:8087
打不开 设置了IE代理后IE···浏览器也不能出去。

**Comment by bannedbook** [comment]
1、	右键单击 GoAgent翻墙.cmd 或GoAgent2翻墙.cmd，以管理员身份启动；
这一步完成后成功翻墙了没？chrome能翻墙吗

**Comment by iluvni** [comment]
GoAgent翻墙.cmd 或GoAgent2翻墙.cmd  现在是 GoAgent1翻墙.cmd 或GoAgent4翻墙.cmd 以管理员身份运行后没有成功翻墙，谷歌浏览器也不可以。

**Comment by bannedbook** [comment]
首先要确保翻墙成功，然后再设置ie代理，然后才能升级

**Comment by iluvni** [comment]
知道 现在问题就是不能翻出去

**Comment by bannedbook** [comment]
你不是说  GoAgent0翻墙.cmd能打开 能打开吗

**Comment by iluvni** [comment]
GoAgent0翻墙.cmd能打开  但是GoAgent1翻墙.cmd和GoAgent4翻墙.cmd打不开 因此浏览器内核也无法升级

**Comment by bannedbook** [comment]
GoAgent0翻墙.cmd能打开后，在其打开的chrome浏览器里翻墙浏览正常吗？
如果GoAgent0能翻墙，这时按照 Chrome内核升级方法.rtf 升级即可

**Comment by iluvni** [comment]
GoAgent0翻墙.cmd打开了，打开的浏览器也能成功，但是不能升级提示获取chrome更新信息失败， 服务器无响应。截图
![qq 20180101153840](https://user-images.githubusercontent.com/24630043/34466333-349b762c-ef0a-11e7-926f-3c6fc0fed2db.jpg)

**Comment by bannedbook** [comment]
IE代理设置是否成功，检查ie代理，并用IE试试看能否翻墙

**Comment by iluvni** [comment]
GoAgent1翻墙.cmd和GoAgent4翻墙.cmd翻不了，设置IE代理后无论是软件自带的浏览器还是ie都翻不了墙

**Comment by bannedbook** [comment]
也可以直接下载这个更新过的，已包括最新版chrome
https://github.com/killgfw/fg/raw/master/fqb/ChromeGo.7z

**Comment by iluvni** [comment]
好的
