### ISSUE TITLE
安卓客户端如何自定义名单？

### ISSUE THREAD

**Issue by 123ysys** [bannedbook/fanqiang#226]
你好，请问安卓客户端如何自定义列表名单？不是“仅代理国外流量”，谢谢。

**Comment by bannedbook** [comment]
请问是哪个 安卓客户端

**Comment by 123ysys** [comment]
是萤火虫，谢谢。

**Comment by bannedbook** [comment]
到这里 https://github.com/yinghuocho/firefly-proxy/issues 问下

**Comment by 123ysys** [comment]
这个似乎没人维护了55555 @bannedbook
