### ISSUE TITLE
此软件有病毒，会更改系统配置，时间长会造成不可修复，只能重装系统，已经经历并测过了

### ISSUE THREAD

**Issue by Jasmine66Bloom** [bannedbook/fanqiang#227]
请发资源的时候注意是否有病毒，不要做没头脑的搬运工！如若是故意隐藏病毒，请提高自身修养，如若不慎，请发资源细致检查！！！

**Comment by bannedbook** [comment]
你说的是哪个软件

**Comment by Jasmine66Bloom** [comment]
@bannedbook readme里的翻墙工具大全链接，页面里的’Chrome一键翻墙包‘是有问题的

**Comment by bannedbook** [comment]
Chrome一键翻墙包里面很多种翻墙软件，据我所知，里面的 Agent4 ，其实是XX-Mini，里面的goagent.exe 有的杀毒软件报警，这个软件来源在这里 https://github.com/xyuanmu/XX-Mini
我们使用后，没有发现修改系统的行为，应该是误报

还有一个是萤火虫代理，也是有杀软报警，来源是这里 https://github.com/yinghuocho/firefly-proxy 貌似是开源软件，简单试用后没有修改系统的病毒行为。据统计，使用这个软件的人还不少。

如果不放心，不用这2个软件就行了。
