### ISSUE TITLE
你好！

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#228]
你好，你的软件可能真的包含病毒（Chrome一键翻墙包完整版）。前两天我的电脑出现了开机反复重启，进不了系统进去了就蓝屏。一开始我也怀疑是病毒但没有想到可能是你的软件，昨天我上贵站发现楼上的一篇帖子说你的软件有病毒。于是我就把你的软件都删了。然后开机就正常了虽然只是今天正常！如果你的软件真的包含了病毒请你好好检测去除病毒。你的软件很好，不但让大家明真相而且可以让我们看到国外的一些先进尖端的事物···谢谢！

**Comment by bannedbook** [comment]
你翻墙时用 Chrome一键翻墙包完整版 里面的哪个翻墙方法？

**Comment by iluvni** [comment]
GoAgent0翻墙.cmd
GoAgent1翻墙.cmd
GoAgent2翻墙.cmd
GoAgent3翻墙.cmd
GoAgent4翻墙.cmd.这五种都右键以管理员身份运行了。但只有GoAgent0翻墙可以使用，所以是使用的GoAgent0翻墙方法。

**Comment by iluvni** [comment]
还有一个问题，我的电脑开机不成功还原系统后 这些：Firefly翻墙.cmd
GoAgent0翻墙.cmd
GoAgent1翻墙.cmd
GoAgent2翻墙.cmd
GoAgent3翻墙.cmd
GoAgent4翻墙.cmd
ipv6-Agent0翻墙.cmd
ipv6-Agent1翻墙.cmd

GoGo翻墙.cmd
PAC翻墙.cmd
v2ray翻墙.cmd
蓝灯翻墙.cmd翻墙的cmd就全部消失了，并且在之前杀毒软件的防御功能都打不开。还原后开机就正常了

**Comment by bannedbook** [comment]
还原系统是使用 windows的系统还原功能吗？
还原系统后，你是说chromego这个文件夹还在，里面的其它文件也在，就只有这几个 .cmd 文件消失了？

**Comment by iluvni** [comment]
是windows系统还原，还原后chromego这个文件夹在，里面的其它文件都在。就这几个.cmd消失了。

**Comment by bannedbook** [comment]
这种事，实在太奇怪，这几个cmd文件也没什么呀，你可以用你的杀毒软件扫描扫描看看

**Comment by iluvni** [comment]
扫描下来也显示正常无毒

**Comment by bannedbook** [comment]
我假定你的述说为真，但我无法解释。
Chrome一键翻墙包里面很多种翻墙软件，据我所知，里面的 Agent4 ，其实是XX-Mini，里面的goagent.exe 有的杀毒软件报警，这个软件来源在这里 https://github.com/xyuanmu/XX-Mini
我们使用后，没有发现修改系统的行为，应该是误报

还有一个是萤火虫代理，也是有杀软报警，来源是这里 https://github.com/yinghuocho/firefly-proxy 貌似是开源软件，简单试用后没有修改系统的病毒行为。据统计，使用这个软件的人还不少。

如果不放心，不用这2个软件就行了。

**Comment by iluvni** [comment]
Agent4和萤火虫代理都出不去，现在我这里只有GoAgent0可以翻出去

**Comment by iluvni** [comment]
那我再今天试试看会不会再出现 如果没有出现的话 那我的电脑可能是硬件方面的问题。到时候我会来这里澄清的
