### ISSUE TITLE
澄清

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#229]
此软件都是无毒的。今天上午我回完上一条贴后就立即下载了软件解压然后杀毒还没等杀毒结束（根本就没有操作打开）我的电脑又出现了自动重启现象并且这次根本就重启不来了。一点亮就熄火。然后我就拿去修理原来是我的电脑长时间没有清理，里面积攒了太多灰尘引起的电脑重启。因此特来澄清软件无毒。望大家不要误解！

**Comment by bannedbook** [comment]
谢谢您的澄清反馈！

**Comment by iluvni** [comment]
不客气 希望你一如既往的为我们提供高质量的软件。
