### ISSUE TITLE
反向代理

### ISSUE THREAD

**Issue by Alvin9999** [bannedbook/fanqiang#230]
这里有个反向代理的项目，供你参考：https://github.com/gfw-breaker/ssr-accounts

你可以用这种代理方式做禁闻网等其它真相网站的代理。

**Comment by bannedbook** [comment]
这种反向代理好像不行吧，好像没有加密，完全是明文，也不是https

**Comment by Alvin9999** [comment]
你指的是安全性不好，还是容易被封锁呢？

**Comment by bannedbook** [comment]
这种应该根本就翻不了吧，因为有敏感词 会触墙 ，根本翻不了

**Comment by gfw-breaker** [comment]
可以翻的，而且速度比较快。现在GFW只是检测URL里有没有敏感词，而没检测BODY，但不排除以后GFW会升级。 可以配置SSL， 但用户看到不受信任证书的警告后可能就不继续访问了。

**Comment by bannedbook** [comment]
不太清楚了，据说：GFW除了会分析上行的HTTP GET请求，对于HTTP返回的内容也会做全文关键字检查。这种检查与对请求的关键字检查不是由同一设备完成的，而且对GFW的资源消耗也更大。相关的研究论文有：http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.191.206&rep=rep1&type=pdf

**Comment by gfw-breaker** [comment]
应该属于这种情况，服务器地址不在审查范围内，所以没有对response body做检查。

![default](https://user-images.githubusercontent.com/34854165/34924796-932f1848-f9e0-11e7-9b68-bec9ec7aafc8.png)

**Comment by bannedbook** [comment]
哦，原来这样。那这个也挺好啊。
如果方便，可帮忙把 这个 usadns.info 反代一下。

**Comment by gfw-breaker** [comment]
写好了，在CentOS6上运行的。页面和下载都没有问题，但部分广告没法显示，有些外链没替换。
默认会为sites目录下所有网站配置代理， 你可以删除不需要的，也可以自行修改端口号
[https://github.com/gfw-breaker/open-proxy](https://github.com/gfw-breaker/open-proxy)

**Comment by bannedbook** [comment]
好的，谢谢！
