### ISSUE TITLE
并没有网站弹出来

### ISSUE THREAD

**Issue by Yingyyyy** [bannedbook/fanqiang#231]
学习大佬的chrome翻墙教程，回车后就停留在了rolling back the update, 然后问我要不要download，怎么回事呢？？

**Comment by bannedbook** [comment]
您好，是用哪个翻墙方法？

**Comment by Yingyyyy** [comment]
就是appid和chrome那个

**Comment by bannedbook** [comment]
是翻墙时的问题，还是 自建翻墙服务器的问题？

**Comment by Yingyyyy** [comment]
自建的时候，根据教程，当我开始输入appid之后，会有一个网站弹出来，我选允许，但是并没有这个网站弹出来。之前准备考试没来得及回复，不好意思
