### ISSUE TITLE
今天翻不了了？

### ISSUE THREAD

**Issue by staryyeah** [bannedbook/fanqiang#232]
之前angent3 OK的，今天翻不了了？

**Comment by staryyeah** [comment]
1，更新不成功，提示找不到 gui-config.json ;
2，提示参数太多，要求不多于2个参数，但收到了6个；
3，蓝灯 在电信网络有效，在移动网络无效

**Comment by bannedbook** [comment]
截屏看看 更新不成功的完整提示是什么

**Comment by staryyeah** [comment]
[全页照片.pdf](https://github.com/bannedbook/fanqiang/files/1645359/default.pdf)

**Comment by bannedbook** [comment]
chromego ，不要放在含有空格或中文的路径中，然后再试试

**Comment by iluvni** [comment]
几天之前我这里也出现了angent3 翻不了的问题 但更新ip之后就可以了

**Comment by staryyeah** [comment]
解决了

**Comment by yiasoall** [comment]
<html>
<body>

推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>
