### ISSUE TITLE
Mac 电脑使用哪个来翻墙

### ISSUE THREAD

**Issue by chao901103** [bannedbook/fanqiang#233]
之前使用蓝灯还有mac版 ，现在蓝灯都找不到，都更换成其他的win 翻墙软件了，没有找到mac版的翻墙，请问mac使用哪个？

**Comment by bannedbook** [comment]
https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E7%94%B5%E8%84%91MAC%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6

**Comment by chao901103** [comment]
多谢！ 正在使用中.....
