### ISSUE TITLE
小白求指点

### ISSUE THREAD

**Issue by emberrsspirit** [bannedbook/fanqiang#234]
之前很早用的goagent设置代理用火狐上网 好久不用了 之后用lantern流量太少
现在又想用火狐 发现 您发的和我之前用的完全不一样 
之前进去一个local文件夹 一个server
您这一版本好像不太一样..我也没找到教程 大概代理什么的之前都设置过 我用的那个版本也进不去 看样子是ip不对 我用gogotest也一直扫不出...用您的ip update也不会用 很尴尬
可否给我 1 您发的这一版本的使用教程 
或者        2 我这一版本应该如何找可用ip复制到 proxy。ini里面呢

**Comment by bannedbook** [comment]
这里的 
firefox一键翻墙包 这个文件夹大概可能有：

Agent0翻墙
。。。
Firefly翻墙.cmd
等翻墙方法，直接点击启动就可翻墙

文件夹里面有 .rtf的说明文档

**Comment by haochiburujiaozi** [comment]
@emberrsspirit 
https://github.com/getlantern/forum/issues/8006

**Comment by emberrsspirit** [comment]
@bannedbook
请问 扫描完ip之后 显示错误10061 计算机积极拒绝无法连接 要怎么解决....

**Comment by bannedbook** [comment]
换一个翻墙方法，按顺序依次尝试：



Agent0翻墙.cmd（GoProxy Quic版,GoProxy Quic版适合封锁比较严重的地区，目前还不完善，不适合用于下载超过32M的文件。在使用过程中，如果遇到网页卡死,页面显示不完整、图片不显示、Google 400. That’s an error.或者其它问题，可以通过刷新网页或者重启软件来尝试着解决。）

蓝灯翻墙.cmd

Firefly翻墙.cmd

ipv6-Agent1（GoProxy ipv6版，必须先看相应的使用说明设置好ipv6环境）

ipv6-Agent0（GoAgent ipv6版，必须先看相应的使用说明设置好ipv6环境）

Agent3（SSR版）

Agent1:		GoAgent版自动扫描IP版
Agent2：	GoProxy版
Agent4：	GoAgent Mini版
......

根据实际测试，建议按照上面的列表从上往下的顺序依次尝试。由于国内网络环境不同、地区不同，封锁强度会不同，所以使用效果会有差别，有的地区几乎所有的软件都能使用，有的只能用几款，因此具体哪款软件适合你的网络环境，需要你自己来尝试。

如果Agent0、Agent2、Agent3、ipv6-Agent0、ipv6-Agent1 不好用，可进入相应目录的ip_Update文件夹运行 ip更新 试试看。Agent1和Agent4自动扫描IP无须手工更新。

**Comment by emberrsspirit** [comment]
@bannedbook 给力！ 比我之前用的简单多了 多谢多谢！

**Comment by yiasoall** [comment]
<html>
<body>

推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>
