### ISSUE TITLE
请问这个是什么，怎么使用？

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#235]
这个软件BT Sync（Resilio Sync）下载，非常好用方便，永久自动同步，我们发布新版翻墙软件后，您会自动获得同步更新。BT Sync同步密钥: BG2G54AGRNPC5YXSTLQV5PNWL7ULYRIPC ，BT Sync（RESILIO SYNC）-下载神器，P2P同步利器和分布式网盘。是什么软件，怎么使用？

**Comment by bannedbook** [comment]
看这里
https://github.com/bannedbook/fanqiang/blob/master/RESILIO-SYNC/readme.md

**Comment by iluvni** [comment]
我按要求操作到勾选

使用代理服务器这里不会了，接下来该如何进行？

**Comment by iluvni** [comment]
![qq 20180124161030](https://user-images.githubusercontent.com/24630043/35321214-8b8063de-0121-11e8-8c79-3f5173281907.jpg)

**Comment by bannedbook** [comment]
选择 https 代理，不要sock4，然后右边两个框分别填入 代理的服务器的 ip 和端口

**Comment by iluvni** [comment]
代理的服务器的 ip 和端口填什么？

**Comment by bannedbook** [comment]
可以填翻墙软件的 代理，比如如果用 我们的chrome一键翻墙包，如果是 
 Agent0、Agent1、Agent2、Agent4，代理地址
ip和端口分别都是
127.0.0.1
和
8087

**Comment by iluvni** [comment]
填好之后下一步怎样进行操作？

**Comment by bannedbook** [comment]
填好以后，点x关掉窗口，然后 再 推出 RESILIO SYNC 后重启 RESILIO SYNC

**Comment by iluvni** [comment]
好的谢谢

**Comment by iluvni** [comment]
暂时还是不弄了···不会。⊙﹏⊙‖∣

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/blob/master/RESILIO-SYNC/btfq.md

**Comment by iluvni** [comment]
好的我去看看

**Comment by winermio** [comment]
<html>
<body>

助你跨过GFW，来到自由世界！推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>
