### ISSUE TITLE
此方法安全问题 是否安全

### ISSUE THREAD

**Issue by emberrsspirit** [bannedbook/fanqiang#236]
据说 2018年初 全国 禁止 个人VPN接入 广东深圳已经启用大范围ss协议识别技术 用于识别监视个人vpn 有些人已经去喝茶了 请问 这种方法安全吗

**Comment by bannedbook** [comment]
一般网民，翻墙看看新闻，不用考虑安全不安全，法不责众么管不过来，获取自由的信息是天赋人权。

**Comment by yiasoall** [comment]
<html>
<body>

推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>
