### ISSUE TITLE
请问如何更换起始页

### ISSUE THREAD

**Issue by JingwangLi** [bannedbook/fanqiang#237]
在使用ipv6-Agent0的时候，每次打开的时候主页都是https://www.bannedbook.org/bnews/fq/?utm_source=ipv6-Agent0，看起来挺不舒服的，无论怎么修改起始页也不行，想请教您要怎么样才能修改首页呢？
谢谢！

**Comment by bannedbook** [comment]
每次都打开这个起始页，就当作是对这个免费软件的支持吧
