### ISSUE TITLE
郭媒体访问不了 https://www.guo.media﻿

### ISSUE THREAD

**Issue by dwales1975** [bannedbook/fanqiang#238]
试了所有翻墙文件包里没一个都不可以访问郭媒体的
https://www.guo.media﻿

**Comment by dwales1975** [comment]
自由中国之声也是访问不了。看来海外自由媒体是更独立自由了，可是我们国内就连翻墙都看不了。

**Comment by bannedbook** [comment]
刚更新了一下这个， 下载 试试看 
https://github.com/killgfw/fg/blob/master/fqb/ChromeGo-lite.7z

**Comment by winermio** [comment]
<html>
<body>

助你跨过GFW，来到自由世界！推荐个快速稳定的SSR，低至5元/50G/月，已屏蔽国内ip，需翻墙访问～
<a href="http://cp.dawangidc.com/aff.php?aff=523">购买链接</a>
<a href="https://fqjsjl.tumblr.com/">教程链接</a>

</body>
</html>
