### ISSUE TITLE
读者投书：自由浏览应用已被中共控制！！！请楼主不要推广了！！

### ISSUE THREAD

**Issue by weinierlaia** [bannedbook/fanqiang#239]
http://www.ntdtv.com/xtr/gb/2018/01/22/a1360380.html
自由浏览（英语：FreeBrowser）是一款由GreatFire开发的安卓破网软件，于2015年2月发布。在中共进一步审查与封锁网络的情况下，有大陆用户披露，自由浏览应用已被中共控制。

1月22日，有大陆读者向新唐人投书说，自由浏览应用已被中共控制......

该读者并发布了两点声明：

一：我不清楚中共政府是什么时候控制了，自由浏览这个github项目，它除了有app.还有一些源码。大概是旧年开始发现我安装这个app后，它的界面就不停地截图，每秒截图好几次，很快，你触屏越快它就截图越快。不停出现红色边框。但是在手机里是找不到这些截图的。

今天我谷歌搜索了原因才发现，这项目被中共控制，太危险了。

搜索的证据网址 https://github.com/programthink/zhao/issues/131 您可以亲自用没有任何私人资料的安卓手机安装自由浏览试试，打开后，它截图的红框闪得比你触摸屏幕还快！

这消息我将告诉几家新闻媒体，希望都能公布出来，这事情实在太严重。

二：最近国内的安卓和苹果app开发很厉害，很多在应用商店排名都很高。为了让各国不要忘记共产政权的血腥残暴，应该提防中国的app。因为中国网络公司通常会有中国政府的服务器备份审查。

尽管有部分app将中国用户和国外用户隔绝联系，但是如果中共政府威胁的时候，这些中国网络公司出于利益，很可能会提供所有的用户隐私数据。

打个比方，在中国大陆很热门的手机app叫〝火山视频〞(app〝新闻头条〞的公司有份参与投资)，中国注册的用户是不能搜索也不能看到到国外注册的用户及其分享的视频资讯。

因为还有一个英文版的app叫"hypstar"。中国网民多，如果中国网络公司决绝接受中共政府提出的备份审查要求，(例如：交出全球注册用户的隐私数据)，会损失很多钱。所以中国网络公司很少会这么做，除非公司不在共产主义国家。

可怕的是，如果这么多中国网络公司，都提供全球注册用户的隐私数据给中共政府，中共共产主义政权的暴政，会将邪恶的魔爪延伸的全球各个国家，如果全球用户隐私数据都在共产党的控制之下，后果不堪设想。

很多中国网络公司开发的app都有英文版，很多中国网络公司的中文版app和英文版app都会显示不同的内容资讯。(意思就是中文版注册用户不允许看见英文版的内容)，而且因为谷歌应用商店遭到中共封锁，一般中国网民都不知道。

类似的中国热门手机app还有：〝小影〞，〝快手〞，〝抖音〞等等。

网络审查App只是中共政府邪恶的一小部分，还有许多的行业值得我们提防。当然也有很多好的中国人，我希望大家不要总是用歧视的眼光来看待所有中国人。因为还有很多中国人生活在政权的谎言之下，得不到真相。

**Comment by bannedbook** [comment]
这个问题，我们是这样看的。本项目的目的，是帮忙大陆网民翻墙获取信息，翻墙看海外的禁网新闻，只要翻墙效果好就行。一般网民对安全性没有什么需求，大陆的微信、QQ、杀毒软件等等全是木马，全在监控网民，但是大多数人还是照样用。

一般人只是翻墙看看新闻，也不怕什么监控不监控，监控了也不怕。

如果对安全性要求比较高的人，自然会选择更高安全性的软件。

**Comment by weinierlaia** [comment]
倒也是

在 2018年1月31日 下午8:26，如何翻墙 <notifications@github.com>写道：
