### ISSUE TITLE
里面的蓝灯有毒，会盗密码。已经删了

### ISSUE THREAD

**Issue by ufozy** [bannedbook/fanqiang#24]
里面的蓝灯有毒，会盗密码。已经删了。我的谷歌密码和邮箱密码都被盗了。还好谷歌异常登录有短信通知。马上改回来了。

**Comment by bannedbook** [comment]
蓝灯软件有官方数字签名的，可以确保是官方原版。下载后可以检查。
请问您是从哪里下载的？

**Comment by ufozy** [comment]
我是从https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85
页面中的 [[“下载链接1：ChromeGo.7z，（如果提示百度云升级，链接不存在等，刷新一下就出来了）”这个链接下载的。确定是因为这个原因被盗密码。用了一下登录账号后就关了。过了十几分钟谷歌就提示我账号有异常登录，显示在日本。我的126邮箱密码也被改了。

**Comment by bannedbook** [comment]
您看下 在 Lantern文件夹里的lantern.exe 文件，右键点，然后点 属性，查看 数字签名 看看是不是 Brave New Software Project, Inc

还有，有没有核对下载的软件包 ChromeGo.7z 的文件大小 和md5校验值是否一致

**Comment by sidney9111** [comment]
wow，表示关注
