### ISSUE TITLE
求指导！

### ISSUE THREAD

**Issue by MaLaiYooo** [bannedbook/fanqiang#241]
按照您的文档自己搭建起了GoAgent翻墙服务器，使用的google appid但是搭建完成后只有域名为google.com下的网站可以打开，youtube，Facebook都打不开，报错
404 Not Found

The resource could not be found.
还会出现
400. That’s an error.

Your client has issued a malformed or illegal request. That’s all we know.
也会出现这样子的代码
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "read udp 0.0.0.0:60178->181.49.184.201:443: HeadersStreamDataDecompressFailure: cannot read frame"
}
请问这是我搭建的服务器哪里出现了问题吗？

**Comment by MaLaiYooo** [comment]
Hello, World!

**Comment by MaLaiYooo** [comment]
Hello, World!

**Comment by bannedbook** [comment]
如果上传成功的话，应该是显示类似这样的信息：
{
	"server": "goproxy 1.0"
	"deploy": "2016-09-05T07:35:25Z",
	"latest": ""
}

**Comment by MaLaiYooo** [comment]
我是根据现在app引擎指导下搭建的，这个教程可以跳过吗？我觉得是出在教程上，这个hello world就是根据教程搭建下来的。

**Comment by Csejte** [comment]
@MaLaiYooo 您好，我也遇到了和您一样的问题，使用的google appid搭建完成后只有google.com可以打开，Twitter，youtube，等都打不开，同样报错
404 Not Found
The resource could not be found.
http://yourappid.appspot.com/ 访问这个同样显示为Hello, World!
请问您是怎么解决的？

**Comment by bannedbook** [comment]
最新版 ChromeGo 里面 \ipv6-Agent1\code\default\gae_proxy\server 目录下
用 uploader.bat 来上传
具体看目录下的
README.md
