### ISSUE TITLE
翻墙工具 中极端恶意诋毁中国共产党 真的好吗？

### ISSUE THREAD

**Issue by qinyou** [bannedbook/fanqiang#242]
宣扬法轮功，诋毁共产党，是生活太美好，想找点刺激是吗？
中国发展需要安定，安定就要阻止恶意传谣，阻止恶意传谣才有了中国防火墙。
如果人人都能理性看待问题，国际关系就不需要这么复杂了。

**Comment by DAMINGLUO** [comment]
我刚刚也发现了，我也希望把某些软件删掉就是那个禁文的网站和app

**Comment by DAMINGLUO** [comment]
真的有点气
