### ISSUE TITLE
哪位有企业翻墙的解决方案？

### ISSUE THREAD

**Issue by baiwei0703** [bannedbook/fanqiang#243]
需求：
1.可以控制解析的域名
2.客户端（员工PC机）尽量少操作，将配置尽可能的放在服务端
先谢过了。。。

**Comment by Alvin9999** [comment]
我在这个论坛刚发布了一篇自建ss/ssr服务器教程的帖子，你可以参考下。

服务器ip确定后可以自己绑定想要的域名。账号搭建好后，只要服务器ip没被封，理论上可以一直用下去，如果ip被封，删除服务器，新建一个服务器就是新的ip。员工只要用客户端填上你配置好的账号就能翻墙，无需额外操作，当然只能浏览器翻墙，不是vpn全局代理。另外，也可以把账号放进路由器里，但是配置要麻烦一些，我没有试过，在教程的末尾有提到，需要你自行研究。

还有一种途径就是网上找为企业提供翻墙服务的，花钱买这种服务。我个人建议自己搞，这样好把握些。

**Comment by sidney9111** [comment]
在中国，还有给钱解决不了的事情？我没有服务，要不一定卖给你
