### ISSUE TITLE
能否将软件都加上版本号？

### ISSUE THREAD

**Issue by pinkchina** [bannedbook/fanqiang#248]
软件下载里面，所有的软件都没有版本号，不知道是新版的还是老版的，希望版主能将软件都加上版本号，这样下载时就能知道是否为最新的！

**Comment by bannedbook** [comment]
网页上方有个 更新日志

**Comment by pinkchina** [comment]
那是否就意味着所有ipfs上的软件都是最新版呢？

**Comment by clobob** [comment]
好像只保留了最新版，旧版的本身就是用不了才更新的，如果页面下载的就不能用，可能是又需要更新了。

**Comment by bannedbook** [comment]
ipfs上的软件都是最新的
