### ISSUE TITLE
Agent0突然error

### ISSUE THREAD

**Issue by lianghao12138** [bannedbook/fanqiang#249]
![360 20180308183252024](https://user-images.githubusercontent.com/32200004/37146587-250e0cdc-22ff-11e8-9279-344cc1cf9f5d.jpg)
之前用的好好的，不知道为什么今天出现这个error

**Comment by carmeny123** [comment]
同问. 其他的Agent也突然用不了

**Comment by bannedbook** [comment]
开会，封锁加剧，多刷新几次还能出来

**Comment by bannedbook** [comment]
可以试试看 ipv6 的版本

**Comment by bannedbook** [comment]
進入Agent0\ip_Update目录，执行一下 ip_2.bat 更新ip，会好一些

**Comment by myh215** [comment]
同问

**Comment by clobob** [comment]
刷新就好

**Comment by lianghao12138** [comment]
试了ipv6的版本，可以

**Comment by iluvni** [comment]
请问设置ipv6的版本会不会改变原本电脑的ip地址？

**Comment by bannedbook** [comment]
启用ipv6后，会多一个ipv6的地址，好像是这样

**Comment by iluvni** [comment]
那到底会不会改变电脑的ip。我的Q设定了登录地点 但是原本绑定的安全中心已经删除很久了

**Comment by bannedbook** [comment]
可以自己测试 https://www.whatismyip.com/

**Comment by lianghao12138** [comment]
ipv6已废
