### ISSUE TITLE
更新不了IP，提示找不到gae.user.json_backup

### ISSUE THREAD

**Issue by terryandjing** [bannedbook/fanqiang#250]
用的一键翻墙，更新IP时提示，系统找不到指定文件gae.user.json_backup

**Comment by bannedbook** [comment]
用 ip_2.bat

**Comment by terryandjing** [comment]
之前能用的几个，这几天都连不好了，有些像同时挂，是开会的原因?

**Comment by bannedbook** [comment]
ipv6 应该还可用

**Comment by terryandjing** [comment]
打开youtube提示
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "read udp: closing session in order to recreate it with a new version"
}

**Comment by bannedbook** [comment]
这个是 ipv6 版吗

**Comment by terryandjing** [comment]
是GoProxy的，ipv6我这个移动宽带连不了

**Comment by bannedbook** [comment]
更新ip的话，请用ip-2文件来更新，运行ip-2文件2～3次！直到不出现“找不到文件”字样为止，才算更新成功。如果更新ip后还是无法使用的话，说明此版目前不适合你那里的网络环境。
