### ISSUE TITLE
高内核GoProxy ipv6版（32位）， 我电脑是64位 好像不行？

### ISSUE THREAD

**Issue by deadcn** [bannedbook/fanqiang#252]
2001:4860:4860::8888 , 2001:4860:4860::8844 
 我设置时候 输入这个IP 提示说不是有效IP地址。 难道64位的电脑不行？
昨天下午开始所有文件包都没有一个行了。

**Comment by bannedbook** [comment]
这个好像应该跟64位没关系吧，你确认是ipv6属性里面设置啊

**Comment by deadcn** [comment]
ChromeGo  这个文件中的 ipv6 

脑系统开启ipv6的步骤如下：
1、打开控制面板---网络和共享中心--点本地连接---点属性---点tcp/IPv6----点属性---点使用下面的DNS服务器---在上面一行复制黏贴 2001:4860:4860::8888 下面一行复制黏贴 2001:4860:4860::8844 ----确定。如图：

**Comment by deadcn** [comment]
ChromeGo-lite  难道要用这个？

**Comment by bannedbook** [comment]
注意下，不要多加空格什么的

**Comment by deadcn** [comment]
ChromeGo-lite  用这个来设置可以，就是速度很慢。凑合看看。这2天严重封锁，哎。
