### ISSUE TITLE
翻墙极端困难了！ip_Update大多数都无法收到更新了。。。。

### ISSUE THREAD

**Issue by fuckgfwnow0123** [bannedbook/fanqiang#253]
Agent0、Agent3这两个常用的，我尝试了不少于10次，更新ip_Update，IP_1和IP_2都不能更新了。
直接反馈：系统找不到指定文件gae.user.json
IP_2是要么和上面的反馈一样找不到文件，要么就是表现为：更新的时候进度条刚刚要开始走就被中断了。然后我试了很多次，都翻不了墙。

Agent1 的ip_Update更新是完成的，但扫描完IP，也一样不能翻。
凡是不能翻的，网页直接空白然后显示以下内容：

    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "read udp: closing session in order to recreate it with a new version"
}

-----
ShadowsocksR的话，IP_2能更新，但是只能用一两次，然后就被中断了，中断以后无论怎么反复尝试都连不上了。要过至少一整天以上，再去尝试，又能翻了，但是最多半小时，接着继续被中断，然后再要等很久。

**Comment by fuckgfwnow0123** [comment]
GOOD IP基本上都是0，BAD IP无数。。。唉。。。。

**Comment by bannedbook** [comment]
用 ipv6 ，ipv6 可用

**Comment by iluvni** [comment]
蓝灯可以试试看

**Comment by deadcn** [comment]
ipv6 也不行了。蓝灯可以用一下，之后就收费。看来现在彻底沦陷了。

**Comment by jiangossac** [comment]
ipv6偶尔可以，很经常就断掉，再连就都不行。问下老大，是不是最近会议的原因，导致我们浏览器无法继续翻墙。

**Comment by deadcn** [comment]
Message From LocalProxy
--
 Local URLFetch 'https://www.bannedbook.org/bnews/fq/?utm_source=ipv6-Agent0' failed
timed out
timed out
我昨天用了几下ipv6，现在 都是这个结果。是的，希望能想想办法。

**Comment by deadcn** [comment]
尝试了一个是上午，最后电脑死机，太可恶了。

**Comment by bannedbook** [comment]
更新ip的话，请用ip-2文件来更新，运行ip-2文件2～3次！直到不出现“找不到文件”字样为止，才算更新成功。如果更新ip后还是无法使用的话，说明此版目前不适合你那里的网络环境。
