### ISSUE TITLE
goagent自建翻墙服务器-rolling back the update

### ISSUE THREAD

**Issue by ronrone** [bannedbook/fanqiang#256]
大神们，自建翻墙服务器过程中，输入appid后没有弹出网站，却提示rolling back the update。请问是哪里出错了？

**Comment by ronrone** [comment]
期间有提示端口不是8087或1008什么的，修改代理IP端口后，还是提示rolling back the update.

**Comment by bannedbook** [comment]
删除掉server目录下的.appcfg_cookies

**Comment by ronrone** [comment]
没有找到server，文件夹搜索了appcfg_cookies，显示没有。

**Comment by bannedbook** [comment]
最新版 ChromeGo 里面 \ipv6-Agent1\code\default\gae_proxy\server 目录下
用 uploader.bat 来上传
具体看目录下的
README.md
