### ISSUE TITLE
请问psiphon翻墙怎么使用？

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#257]
如题，谢谢！

**Comment by bannedbook** [comment]
下载解压chromego后，执行 4.psiphon翻墙.cmd 即可

**Comment by iluvni** [comment]
不分左右键吗？还有反馈现在6.agent0我这边又可以用了！

**Comment by bannedbook** [comment]
psiphon翻墙.cmd直接双击启动就可以。

**Comment by bannedbook** [comment]
翻墙脚本的.cmd文件的文件名前面也加了1、2、3...的序号，建议按这个序号顺序挨个尝试。
由于国内网络环境不同、地区不同，封锁强度会不同，所以使用效果会有差别，有的地区几乎所有的软件都能使用，有的只能用几款，因此具体哪款软件适合你的网络环境，需要你自己来尝试。
