### ISSUE TITLE
问题又来了

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#259]
我刚刚试着打开gogo和蓝灯发现都出不去，接着我又使用ipv6上网发现两个ipv6也都上不了。已经打开了ipv6.bat。现在我还是使用的6.agent0

**Comment by iluvni** [comment]
还有赛风也不行 一直显示连接中

**Comment by bannedbook** [comment]
验证ipv6是否开启
打开 http://test-ipv6.com/ 网站，它会自动检测网络是否开启ipv6

这个验证了没

**Comment by iluvni** [comment]
现在又可以上了，没哄你之前真的不能上。
