### ISSUE TITLE
请问您的代理我们怎么拿出来用

### ISSUE THREAD

**Issue by zjcnew** [bannedbook/fanqiang#263]
我现在需要在Linux服务器上使用http代理访问Google drive备份数据，请问怎么使用你里面的代理作为我的http代理成功连接goolgle服务器？

**Comment by bannedbook** [comment]
https://github.com/Alvin9999/new-pac/wiki/Linux%E7%B3%BB%E7%BB%9F%E7%BF%BB%E5%A2%99%E6%96%B9%E6%B3%95
