### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#266]
你好！我想问一下怎样可以绕过手机验证注册谷歌邮箱？之前看到的，但忘记了！

**Comment by bannedbook** [comment]
用google搜一下

**Comment by iluvni** [comment]
没搜到有效的方法。我记得你的网站之前好像介绍过的。但是我当时没仔细看

**Comment by bannedbook** [comment]
不记得了哦，这些方法一般也会有时效性，当时的方法现在也不一定能行了。
