### ISSUE TITLE
奇怪了

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#267]
我刚开机，开你的软件发现弹出的浏览器不是你的chrome浏览器了。请问怎么回事？我在打开你软件之前就只是改动了一下桌面分辨率！

**Comment by bannedbook** [comment]
那你弹出的是什么呢

**Comment by iluvni** [comment]
弹出的是我电脑默认的猎豹浏览器，昨天还正常弹出你的chrome浏览器的

**Comment by bannedbook** [comment]
你用哪个翻墙方法，哪个bat启动文件

**Comment by iluvni** [comment]
6.Agent0翻墙、蓝灯、ipv6-Agent1、.ipv6-Agent2···所有的都这样

**Comment by bannedbook** [comment]
把 下载的 翻墙包文件，换个目录重新解压一下试试看

**Comment by iluvni** [comment]
换了目录，问题还是没解决。我不知道是不是只有我这里出现这个问题。

**Comment by bannedbook** [comment]
猎豹浏览器 把这个卸载掉如何

**Comment by iluvni** [comment]
照做卸载之后点击软件等了几分钟什么浏览器都没有弹出

**Comment by bannedbook** [comment]
请问下载的是完整版的chromego吧

**Comment by bannedbook** [comment]
为了更稳定、更安全的翻墙，建议卸载国产杀毒软件，至少翻墙时不要用它们！因为很多国产杀毒软件，比如360安全卫生、360杀毒软件、腾讯管家、金山卫士等不仅仅会起干扰作用，造成软件无法正常使用或速度变慢，它们与防火墙还有千丝万缕的关系。现在国外好用的免费杀毒软件也挺多的，网上一搜就有很多。如果翻墙插件被杀毒软件“误删”了或者默默地删掉了，是不能翻墙的，退出杀毒软件，重新解压下载的压缩包。

**Comment by iluvni** [comment]
是的  又出新问题了：原本我打开你的软件可以跳出你的页面 但是刚刚卸载重装浏览器之后弹出的是猎豹的主页面。哦  我试试看

**Comment by iluvni** [comment]
哎，退出杀毒软件再解压软件还是那样

**Comment by bannedbook** [comment]
猎豹浏览器 也是流氓软件 http://tieba.baidu.com/p/2906864621

**Comment by iluvni** [comment]
请问你的软件的chrome.exe在哪个文件夹？我把它添加到毒霸信任程序试试看！

**Comment by bannedbook** [comment]
就在 Browser 这个文件夹

**Comment by iluvni** [comment]
添加了，可还是不行

**Comment by bannedbook** [comment]
卸载金山毒霸后可以了
https://github.com/bannedbook/fanqiang/issues/268
