### ISSUE TITLE
卸载了金山毒霸后，杀毒软件可用了

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#268]
刚刚卸载了金山，安装了avast。现在恢复了。还有一个关于软件的问题：刚刚用avast查杀电脑发现这个报毒
![avast1](https://user-images.githubusercontent.com/24630043/38009734-628789c4-3288-11e8-960d-a9723e248954.jpg)

**Comment by bannedbook** [comment]
这是误报，但这个文件好像我们也没用，可以删掉
