### ISSUE TITLE
agent1-ipv6 如何添加代理地址

### ISSUE THREAD

**Issue by yuban01652** [bannedbook/fanqiang#275]
您好，我下载了新版本的代理包后，发现许多代理都是一键式的，虽然方便但是找不到设置选项，比如agent1-ipv6这种方式个人感觉较快，但有些网站不经过代理直连，请问怎么让这些网站通过代理？或者说有没有全局代理的方式？我只能看到cmd界面，除此之外的chrome和IE都找不到设置选项。

**Comment by bannedbook** [comment]
代理 是 127.0.0.1:8087 ，自己设置 ie 代理就变成全局代理了
