### ISSUE TITLE
求助，GoProxy ipv6版打不开网页，请教版主这个错误是什么意思？有何解决方法？

### ISSUE THREAD

**Issue by hipskil** [bannedbook/fanqiang#276]
![1](https://user-images.githubusercontent.com/38067374/38437370-d1da5d82-3a09-11e8-8865-7f22c8625346.PNG)
![2](https://user-images.githubusercontent.com/38067374/38437375-d6ed8f7e-3a09-11e8-8bbb-420db4d0dc2f.PNG)
![3](https://user-images.githubusercontent.com/38067374/38437384-dc7c5894-3a09-11e8-8543-fc449828f927.PNG)
![4](https://user-images.githubusercontent.com/38067374/38437392-e0fd044a-3a09-11e8-8e7d-894888bbf9ef.PNG)
GA ip6版也打不开网页，和这个一样的问题，想请教一下版主有什么办法吗？ @bannedbook

**Comment by bannedbook** [comment]
进 ipv6-Agent0\ip_Update 目录，更新ip

**Comment by hipskil** [comment]
OK，回去我试一下，我记得我是有试过更新了的，teredo服务器也都换过，dns也换过，话说这个错误提示是什么意思？连接地址超时对吧？

**Comment by bannedbook** [comment]
云端更新GoProxy ipv6和GoAgent ipv6版google ipv6 ip，按照使用说明运行ip更新文件即可同步到最新的云端。如果你更新了最新的ip且所有的teredo的服务器都尝试过，还是不能翻墙，浏览器提示"error": "dial tcp6 [2404:6800:400b:2d::b]:443: i/o timeout"，推测是google ipv6 ip在你所在地区已被全部封锁，所以ipv6版用不了。

建议换其它类型的软件，比如Agent0、v2ray版、Agent3等

**Comment by hipskil** [comment]
🆗，谢谢大大

**Comment by Tino23X** [comment]
使用goproxy相同的问题，应该是上星期开始出现的

但有时我爆的是502
-----------------
502 Bad Gateway

This HTTP request has a Host header that is not covered by the TLS certificate used. Due to an infrastructure change, this request cannot be processed.

----------------
ipv6测试是正常的，
不知道是否还有救？

**Comment by bannedbook** [comment]
2018年12月20日公告：云端更新IPV6版ip，请进对应的ip_Update文件夹更新ip。

**Comment by Tino23X** [comment]
这两天在公司和家里做了一些测试，应该是IP被封了。

**Comment by Tino23X** [comment]
@bannedbook 谢谢，
goagent之前用过一段时间，感觉挺不稳定的，没有goproxy好用，我暂时配了一个免流的lantern，虽然稍微慢一点，但是还比较稳定。能对付一阵子。

**Comment by bannedbook** [comment]
发布最新版chromego，可以试试看
