### ISSUE TITLE
自己搭建的GoAgent服务器，上外网显示404 Not Found

### ISSUE THREAD

**Issue by Csejte** [bannedbook/fanqiang#277]
您好，我也遇到了和 https://github.com/bannedbook/fanqiang/issues/241
一样的问题，使用的google appid搭建完成后只有google.com可以打开，Twitter，youtube，等都打不开，同样报错
404 Not Found
The resource could not be found.
http://yourappid.appspot.com/ 访问这个显示为Hello, World!
请问要怎么解决？

**Comment by bannedbook** [comment]
appid 没上传成功，http://yourappid.appspot.com/  显示 404

**Comment by Csejte** [comment]
是不是我在将自己的APPID部署到Google App Engine时出了错？
我在安照您的说明（GoAgent v3.2.3 自建翻墙服务器）逐步操作时发现要想部署一个APPID还必须要通过Google的一个教程，而且无法跳过，小白表示这个教程完全看不懂TAT...只是一步步勉强完成了部署，但访问http://yourappid.appspot.com/ 显示为Hello, World!，表明APPID没有上传成功...
[`能不能麻烦您稍微详细说明一下该如何成功上传APPID呢？

**Comment by bannedbook** [comment]
最新版 ChromeGo 里面 \ipv6-Agent1\code\default\gae_proxy\server 目录下
用 uploader.bat 来上传
具体看目录下的
README.md
