### ISSUE TITLE
哥们，借一步说话

### ISSUE THREAD

**Issue by dazeGitHub** [bannedbook/fanqiang#279]
哥们，你这一堆反动内容是要干嘛？没意思，反来反去有啥意思？这是被黑客黑了还是故意的？

**Comment by bannedbook** [comment]
https://github.com/programthink/books

**Comment by gybluer** [comment]
我也想知道怎么去取消启动就是禁闻网，有办法了，麻烦告知一下，谢谢！

**Comment by bannedbook** [comment]
这个是免费软件，暂且取消不了啊。不想看的话，关闭一下就好了。
