### ISSUE TITLE
有iOS 的翻墙大法吗

### ISSUE THREAD

**Issue by Ian0903** [bannedbook/fanqiang#281]
只看到电脑版跟安卓的，有iOS 的翻墙大法吗？

**Comment by bannedbook** [comment]
https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E6%89%8B%E6%9C%BA%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6

**Comment by onion111** [comment]
欢迎关注motionpro,全平台vpn，支持Windows,Mac,Linux,Android,iOS，SSL加密，非SS或SSR，多地区多条高速线路，不限流量，欢迎加微信fangming_8888，客服开通体验账号，72小时免费体验。
