### ISSUE TITLE
求助大大 分享下v2ray 搭建方法 自己搭建速度很慢 

### ISSUE THREAD

**Issue by a928006421** [bannedbook/fanqiang#283]
我用了vultr里的洛杉矶的debian9 安装了v2ray  也开启了BBR加速 还是慢 只有400KB/S 用您的 v2ray  有17000KB/S

**Comment by Alvin9999** [comment]
[参考教程](https://github.com/Alvin9999/new-pac/wiki/%E8%87%AA%E5%BB%BAv2ray%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%95%99%E7%A8%8B)推荐选择**普通TCP**传输方式
