### ISSUE TITLE
请问，我如果用自己系统的cherome，应该如何手动设置代理？

### ISSUE THREAD

**Issue by ccav456** [bannedbook/fanqiang#285]
看了相关的帖子，好像没有解答，还希望能够详细教下如何设置，多谢
还有个问题，之前下载一键翻墙包的时候并未使用管理员身份运行agent0，直接实在文件夹中点开goproxy.exe，发觉也能连上翻墙，而且用的自己的cherome，然后重启一下电脑后发觉就不行了，这又是什么原因？如果可以设置应该怎么操作？麻烦解答圈外人的无聊问题，多谢!!!

**Comment by bannedbook** [comment]
第一次启动，管理员身份运行agent0，然后登录一下chrome，就可以把自己的chrome设置，书签、插件等等同步过来，跟自己的chrome一样
