### ISSUE TITLE
建议开启goagent php翻墙模式

### ISSUE THREAD

**Issue by bclswl0827** [bannedbook/fanqiang#286]
goagent gae翻墙现在似乎已经不太管用了，也就是说Google的ip总会有一天被封完，也正因如此，所以建议Chrome＆Firefox一键翻墙包中加入goagent php模式

**Comment by bclswl0827** [comment]
使用一台位于国外的PHP空间结合goagent翻墙，就应该没gae那么容易被封

**Comment by 2848203063** [comment]
http://MyVpnApp.tk

MyOpenVpn我的OPENVPN服务器

MyOpenVpn我的OPENVPN服务器是一套VPN服务系统，包含VPN主服务器，VPN分服务器，客户端包含Android端windows端，

是基于OPENVPN系统二次开发的软件，加入了会员注册模块，计费模块，会员管理模块，

系统权限模块，管理模块，二次加密模块，速度控制模块的软件。基于ISA2006有强大的后端管理功能
支持使用者建立属于你自己的VPN系统，支持管理，计费,多服务器切换等

**Comment by bannedbook** [comment]
可以考虑
不过自己搞的空间，一封ip就得换
