### ISSUE TITLE
无法正常工作  firefox56.2

### ISSUE THREAD

**Issue by truelv** [bannedbook/fanqiang#294]
配置完后还是一样  国内的打的开google之类还是打不开   另外bt sync工具箱下载地址已经失效或者屏蔽了

**Comment by bclswl0827** [comment]
换成chrome版本的吧

**Comment by bannedbook** [comment]
bt sync 下载 https://github.com/killgcd/fg/blob/master/fqb/Resilio-Sync.exe

**Comment by bannedbook** [comment]
你是自建goagent app id吗，如果配置不好，可以直接下载我们的翻墙包使用
