### ISSUE TITLE
建议Google Chrome浏览器内核换回旧版本

### ISSUE THREAD

**Issue by bclswl0827** [bannedbook/fanqiang#296]
建议Google Chrome浏览器内核换回旧版本，58.0以上的版本不再信任GOAGENT的自签名证书，会导致很多https的网站打开时提示『隐私设置错误』，很烦，比如使用Chrome一键翻墙包访问[https://yahoo.co.jp/](https://yahoo.co.jp/)就是这样

**Comment by bannedbook** [comment]
应该不会吧，第一次使用，邮件点击，以管理员身份启动应该就没问题
