### ISSUE TITLE
关于下载限制3m的问题

### ISSUE THREAD

**Issue by netforfreedom** [bannedbook/fanqiang#297]
你好，已经替换了私人的appid，可是下载还是限制3m，请问怎么去除下载限制。谢谢！

**Comment by bannedbook** [comment]
好像 Agent0、Agent2、ipv6-Agent1 无法下载超过32M的文件，其它版本没有限制。

**Comment by netforfreedom** [comment]
谢谢回复,我用的是agent0,用goproxy软件的.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 如何翻墙 <notifications@github.com>
发送时间: Saturday, June 2, 2018 10:43:36 AM
收件人: bannedbook/fanqiang
抄送: netforfreedom; Author
主题: Re: [bannedbook/fanqiang] 关于下载限制3m的问题 (#297)


好像 Agent0、Agent2、ipv6-Agent1 无法下载超过32M的文件，其它版本没有限制。

―
