### ISSUE TITLE
有没旧版的火狐一键翻墙包？

### ISSUE THREAD

**Issue by terryandjing** [bannedbook/fanqiang#298]
新版火狐好多扩展用不了，很不习惯

**Comment by bannedbook** [comment]
旧版基本都覆盖掉了，没有保存啊
需要用什么插件呢

**Comment by terryandjing** [comment]
几个月前的就可以了，我几个月前下载的就是旧版的浏览器，现在更新了新版的浏览器扩展没法用，像flashgot，downthemall，都用不了

**Comment by terryandjing** [comment]
还有一件事，新的翻墙包点击Firefly翻墙，不会自动下载firefly了，会提示找不到文件

**Comment by bannedbook** [comment]
这个是老版本的firefox的
https://aa.gdrive.pw/FirefoxFQ-Classic.7z
