### ISSUE TITLE
自建google appid，项目上传出错，貌似是报的编码错误。。。

### ISSUE THREAD

**Issue by kongdesheng** [bannedbook/fanqiang#301]
如题，上传gae项目时出错。帮忙看下怎么解决，谢谢!
![image](https://user-images.githubusercontent.com/13492191/41210727-f9419d10-6d65-11e8-806e-675351b5c8cb.png)

**Comment by bannedbook** [comment]
最新版 ChromeGo 里面 \ipv6-Agent1\code\default\gae_proxy\server 目录下
用 uploader.bat 来上传
具体看目录下的 
README.md
