### ISSUE TITLE
不太明白到底如何iphone翻墙，求大神告知

### ISSUE THREAD

**Issue by 327052103** [bannedbook/fanqiang#302]
按照教程上面，打开wifi里面的 代理 自动 然后输入论坛的好几个地址   然后再用自带浏览器打开网站还是不行根本打不开 或者直接复制地址打开 出现的页面就是空白或乱码 到底如何设置才是对的 求告知 感谢

**Comment by bannedbook** [comment]
https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E6%89%8B%E6%9C%BA%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6

**Comment by gfw-breaker** [comment]
@327052103 AppStore上的VPN应用基本都被强制下架， 目前有几款Shadowsocks客户端可用， 可以试试 OpenWingy、SuperWingy、SkipWorld、SsrConnectPro。 另外需要Shadowsocks账号。

或者直接使用 Web代理： [YouTube代理 ]( https://nogfw.the-youtube.win/)  ，         [通用Web代理](https://node1.free-ss.win/)
