### ISSUE TITLE
agent0 是不是不好用了啊 咋办

### ISSUE THREAD

**Issue by emberrsspirit** [bannedbook/fanqiang#303]

**Comment by bannedbook** [comment]
蓝灯版 和 Agent3 可以试试看

**Comment by 171563857** [comment]
@bannedbook 
一直提示"read udp: closing session in order to recreate it with a new version"
然后全是bad_addr
good_addr 最多就一个...
这是怎么回事

**Comment by terryandjing** [comment]
@bannedbook 
中国移动的宽带是不是用不了ipv6?

**Comment by edc-hui** [comment]
agent0今天发现不能用了，不过现在用的agent3

**Comment by bannedbook** [comment]
@terryandjing  这个我不确定啊。 可以设置试试看 。
看看 2.ipv6-Agent1翻墙.使用说明（必看）.rtf 这个文档，运行 2.配置IPv6.bat 试试看

**Comment by iluvni** [comment]
望 突破封锁

**Comment by jiangossac** [comment]
从昨天开始就不能正常使用了~

**Comment by 171563857** [comment]
全线崩溃....
ipv6用不了
只有v2ray可以
这次是怎么回事,这么大规模,所有ip全部炸了

**Comment by bannedbook** [comment]
2018年6月19日公告：云端更新IPV6版ip，请进对应的ip_Update文件夹更新ip。

**Comment by bannedbook** [comment]
<p><b>2018年6月21日公告：</b>agent0已被封锁，建议使用Agent3、蓝灯、v2ray、psiphon3、IPV6等通道</p>

**Comment by ShrekerNil** [comment]
Agent0,页面报错如下，谁知道什么问题：
{
    "type": "localproxy",
    "host": "127.0.0.1:8087",
    "software": "goproxy r1549 (go/devel +3ff7eb1321 Sat Aug 19 01:55:08 2017 +0000 windows/386)",
    "filter": "*gae.Filter",
    "error": "read udp: NetworkIdleTimeout: No recent network activity."
}

**Comment by ShrekerNil** [comment]
已改Agent3，更新id后正常运行

**Comment by bannedbook** [comment]
2019年3月24日公告：增加ipv6-xxnet翻墙，众多更新，请下载新版。
