### ISSUE TITLE
翻墙软件连不上服务器了

### ISSUE THREAD

**Issue by lb800** [bannedbook/fanqiang#304]
0622 00:58:41.445925    6588 dialer2.go:266] MULTIDIALER DialQuic("clients3.google.com:443") with good_addrs=0, bad_addrs=1925
E0622 00:58:41.446928    6588 handler.go:96] 127.0.0.1:55911 Filter RoundTrip *gae.Filter error: read udp: NetworkIdleTimeout: No recent network activity.
W0622 00:58:46.451421    6588 gaetransport.go:122] GAE *h2quic.RoundTripper.RoundTrip(retry=1) for "https://clients3.google.com/generate_204"
I0622 00:58:46.451421    6588 dialer2.go:266] MULTIDIALER DialQuic("clients3.google.com:443") with good_addrs=0, bad_addrs=1925
I0622 00:58:48.573223    6588 stripssl.go:151] 127.0.0.1:56651 "STRIP CONNECT accounts.google.com:443 HTTP/1.1" - -
I0622 00:58:51.461816    6588 gae.go:382] GAE EnableDeadProbe probeQuic error: read udp: NetworkIdleTimeout: No recent network activity.
I0622 00:58:51.461816    6588 dialer2.go:266] MULTIDIALER DialQuic("accounts.google.com:443") with good_addrs=0, bad_addrs=1925
W0622 00:58:56.467049    6588 gae.go:552] 127.0.0.1:56651 "GAE DIRECT POST https://accounts.google.com/ListAccounts?gpsia=1&source=durations_metrics,counter:7,load_time_ms:1086423&json=standard HTTP/1.1" error: *net.OpError(read udp: NetworkIdleTimeout: No recent network activity.)
I0622 00:58:56.467049    6588 dialer2.go:266] MULTIDIALER DialQuic("clients3.google.com:443") with good_addrs=0, bad_addrs=1925
E0622 00:58:56.467049    6588 handler.go:96] 127.0.0.1:56651 Filter RoundTrip *gae.Filter error: read udp: NetworkIdleTimeout: No recent network activity.

**Comment by bannedbook** [comment]
<p><b>2018年6月21日公告：</b>agent0已被封锁，建议使用Agent3、蓝灯、v2ray、psiphon3、IPV6等通道</p>

**Comment by 171563857** [comment]
@bannedbook 
补充下,要先测试当地运营商是否开启ipv6的支持
http://test-ipv6.com/

**Comment by truth315** [comment]
@lb800 无界还可以用

**Comment by bannedbook** [comment]
网友反馈:
原来是IPV6问题，之前IPV6都ok的，结果就没往上面想，
试了一下，现在只有第10个IPV6服务器能通了，
不知道是不是因为电信动了手脚
