### ISSUE TITLE
貌似都不能用了~

### ISSUE THREAD

**Issue by jiangossac** [bannedbook/fanqiang#306]
前些天，AGENT 3 还可以用，这两天又开始不能用了，试了好多种方法也不行~

**Comment by bannedbook** [comment]
蓝灯、agent3、v2ray 应该还可用，可以更新ip后尝试

**Comment by bannedbook** [comment]
网友反馈:
原来是IPV6问题，之前IPV6都ok的，结果就没往上面想，
试了一下，现在只有第10个IPV6服务器能通了，
不知道是不是因为电信动了手脚

**Comment by jiangossac** [comment]
好的，非常谢谢。

**Comment by 2848203063** [comment]
http://MyWebProxy.tk

MyWebProxy我的代理服务器
MyWebProxy是一套代理服务器软件，包含VPN主服务器，VPN分服务器，客户端包含Android端windows端，

支持使用者建立属于你自己的WebProxy系统，支持管理，计费,多服务器切换等 ,基于ISA2006有强大的后端管理功能
