### ISSUE TITLE
能否用SwitchyOmega+chrome来翻？

### ISSUE THREAD

**Issue by ldk6** [bannedbook/fanqiang#310]
是否可以？要如何设置SwitchyOmega？我设置成127.0.0.1 端口8087翻不了。

**Comment by bannedbook** [comment]
chromego 可以不要插件，启动脚本会自动设置代理的

**Comment by 2848203063** [comment]
找到一搭建自己vpn服务器的工具
免费的，不用谢
http://148.163.171.13
