### ISSUE TITLE
关于蓝灯的问题

### ISSUE THREAD

**Issue by hjnnjh** [bannedbook/fanqiang#312]
库主我想问一下蓝灯翻墙那个cmd文件的作用是什么啊？为什么每次开机蓝灯都自动启动，我想卸载也找不到。

**Comment by hjnnjh** [comment]
还有就是使用Agent3翻墙时我自己打开的chrome窗口不行，自动打开的窗口却可以

**Comment by bannedbook** [comment]
我记得蓝灯启动后，会自动打开一个页面，在那个页面上 有 设置选项，可以禁止 蓝灯开机启动。

蓝灯翻墙那个cmd文件，可以用来手动启动蓝灯

**Comment by hjnnjh** [comment]
那压缩包里Lantern那个文件夹里的又是什么呢？蓝灯的安装程序还是什么？

**Comment by bannedbook** [comment]
里面就是蓝灯的执行程序

**Comment by hjnnjh** [comment]
cmd就是直接调用里面的程序对吧？

**Comment by bannedbook** [comment]
是的

**Comment by hjnnjh** [comment]
好的，感谢库主的解答
