### ISSUE TITLE
蓝灯的问题

### ISSUE THREAD

**Issue by zhdzaq** [bannedbook/fanqiang#313]
为什么现在蓝灯的刷新配置不好使了，每次刷新完都是依旧没有流量，求解

**Comment by bannedbook** [comment]
是不是你的免费流量用完了？

**Comment by zhdzaq** [comment]
是的，不过在没用完的情况下刷新配置也不好使啊，也是刷新完没有效果，还是那个流量

**Comment by bannedbook** [comment]
这个刷新，只是把配置文件清空一下，解决一些配置文件紊乱错误的情况。

**Comment by bannedbook** [comment]
跟流量没有关系。

**Comment by zhdzaq** [comment]
明白了，不过我记得好像以前是无限续杯的意思啊，有可能是我记错了
