### ISSUE TITLE
ChromeGo完整版安装包怎么没了？

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#315]
请问ChromeGo完整版是不是不提供下载了？

**Comment by bannedbook** [comment]
完整版比较大，下载比较费劲，其实 自己安装一个chrome ，然后下载轻便版 比较好。
https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85#chromego-down
