### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by iluvni** [bannedbook/fanqiang#317]
你好，首先我感谢你们工作组能够让我们看到国内看不到的新闻！我的问题是为什么我使用你们新版的chrome后会自动下载许多文件！请问是怎么回事？

**Comment by bannedbook** [comment]
什么多余的文件？
chrome运行过程中就会产生很多文件，不见得是下载的

**Comment by iluvni** [comment]
是下载的 杀毒软件有提示。我截图给你看

还有一个问题。新版的软件里也没有更新chrome的选项了。

**Comment by iluvni** [comment]
![zdxz](https://user-images.githubusercontent.com/24630043/44385309-970dd400-a551-11e8-9b8d-de117b199072.jpg)

**Comment by bannedbook** [comment]
正常吧

**Comment by bannedbook** [comment]
还可以按以前的方法更新。
或者下载新版的chrome再安装一遍也行。

**Comment by iluvni** [comment]
好的
