### ISSUE TITLE
输入我的邀请码 YYPJJXH 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by LJFING** [bannedbook/fanqiang#320]
输入我的邀请码 YYPJJXH 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by wtixsx** [comment]
YYPJJXH

**Comment by HnlyWk** [comment]
脑子一热自己刚租了个海外服务器搭了个节点。。
试了下，速度非常快，只是一个人用贵了点，，就偶尔用用谷歌和FB。。
求几个小伙伴合伙，费用均摊，大概每人10块就好了，只要7个人。。
要求：轻度使用，以免影响速度。
PS. 亲测上油管看1080P视频没问题。。

需要的可以留言，不定期上github

**Comment by anlexN** [comment]
您是怎么拿到邀请码的？方便透露一下剧情吗？

**Comment by Metka955** [comment]
> 脑子一热自己刚租了个海外服务器搭了个节点。。
> 试了下，速度非常快，只是一个人用贵了点，，就偶尔用用谷歌和FB。。
> 求几个小伙伴合伙，费用均摊，大概每人10块就好了，只要7个人。。
> 要求：轻度使用，以免影响速度。
> PS. 亲测上油管看1080P视频没问题。。
> 
> 需要的可以留言，不定期上github

q1010729083

**Comment by tomatoKnightJ** [comment]
输入我的邀请码 YPBKSVV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by DenghuaCN** [comment]
> 脑子一热自己刚租了个海外服务器搭了个节点。。
> 试了下，速度非常快，只是一个人用贵了点，，就偶尔用用谷歌和FB。。
> 求几个小伙伴合伙，费用均摊，大概每人10块就好了，只要7个人。。
> 要求：轻度使用，以免影响速度。
> PS. 亲测上油管看1080P视频没问题。。
> 
> 需要的可以留言，不定期上github



> 脑子一热自己刚租了个海外服务器搭了个节点。。
> 试了下，速度非常快，只是一个人用贵了点，，就偶尔用用谷歌和FB。。
> 求几个小伙伴合伙，费用均摊，大概每人10块就好了，只要7个人。。
> 要求：轻度使用，以免影响速度。
> PS. 亲测上油管看1080P视频没问题。。
> 
> 需要的可以留言，不定期上github

try?
