### ISSUE TITLE
关于ubuntu版本

### ISSUE THREAD

**Issue by MichelleYang2017** [bannedbook/fanqiang#322]
我想请问一下有没有ubuntu版本的翻墙手册说明和软件

**Comment by wjjsmile** [comment]
有的 ssr

MichelleYang2017 <notifications@github.com> 于 2018年9月29日周六 23:58写道：

**Comment by bannedbook** [comment]
无界浏览 推出了 Linux VPN17.03 
可以翻墙后下载 http://www.wujieliulan.com/download.php
