### ISSUE TITLE
MAC版本的有吗？

### ISSUE THREAD

**Issue by alleztous** [bannedbook/fanqiang#323]

**Comment by wjjsmile** [comment]
有的 加下qq群 799976430

chen wei <notifications@github.com> 于 2018年9月30日周日 23:30写道：

**Comment by bannedbook** [comment]
看看这里
https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E7%94%B5%E8%84%91MAC%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6
