### ISSUE TITLE
蓝灯邀请码 JBKQY8     浙江移动使用正常，安卓系统8.1

### ISSUE THREAD

**Issue by charleshw** [bannedbook/fanqiang#325]
坐标杭州，安卓系统，目前使用正常

邀请码  JBKQY8

**Comment by anlexN** [comment]
您是怎么拿到邀请码的？方便透露一下剧情吗？

**Comment by charleshw** [comment]
打开蓝灯，里面有个邀请好友，点开就能看到

anlex N <notifications@github.com> 于 2018年10月16日周二 14:37写道：
