### ISSUE TITLE
使用Resilio-Sync的时候，输入密匙之后，怎么连接不上呢？

### ISSUE THREAD

**Issue by GrandMamba** [bannedbook/fanqiang#326]
在登录了Resilio-Sync的时候，按照步骤创建好了文件夹，但是不能够同步呀，这个问题怎么解决呢？

**Comment by bannedbook** [comment]
[聊聊 GFW 如何封杀 Resilio Sync（BTSync）？以及如何【免翻墙】继续使用？](https://github.com/bannedbook/fanqiang/blob/master/RESILIO-SYNC/btfq.md)

**Comment by maxiao124** [comment]
@bannedbook 文章中提到的各个版本的下载地址在哪儿？

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/tree/master/RESILIO-SYNC

**Comment by maxiao124** [comment]
@bannedbook 这里面的软件，点开链接之后直接下载了，是一个固定的版本
