### ISSUE TITLE
在设置Resilino的时候，代理服务器的IP和端口设置问题

### ISSUE THREAD

**Issue by GrandMamba** [bannedbook/fanqiang#327]
我用的是1.4.111版本的，代理服务器用的是VPN，但是输入IP和端口号的时候，输入的IP是VPN的IP，端口号是8080，这样的设置是否有问题，到现在还没有节点可以看到

**Comment by bannedbook** [comment]
VPN 应该是不需要设置代理的一般好像

需要设置代理，那就不是vpn吧 

首先，你用那个ip 和 端口 设置作为浏览器的 代理能不能上网？
