### ISSUE TITLE
ubuntu下各位怎么科学上网啊

### ISSUE THREAD

**Issue by ranjiewwen** [bannedbook/fanqiang#331]
ubuntu下各位怎么科学上网啊，用什么工具啊，麻烦了，有没有好的教程，最近苦于很多资料查看不了在ubuntu下

**Comment by bannedbook** [comment]
https://github.com/Alvin9999/new-pac/wiki/Linux%E7%B3%BB%E7%BB%9F%E7%BF%BB%E5%A2%99%E6%96%B9%E6%B3%95

**Comment by charleshw** [comment]
蓝灯啊
