### ISSUE TITLE
无界浏览pc版挂了

### ISSUE THREAD

**Issue by ccy0shw** [bannedbook/fanqiang#341]
任何一个版本不可用
18.06版和19.01版是99.5%，99.5%，99.5%，然后连接不上
之前版本是0%，0%，0%，然后连接不上
自由门可用
![default](https://user-images.githubusercontent.com/25379437/52276208-8da3e700-298c-11e9-858c-db68e3167d6c.png)
![2](https://user-images.githubusercontent.com/25379437/52276209-8e3c7d80-298c-11e9-8bba-c5430f862b2f.png)

**Comment by bannedbook** [comment]
自由门好像前几天出了新版...
