### ISSUE TITLE
iphone翻墙要怎么实现啊，求教

### ISSUE THREAD

**Issue by zer946** [bannedbook/fanqiang#343]
iphone翻墙要怎么实现啊，求教

**Comment by bannedbook** [comment]
https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E6%89%8B%E6%9C%BA%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6

**Comment by xwtxwy** [comment]
http://yunsu.aicaibai.com/share.html?channel=kdl16 这个下载就可以

**Comment by wyfSunflower** [comment]
求助，请问现在有适合ubuntu的教程么？我以前用的lantern能用只是比较慢，但是最近是彻底不能用了，任何时间根本连不上，多谢啊！

**Comment by bannedbook** [comment]
https://github.com/Alvin9999/new-pac/wiki/Linux%E7%B3%BB%E7%BB%9F%E7%BF%BB%E5%A2%99%E6%96%B9%E6%B3%95
