### ISSUE TITLE
Firefox中蓝灯显示流量用完

### ISSUE THREAD

**Issue by zhousanzhang** [bannedbook/fanqiang#345]
火狐浏览器中的蓝灯显示流量用尽，刷新也无法翻墙，其他的选项翻墙也非常的缓慢，不知道楼主能否提供一下解决办法？谢谢了

**Comment by bannedbook** [comment]
自由门、无界 试试看

**Comment by zhousanzhang** [comment]
自由门、无界 非常慢啊，有时候上不去

**Comment by bannedbook** [comment]
2019年3月24日公告：增加ipv6-xxnet翻墙，众多更新，请下载新版。
