### ISSUE TITLE
Agent3 里面的shadowsock 更新IP失败噢

### ISSUE THREAD

**Issue by wtw888** [bannedbook/fanqiang#346]
Agent3 里面的shadowsock 
在ip_Update更新 ip_1.bat 和 ip_2.bat 更新失败啊，dos返回这个错误
 在部分win10系统里会出现这种情况啊，如何补救呀
![1](https://user-images.githubusercontent.com/48409200/54085653-48a01580-437b-11e9-9745-7bdf25e15fa8.png)

**Comment by bannedbook** [comment]
c:\9158 
这个目录下应该有个 wget.exe 
你的有吗

**Comment by wtw888** [comment]
解决啦，原来是复制的时候没把这个文件复制过去呢，谢谢啦，你们都是法轮功么？

如何翻墙 <notifications@github.com>于2019年3月11日 周一10:26写道：
