### ISSUE TITLE
启用v2ray工具后，部署Tomcat网络项目，chrome无法访问localhost:8080怎么解决？

### ISSUE THREAD

**Issue by Schlatter076** [bannedbook/fanqiang#350]
启用v2ray工具后，部署Tomcat网络项目，chrome无法访问localhost:8080怎么解决？

**Comment by bannedbook** [comment]
把 Tomcat 的端口改一下

**Comment by Schlatter076** [comment]
> 把 Tomcat 的端口改一下
也有改过端口试过，只是在开了翻墙代理之后Chrome访问不了localhost。我看您的批处理启动有这么一句：--host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE 127.0.0.1"。
是排除localhost的意思吗？我改成include则无法翻墙，而且如果我不打开V2Rey或其他的翻墙工具，则可以正常访问Tomcat。

**Comment by bannedbook** [comment]
我觉得这个就是端口冲突
xxnet 可能占用了 8085 8086 8087 等等端口 ，我不确定有没有 8080

你就把tomcat 端口改个别的，比如 9999 试试看

**Comment by Schlatter076** [comment]
大佬，时真的不行，我改过很多次端口。就只是在启用了v2ray工具后，用IE可以访问，而chrome无法连接到localhost。当我一旦我关掉它，chrome可正常访问

**Comment by Schlatter076** [comment]
我现在用127.0.0.1:8080替换localhost:8080则可以访问到，确实不知道为什么

**Comment by bannedbook** [comment]
这个好奇怪啊，搞不清楚。那就用127.0.0.1:8080吧
