### ISSUE TITLE
添加变量仍显示找不到chrome

### ISSUE THREAD

**Issue by dyxang** [bannedbook/fanqiang#355]
chrome-master文件夹在e盘根目录
chrome.exe在 C:\Users\Administrator.000\AppData\Local\Google\Chrome\Application\chrome.exe
![aa](https://pic.superbed.cn/item/5cb2961a3a213b041736671c)
我现在是手动打开chrome

**Comment by bannedbook** [comment]
path 变量 是添加目录，把
C:\Users\Administrator.000\AppData\Local\Google\Chrome\Application\chrome.exe
改成
C:\Users\Administrator.000\AppData\Local\Google\Chrome\Application

**Comment by dyxang** [comment]
> path 变量 是添加目录，把
> C:\Users\Administrator.000\AppData\Local\Google\Chrome\Application\chrome.exe
> 改成
> C:\Users\Administrator.000\AppData\Local\Google\Chrome\Application

了解
