### ISSUE TITLE
给个建议

### ISSUE THREAD

**Issue by chillybird** [bannedbook/fanqiang#360]
我不知道这个是不是国人开的源，但是搞什么禁网真的过分了，中国是一个人口大国，是共产党让中国从贫穷落后发展到当今的繁荣和富足，这真的是不易的，中国的繁荣是中国人的奇迹。但竟然给我讲啥党文化的三板斧，真的是tmd的智障

**Comment by bannedbook** [comment]
禁网最厉害的是中共，中共国的互联网就是个局域网，局域网造就愚民。
