### ISSUE TITLE
Too shy...

### ISSUE THREAD

**Issue by wangqita** [bannedbook/fanqiang#363]
运行蓝灯后可以翻墙 注册了Gmail  然后在注册推和脸书的时候发送邮件为什么一直看不到呢... netflix也看不了   我这问题太小白了但还是不知道要怎么办...

**Comment by bannedbook** [comment]
gmail web 界面有3个 tab，主要、社交、推广
推特和脸书的邮件，估计在 社交 里面

**Comment by wangqita** [comment]
没有...社交和推广下面只有广告

**Comment by wangqita** [comment]
不好意思再劳烦问一下   国内的那些杀毒软件比如鲁大师 Windows defender卸载了也无什么事？ 不会有什么病毒啥的...   刚刚不小心忘记关掉鲁大师  一直被警告

**Comment by bannedbook** [comment]
凡是国内的杀毒、防火墙、电脑管家等等安全软件一律不用，会干扰翻墙，记录隐私。
Windows defender 好像就是windows自带的，应该可以用
