### ISSUE TITLE
运行Trojan出现不知道这样的主机

### ISSUE THREAD

**Issue by Vogel0** [bannedbook/fanqiang#372]
![Z%O5NTSH5RG3@{M`66}$5`N](https://user-images.githubusercontent.com/51629405/59190892-85fd8480-8bb0-11e9-9dec-d6b284318547.png)

**Comment by bannedbook** [comment]
请到相应的ip_Update目录 更新一下试试看

**Comment by Vogel0** [comment]
虽然这个问题很蠢…但是Trojan里面好像没有brook/v2ray那样的更新目录
![DOSB}QM(PBO{49R}}R{7LP9](https://user-images.githubusercontent.com/51629405/59192741-01156980-8bb6-11e9-9d5e-1ce3a20498ea.png)

**Comment by bannedbook** [comment]
抱歉，稍后我更新一下

**Comment by bannedbook** [comment]
<li><strong>2019年6月10日公告：</strong>更新trojan和v2ray，增加抗封锁性，请下载最新版使用。</li>

**Comment by Vogel0** [comment]
可以用了  感谢大佬！
