### ISSUE TITLE
求解mac翻墙

### ISSUE THREAD

**Issue by perfectSymphony** [bannedbook/fanqiang#376]

**Comment by bannedbook** [comment]
https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E7%94%B5%E8%84%91MAC%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6

**Comment by perfectSymphony** [comment]
有没有破解的mac版本的蓝灯

**Comment by oszone** [comment]
最新神器Mac神器，可看看 https://jiasu.gitbook.io/index/

**Comment by perfectSymphony** [comment]
破解版的地址贴一下，老铁
