### ISSUE TITLE
sb,以为翻个墙看个反政府网站就很了不起.动不动就回圈里去.你这种人连基本的是非都不能判断,悲哀!

### ISSUE THREAD

**Issue by MacMang** [bannedbook/fanqiang#390]
sb,回圈里去吧

_Originally posted by @tomail in https://github.com/bannedbook/fanqiang/issues/388#issuecomment-517975554_

**Comment by oasis1ee** [comment]
同感，本来东西是不错的，但是自动加了一堆乱七八糟的书签，就觉得很恶心
顺带一提直接用v2/ssr什么的不好吗
