### ISSUE TITLE
ChromeGo

### ISSUE THREAD

**Issue by Chris-z-su** [bannedbook/fanqiang#405]
您好，请问我更新了IP，卸载了电脑管家，还是无法fangqiang，brook打开的浏览器连普通的百度、GitHub都进不去，怎么办呢？而且我这是从GitHub上重新下载的一个项目，谢谢！

**Comment by bannedbook** [comment]
ChromeGo 里面的每个工具都试一试

**Comment by fayehk** [comment]
越来越难，试遍一键翻，之前灯还成，现在基本都不好用了，暂时这个还能用
安卓,苹果,Mac,Windows 好用的加速器 刷INS、访推特，完美支持高清1080P视频，无任何流量限制,真正免费的加速器 https://ant.antss026.com/aff/6raf

**Comment by Chris-z-su** [comment]
> 可以啊 有偿ss 需要？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "z宝宝宝"<notifications@github.com>; 发送时间: 2019年9月24日(星期二) 晚上9:45 收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: Re: [bannedbook/fanqiang] ChromeGo (#405) 为什么还不行呢？都用不了了，你们可以吗？还是现在teshu时期？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

不好意思，我自己弄吧，没必要，谢谢
