### ISSUE TITLE
我们不能上外网就是你们这帮轮子害的

### ISSUE THREAD

**Issue by thewake** [bannedbook/fanqiang#409]
你们怎么能这么坏呢

**Comment by bannedbook** [comment]
斯德哥尔摩综合症？
没有共产党，怎么会有网络封锁

**Comment by samdashu123** [comment]
> 你们怎么能这么坏呢

小粉红跟曾经的红卫兵一模一样，又蠢又毒只会批斗别人，把整个国家带入深渊

**Comment by bbfxier** [comment]
你错了，好用稳定的翻墙方法都是轮子开发的
你可以试试这个
https://github.com/Alvin9999/new-pac/wiki/Goflyway%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7

**Comment by PyfanLiu** [comment]
讨厌轮子归讨厌，共产党不想让大众知道自己的丑事不能怪轮子，我也很讨厌邪教，不信就好了，翻墙还是要用的，那些有偏差的禁闻看了笑一笑就好，新闻联播和大鸡元的和在一起看，大概就是中国现状了
