### ISSUE TITLE
cloudflare 免费VPN 

### ISSUE THREAD

**Issue by bannedbook** [bannedbook/fanqiang#414]
cloudflare 免费VPN 
https://one.one.one.one/
大家试试看 能不能翻墙

**Comment by G-Bruin** [comment]
不能翻，老哥！

**Comment by yunsendong** [comment]
不能！

**Comment by Anki-teen** [comment]
下载链接：https://dwz.cn/QtUyonPO 安装后填写邀请码：19167706 可以免费用
*但是只能免费用四天*
