### ISSUE TITLE
最近国外网站下视频服务器错误 拒绝访问

### ISSUE THREAD

**Issue by KrysMs1** [bannedbook/fanqiang#418]
上上个月左右开始吧 有些原来很好的在线网站 像sexloading  avcrempie 这种类型的满速下 速度可能会越来越慢 但至少开始能满速 

最近就是所有都显示服务器错误 拒绝访问 403 播放器内核也换成了openload  原来好像是Fembed 

FreePorn 你们应该都有看 用浏览器还有点速度 没一会就下载失败 不知道大家能不能下了 是不是我换了系统的问题

**Comment by bannedbook** [comment]
我们不支持色情网站
