### ISSUE TITLE
换了移动的宽带不能用了怎么办

### ISSUE THREAD

**Issue by wudonghe1996** [bannedbook/fanqiang#422]
重下好几次了，用热点就能用，用宽带就不能用，有什么解决办法啊

**Comment by Alvin9999** [comment]
软件有很多不同的翻墙方式，比如goflyway、trojan、v2ray、brook、ssr等，可以都试试看。

**Comment by wudonghe1996** [comment]
> 软件有很多不同的翻墙方式，比如goflyway、trojan、v2ray、brook、ssr等，可以都试试看。

都试过了 不能用啊。。

**Comment by bannedbook** [comment]
有的移动宽带很难用，好像是这样吧

**Comment by Alvin9999** [comment]
把防火墙、杀毒软件、安全卫士全部关闭，删掉文件夹，重新解压后再更新ip

**Comment by Alvin9999** [comment]
实在不行的话，那就是移动宽带的本身限制
