### ISSUE TITLE
为什么我用了这些软件以后现在不翻墙chrome用不了了？

### ISSUE THREAD

**Issue by only-tao** [bannedbook/fanqiang#431]
rt，别的浏览器都可以用。
chrome显示1080端口问题，
而且qq的一些东西不如qq群文件一直是无法显示，
微软的应用比如OneNote也用不了了，错误码0x80070005.
希望大佬能帮我解决这个问题，谢谢

**Comment by only-tao** [comment]
是因为异常关闭的原因吗？

**Comment by bannedbook** [comment]
可能是异常关闭的原因
看一下ie 代理，把ie代理取消掉。

**Comment by only-tao** [comment]
internet设置那里点了但是没有办法点确定，（确定点了没有反应）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "如何翻墙"<notifications@github.com&gt;; 
发送时间: 2020年1月1日(星期三) 晚上8:39
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;; 
抄送: "only_tao"<1312751075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bannedbook/fanqiang] 为什么我用了这些软件以后现在不翻墙chrome用不了了？ (#431)




可能是异常关闭的原因
 看一下ie 代理，把ie代理取消掉。

**Comment by bannedbook** [comment]
看下这里
https://support.microsoft.com/zh-cn/help/2289942/how-to-reset-your-internet-explorer-proxy-settings

**Comment by only-tao** [comment]
试过了两个方法，但是都没有用，第一个自动配置：但是那个程序显示我的电脑没有IE789,不适用
第二个人工配置按那个操作做了但是依旧没有用。





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "如何翻墙"<notifications@github.com&gt;; 
发送时间: 2020年1月2日(星期四) 上午9:10
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;; 
抄送: "only_tao"<1312751075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bannedbook/fanqiang] 为什么我用了这些软件以后现在不翻墙chrome用不了了？ (#431)




看下这里
 https://support.microsoft.com/zh-cn/help/2289942/how-to-reset-your-internet-explorer-proxy-settings

**Comment by bannedbook** [comment]
你是不是已经能看到ie里有代理，但是取消不掉？

**Comment by bannedbook** [comment]
要不你正常启动蓝灯，然后正常退出蓝灯，这样试试看

**Comment by only-tao** [comment]
我这里用不了蓝灯的，不过我试了试别的软件，最后终于可以了。
太感谢你了！





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "如何翻墙"<notifications@github.com&gt;; 
发送时间: 2020年1月2日(星期四) 下午3:39
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;; 
抄送: "only_tao"<1312751075@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bannedbook/fanqiang] 为什么我用了这些软件以后现在不翻墙chrome用不了了？ (#431)




要不你正常启动蓝灯，然后正常退出蓝灯，这样试试看

**Comment by only-tao** [comment]
我早就应该这样做了，如果是正常关闭的话，再开一次就好了
