### ISSUE TITLE
设置系统变量path之后哟然没有解决“找不到chrome.exe”的问题

### ISSUE THREAD

**Issue by tokiofoster** [bannedbook/fanqiang#433]
下载安装chrome浏览器后，设置里系统变量path，调整了优先级，但依然没有解决问题，请问是否有其他解决方法

**Comment by bannedbook** [comment]
在chromego文件夹下创建一个目录：Browser
然后，右键点桌面的chrome图标，找到chrome.exe文件的路径，然后打开那个目录。
把chrome.exe 连同那个目录下的所有子文件夹和文件，一起拷贝到
chromego文件夹下Browser目录里面，然后再试试看

**Comment by tokiofoster** [comment]
谢谢，已解决！
