### ISSUE TITLE
Windows找不到文件

### ISSUE THREAD

**Issue by rosemengzi** [bannedbook/fanqiang#435]
![2020-01-06](https://user-images.githubusercontent.com/59559434/71819933-769fd480-30c8-11ea-8f4b-f5e89f3a5d9c.png)
运行.cmd以后选3跳过，显示Windows找不到文件，路径目录没有空格，也没有中文，还请大佬解答。

**Comment by bannedbook** [comment]
请按这个办法试试看
https://github.com/bannedbook/fanqiang/issues/432

**Comment by rosemengzi** [comment]
我仔细看了下文件运行前后的变化知道问题出在哪儿了，是杀毒软件在运行文件时检测到了然后自动删除了文件，我已经解决了这个问题，多谢解答
