### ISSUE TITLE
请问哪里购买vpn账号？一个月30那种？

### ISSUE THREAD

**Issue by henbucuoshanghai** [bannedbook/fanqiang#439]

**Comment by Alvin9999** [comment]
https://github.com/killgcd/justmysocks/blob/master/README.md

**Comment by highertq** [comment]
30很贵了吧，我用的这个还行，有很多线路，国内国外都有平时可以当游戏加速器使用， 10块钱一个月，有需要就看看吧 注册你和我都能多得100G流量， https://www.kuailimao.cloud/register?aff=18343

**Comment by henbucuoshanghai** [comment]
注册就可以？

**Comment by ying5504242** [comment]
https://www.vultr.com/?ref=8538588-6G
买服务器，自己达，不会我可以教你。按照汇率现在是35一个月左右。5美金一个月。

**Comment by Yifangmo** [comment]
https://aom.monster/auth/register?code=6k4E
