### ISSUE TITLE
下载的Shadowsocks怎么无法运行？

### ISSUE THREAD

**Issue by Tallerrand** [bannedbook/fanqiang#440]

**Comment by Alvin9999** [comment]
是下载的一键包浏览器还是什么？

**Comment by Tallerrand** [comment]
> 是下载的一键包浏览器还是什么？

不是，是从just my sock付费下载的软件

**Comment by Alvin9999** [comment]
截图看看，把问题描述的详细点会更能帮助到你

**Comment by Tallerrand** [comment]
> 截图看看，把问题描述的详细点会更能帮助到你

出现了（问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	Shadowsocks.exe
  应用程序版本:	4.1.6.0
  应用程序时间戳:	5cb72245
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.18409
  故障模块时间戳:	53159a86
  异常代码:	e0434352
  异常偏移:	0000c42d
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	0a9e
  其他信息 2:	0a9e372d3b4ad19135b953a78882e789
  其他信息 3:	0a9e
  其他信息 4:	0a9e372d3b4ad19135b953a78882e789
）
我直接复制过来了，我在程序已经设置了兼容性和管理员身份运行，依旧还是无法运行

**Comment by Alvin9999** [comment]
电脑有没有安装NET Framework 4.0？

**Comment by Tallerrand** [comment]
> 电脑有没有安装NET Framework 4.0？

安装了4.5的，你的意思是两个软件冲突了吗？

**Comment by Alvin9999** [comment]
应该不会，确定下安装没有。
你通过这个地址下载ss或ssr试试看[全平台SS/SSR客户端下载汇总](http://www.mediafire.com/folder/sfqz8bmodqdx5/shadowsocks%E7%9B%B8%E5%85%B3%E5%AE%A2%E6%88%B7%E7%AB%AF)

**Comment by bannedbook** [comment]
https://github.com/shadowsocks/shadowsocks-windows/releases
下载最新版4.1.9.2试试看
注意，just my sock 要用 shadowsocks（SS）客户端，不能用SSR客户端

**Comment by Tallerrand** [comment]
> 应该不会，确定下安装没有。您
> 通过这个地址下载ss或ssr试试看[全平台SS / SSR客户端下载汇总](http://www.mediafire.com/folder/sfqz8bmodqdx5/shadowsocks%E7%9B%B8%E5%85%B3%E5%AE%A2%E6%88%B7%E7%AB%AF)

**Comment by Tallerrand** [comment]
> 应该不会，确定下安装没有。
> 你通过这个地址下载ss或ssr试试看[全平台SS/SSR客户端下载汇总](http://www.mediafire.com/folder/sfqz8bmodqdx5/shadowsocks%E7%9B%B8%E5%85%B3%E5%AE%A2%E6%88%B7%E7%AB%AF)

问题已解决，是.NET 版本低了，安装4.7及以上版本，就可以正常运行

**Comment by Tallerrand** [comment]
> https://github.com/shadowsocks/shadowsocks-windows/releases
> 下载最新版4.1.9.2试试看
> 注意，just my sock 要用 shadowsocks（SS）客户端，不能用SSR客户端

ss和.NET版本需要保持较高版本，这个问题已经解决。
