### ISSUE TITLE
JMS 无法使用 (Just My Socks)

### ISSUE THREAD

**Issue by typist-coder** [bannedbook/fanqiang#444]
![图片.png](https://i.loli.net/2020/02/09/5nYy2ejcIWP4m6s.png)

如图，配置都是直接用的官网上的专属QR-Code导入，网址已经ping过可用，小飞机也变蓝了(Shadowsocks)，就是没有办法上网站，开的全局模式，Firefox和Chrome都已经尝试过了，服务器加了个高可用。不知道哪里出了问题。

**Comment by typist-coder** [comment]
P.S. 链接是从[JMS教程](https://github.com/killgcd/justmysocks)点击过来的

**Comment by bannedbook** [comment]
给官方发贴反应一下，这不应该啊
https://justmysocks2.net/members/submitticket.php?step=2&deptid=1

**Comment by bannedbook** [comment]
试试看不要高可用性，一个一个选中测试一下。
其中有一个是需要  插件 的，没有插件连不了

**Comment by bannedbook** [comment]
试试看不要高可用性，一个一个选中挨个的测试一下。
其中有一个是需要 插件 的，没有插件连不了

**Comment by bannedbook** [comment]
注意：近日有个别网友反馈服务不稳定，个别的购买后连不上，可能跟因掩盖瘟疫信息加重封锁有关，如果购买后试用不满意，可申请退款：[Just My Socks 怎么退款（退款条件）](https://github.com/killgcd/justmysocks/blob/master/jmstk.md)

**Comment by typist-coder** [comment]
@bannedbook 已经装了插件配置好了，还是不可以（用的是bing混淆）等明天早上用户少一点再试试看，非常感谢

**Comment by typist-coder** [comment]
@bannedbook 已经测试过了，还是用不了，本来是因为自建的SS垮了所以才考虑的，再试一下自建v2ray什么的之后再不行就购买成品了，非常感谢，不过JMS还是先挂着，现在离退款期限还有一段时间，定期测试一下。
