### ISSUE TITLE
v2ray安装后命令找不到

### ISSUE THREAD

**Issue by Fishbaptism** [bannedbook/fanqiang#451]
bash <(curl -L -s https://install.direct/go.sh)运行后，显示v2ray: command not found。请问怎么解决

**Comment by Fishbaptism** [comment]
再装一遍说我已安装，但是命令还是找不到

**Comment by bannedbook** [comment]
/usr/bin/v2ray/v2ray -test -config /etc/v2ray/config.json

**Comment by Fishbaptism** [comment]
root@vultr:~# /usr/bin/v2ray/v2ray -test -config /etc/v2ray/config.json
V2Ray 4.22.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13.5 linux/amd64)
A unified platform for anti-censorship.
Configuration OK.
root@vultr:~# v2ray
-bash: v2ray: command not found

**Comment by bannedbook** [comment]
不要直接打v2ray
控制 V2Ray 的运行：
service v2ray restart | force-reload  |start|stop|status|reload 
比如重启
service v2ray restart

**Comment by Fishbaptism** [comment]
好的，就是我不能用它的界面？只能用命令？

**Comment by bannedbook** [comment]
好像 没有界面啦

**Comment by Fishbaptism** [comment]
Ok，非常感谢。我还说官方怎么配了中文界面，这么良心
