### ISSUE TITLE
免费是好的，但是我们翻墙出去并不是为了看某党的丑闻，所以我不太喜欢这种翻墙软件

### ISSUE THREAD

**Issue by gongdadiao** [bannedbook/fanqiang#457]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？

**Comment by bannedbook** [comment]
关掉不想看的页面，去看想看到页面即可

**Comment by mobeyond** [comment]
> 关掉不想看的页面，去看想看到页面即可
 Why not CLOSE shithole issues like this? They just occupied it and distract your attention, as a job. Only thinking mind with meaningful points deserves a conversation or debate.
