### ISSUE TITLE
Vultr购买不成功

### ISSUE THREAD

**Issue by style456** [bannedbook/fanqiang#459]
我登录vultr后，左边没有出现教程中的Servers一栏，而且再付款上面出现Server Hostname & Label，点击deploy now没反应，这是怎么回事呢

**Comment by bannedbook** [comment]
改名字了，现在叫 Products 了，Products 就相当于教程里提到的servers

**Comment by bannedbook** [comment]
Server Hostname & Label ，填好了吗
如果 点击deploy now没反应，页面上是否有什么提示
如果不行的话，多点几下

**Comment by style-tech** [comment]
请问Server Hostname & Labe怎么填呢?如何找到服务器主机名和标签呢

**Comment by bannedbook** [comment]
这个随便填几个英文字母，比如：
myvps
