### ISSUE TITLE
按教程搭建shadowscokes无法访问

### ISSUE THREAD

**Issue by markses** [bannedbook/fanqiang#463]
自己买的服务器，也是按照《自建Shadowsocks服务器简明教程》一步步搭建的，可是最终就是无法访问外网。ping了ip，没有被墙

**Comment by bannedbook** [comment]
在vps上执行命令检查下配置文件：
 /usr/bin/v2ray/v2ray -test -config /etc/v2ray/config.json
有什么输出？

**Comment by markses** [comment]
> 在vps上执行命令检查下配置文件：
> /usr/bin/v2ray/v2ray -test -config /etc/v2ray/config.json
> 有什么输出？

现在可以了，就是用其他浏览器可以访问外网，但google却不可以，，google安装了谷歌访问助手，后来把他停用了也不行

**Comment by bannedbook** [comment]
把服务器配置文件里面的：
```
    "rules": [
       {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked"
      }
    ]
```
这几行删掉，然后保存，重启v2ray
service v2ray restart

**Comment by markses** [comment]
> 把服务器配置文件里面的：
> 
> ```
>     "rules": [
>        {
>         "type": "field",
>         "ip": [
>           "geoip:private"
>         ],
>         "outboundTag": "blocked"
>       }
>     ]
> ```
> 
> 这几行删除掉，然后保存，重启v2ray
> service v2ray restart
嗯嗯 可以了 我直接把配置文件里的“google.com”给删了

**Comment by bannedbook** [comment]
配上文件里怎么会有 google.com ，是自己加大吗

**Comment by markses** [comment]
不是，是教程上自带的，就是那个shadowscokes简明教程里的

**Comment by bannedbook** [comment]
不会哦，教程里好像没有提到 google.com 
是 https://github.com/bannedbook/fanqiang/blob/master/v2ss/V2ray%E5%AE%98%E6%96%B9%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC.md
这个脚本安装完，里面默认就有 google.com 的配置吗？

**Comment by markses** [comment]
https://github.com/bannedbook/fanqiang/blob/master/v2ss/%E8%87%AA%E5%BB%BAShadowsocks%E6%9C%8D%E5%8A%A1%E5%99%A8%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B.md
给出的config.json配置文件里就有的

**Comment by bannedbook** [comment]
哦，不好意思，看到了。
但是，如果完全按这个配置文件的话，应该访问google.com 是没问题的呀。
就是因为默认配置访问google有时有问题，才加了这个
```
 {
        "domain": [
          "google.com",
          "apple.com",
          "oppomobile.com"
        ],
        "type": "field",
        "outboundTag": "allowed"
      },
···
注意，
这里也加了一行        "tag": "allowed" ，2个地方需要配合
"outbounds": [
    {
      "protocol": "freedom",
      "settings": {},
      "tag": "allowed"
    },

**Comment by markses** [comment]
我就是去了那个google.com 谷歌浏览器才能访问外网的，之前只能用其他浏览器访问，可能是我谷歌浏览器装了些别的东西才出了这个问题的把

**Comment by markses** [comment]
能ping通主机地址，但是连接的时候出现这个问题：Unable to resolve host "www.google.com": No address associated with hostname,请问这是怎么回事呢

**Comment by bannedbook** [comment]
如果加那个 "geoip:private" 规则
就必须在前面加 "apple.com", 的 "outboundTag": "allowed" 规则

要么就是把 rules 整个删掉

**Comment by bannedbook** [comment]
你验证看，是否是这样，我怀疑是  "geoip:private" 规则 的bug

**Comment by bannedbook** [comment]
```
    "access": "/dev/null",
    "error": "/dev/null"
```

把上面这2行的服务器配置改成
```
    "access": "/var/log/v2a.log",
    "error": "/var/log/v2e.log"
```

然后重启v2ray 服务器 service v2ray restart 
把错误日志贴一下，注意删除自己的ip地址

**Comment by markses** [comment]
2020/03/06 03:03:36 [Warning] v2ray.com/core: V2Ray 4.22.1 started
这就是全部的日志信息，好像没有问题呀
我把那个rules规则给删除了

**Comment by bannedbook** [comment]
现在google 可以访问了吗
看日志看这个服务器上的文件
/var/log/v2a.log
输入命令：
tail -f /var/log/v2a.log

**Comment by markses** [comment]
我现在又把rules给加上去了，v2a/v2e.log均显示没有什么问题。改下了端口号，现在没有问题了。谢谢你耐心的解答！

**Comment by markses** [comment]
v2ray.com/core/proxy/shadowsocks: failed to read IV > read tcp 31125-> :36912: i/o timeout
tcp:www.googleapis.com:443 [allowed] 
safebrowsing.googleapis.com:443 [allowed]
现在可以正常访问了，输出的日志是这样

**Comment by bannedbook** [comment]
好的，可以正常访问就好了，谢谢反馈。

**Comment by fbion** [comment]
le.com
这条规则会匹配google.com
所以block了
用domain:le.com 替代

纯字符串: 当此字符串匹配目标域名中任意部分，该规则生效。比如"sina.com"可以匹配"sina.com"、"sina.com.cn"和"www.sina.com"，但不匹配"sina.cn"。

子域名 (推荐): 由"domain:"开始，余下部分是一个域名。当此域名是目标域名或其子域名时，该规则生效。例如"domain:v2ray.com"匹配"www.v2ray.com"、"v2ray.com"，但不匹配"xv2ray.com"。
