### ISSUE TITLE
1

### ISSUE THREAD

**Issue by blblbl3** [bannedbook/fanqiang#464]
1

**Comment by Alvin9999** [comment]
你用的哪个工具？浏览器有很多款工具

**Comment by blblbl3** [comment]
> 你用的哪个工具？浏览器有很多款工具

好多个都没用，ip1是35开头的ip，ip2是一个22开头的ip，不管是用哪个都是这两个ip，然后就上不去

**Comment by bannedbook** [comment]
ip1 、ip2 更新过程有没有错误？
