### ISSUE TITLE
8个软件，每次从头试到尾都不管用。半天也上不去，怎么办

### ISSUE THREAD

**Issue by ahei036** [bannedbook/fanqiang#467]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
chrome一键安装包，里面8个软件，哪个都不好使能不能给我一个稳定能用的。

**Comment by bannedbook** [comment]
是否都更新ip了
xxnet 、蓝灯试了没

**Comment by ahei036** [comment]
每次都更新，是不是我更新多了？现在有新问题了。我开机不用运行任何软件，自动就能上谷歌 了，这是怎么回事？

如何翻墙 <notifications@github.com> 于2020年3月12日周四 下午4:07写道：

**Comment by bannedbook** [comment]
是不是有什么软件，开启自动运行了。比如蓝灯

**Comment by Alvin9999** [comment]
win10系统的防火墙可能会起网络阻碍作用，可以把防火墙关闭试试看

**Comment by ahei036** [comment]
我查了没发现什么异常的进程，现在除了用chrome可以上网，其它的软件，比如百度网盘，360浏览器都不能上网，只有chrome
能上网，除了这个，其它任何软件都不好用了，都不能连接网络。微信和QQ还好用。

自由上网 <notifications@github.com> 于2020年3月15日周日 上午9:39写道：

**Comment by bannedbook** [comment]
你检查下 ie浏览器的代理设置，我觉得还是蓝灯自动启动了，蓝灯会自动设置系统代理。
你可以把蓝灯的自动启动 关掉。
