### ISSUE TITLE
配置了自建SS服务器

### ISSUE THREAD

**Issue by BQSBQS** [bannedbook/fanqiang#468]
根据说明配置好了，人在墙外要怎么看连没连上……
想问以后每次使用都需要git bash 连接ssh >>service v2ray start>>打开SS客户端吗？
人在墙外看不出成没成功，vultr的network监测好像只有配置成功那次涨了一下，后面就一直在0上浮动，SS客户端的logs也妹起伏……这是没连上的意思吗

**Comment by bannedbook** [comment]
service v2ray start 启动后，一般就不用管了
会一直处于启动状态，除非有什么异常情况，比如服务器崩溃啥的

自己用SS客户端 连接一下，连接成功后，设置浏览器代理为SS客户端的本地代理，然后
访问
https://ipcheck.bannedbook.org/
看看ip地址是不是变成了vps的ip

**Comment by BQSBQS** [comment]
搞定了，谢谢
之前先是SS的system proxy没开（。）然后浏览器代理也没设置……
