### ISSUE TITLE
chromego上IDM插件不能正常使用

### ISSUE THREAD

**Issue by Bobo-W** [bannedbook/fanqiang#471]
我用的是DAZE，运行命令行脚本进入浏览器IDM会报错，大致内容是“正在以管理员身份运行浏览器，拥有更高权限，IDM权限不够无法使用”，这是更新之后才出现的问题，之前并没有，当我又换回原来的DAZE时IDM可以正常使用，希望能修复这个问题

**Comment by bannedbook** [comment]
试试以管理员权限 运行 IDM行不行
