### ISSUE TITLE
请求添加

### ISSUE THREAD

**Issue by MysteryMulberry** [bannedbook/fanqiang#479]
https://饿饭.cc/
https://worldoor.club/
https://fuqiangpai.com/
https://adoncn.com/vultr.html
https://www.cesafe.com/vps
https://v2box.net/#/register?code=8myBaFXE
https://portal.cylink0123.icu/auth/register
https://decline.hitun.io/403/
https://www.clashcloud.net/auth/register
efanccyun.net/
bwggo.com/bwgss/all
https://ijustmysocks.com/
https://redirect.rixcloud.workers.dev/
https://dlercloud.com/auth/register
https://portal.cylink.pro/auth/register?code=m6H2
https://www.duyaoss.com/archives/2032/
https://www.amysecure.com/aff.php?aff=1
https://dlercloud.com/auth/register
https://dream.ren/
https://ssplive.pw/auth/register
https://n3ro.best/auth/register
https://dns.obitibet.com/auth/register
https://source-beat1.com/auth/register
https://conair.me/auth/register
https://www.喵帕斯.com/
doubibackup.com 104.27.175.54
https://feedx.xyz，https://feedx.net，https://docs.rsshub.app，https://getpodcast.xyz，https://feed43.com，https://rssfeed.today/weibo/，https://fraidyc.at/，http://feedsoso.com/，https://rss.mifaw.com/，https://fivefilters.org/content-only/，https://feedex.net/，https://werss.app/?utm_source=v2ex&utm_campaign=20180713，http://ctrlq.org/rss/

**Comment by bannedbook** [comment]
哪个软件
