### ISSUE TITLE
请求: 希望添加一些rss相关的可用 hosts，如下

### ISSUE THREAD

**Issue by MysteryMulberry** [bannedbook/fanqiang#480]
104.27.136.214 feedx.xyz
66.42.58.11 feedx.net
104.26.13.87 docs.rsshub.app
138.201.58.89 feedex.net
208.97.169.138 ctrlq.org
207.38.86.222 feedsoso.com
66.228.47.94 feed43.com
192.243.118.206 rss.mifaw.com
149.129.57.220 werss.app
168.235.76.45 fraidyc.at
119.28.178.53 getpodcast.xyz
208.94.117.53 fivefilters.org
104.27.144.245 rssfeed.today

**Comment by bannedbook** [comment]
https://github.com/gfwlist/gfwlist
到这里报告
