### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by OliverLai** [bannedbook/fanqiang#481]
600:gae_exception:'600:fetch gae fail' https://www.bannedbook.org/bnews/fq/?utm_source=XX-Netgae_exception:'600:fetch gae fail' https://www.bannedbook.org/bnews/fq/?utm_source=XX-Netgae_exception:'600:fetch gae fail' https://www.bannedbook.org/bnews/fq/?utm_source=XX-Net
更新至最新的版本后还是报这个错误

**Comment by bannedbook** [comment]
是哪个软件，xxnet版吗
可能需要扫描ip ，等待一段时间看看
