### ISSUE TITLE
进来看

### ISSUE THREAD

**Issue by sakura5757** [bannedbook/fanqiang#484]
为什么一连接成功就会弹出反动的新闻?
杀毒软件报警难道是无缘无故的吗?还让大家卸载杀毒软件?
readme.md最后说请随意转发?
请大家认真想想吧!

**Comment by bannedbook** [comment]
很多国产杀毒软件，比如360安全卫生、360杀毒软件、腾讯管家、金山卫士等不仅仅会起干扰作用，造成软件无法正常使用或速度变慢，它们与共匪金盾工程还有千丝万缕的关系!其实win10自带的defender就有杀毒的功能，如果还需要安全软件，可以用[推荐的杀毒软件](https://tiandixing.org/viewtopic.php?f=25&t=193535)，免费的，而且不会干扰翻墙。

**Comment by bannedbook** [comment]
注意：软件都是采用加密方式的，但为了更稳定、更安全的翻墙，建议卸载国产杀毒软件，至少翻墙时不要用它们！
