### ISSUE TITLE
V2ray + ws + tls ping可以，但访问网站极慢，墙又升级了？

### ISSUE THREAD

**Issue by magnusguo** [bannedbook/fanqiang#494]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
Ping这没问题 200多毫秒， 但iOS手机端Shadowsocks测试链路的方法有一种是连接一个网站， 则延迟一下跳到1100多 且不稳定。请问是不是V2ray + ws + tls  这方法已经不行了？

**Comment by bannedbook** [comment]
ping 的延时 和 那个测试连接的延时 是2种不同的衡量，这2个数值不能比较。一般ping值会比那个测试连接的数值小很多，这是正常的

**Comment by magnusguo** [comment]
> ping 的延时 和 那个测试连接的延时 是2种不同的衡量，这2个数值不能比较。一般ping值会比那个测试连接的数值小很多，这是正常的

好的 谢谢您，那请问最近是梯子质量都不好么？youtube都loading不出来那种，或者只能144砂纸分辨率才能播放那种？ 请教怎么看问题出在哪个环节了呢？谢谢

**Comment by Alvin9999** [comment]
一般来说，套cdn会变慢的。你可以把cdn关闭，然后再试试看，如果还慢，可以换其它加密方式。ip没有被墙，套cdn意义不是特别大。

**Comment by magnusguo** [comment]
> 一般来说，套cdn会变慢的。你可以把cdn关闭，然后再试试看，如果还慢，可以换其它传输协议。ip没有被墙，套cdn意义不是特别大。

请问啥事CDN？ 我好像并没有套cdn吧？

**Comment by Alvin9999** [comment]
@magnusguo 我看错了，tls可以关闭

**Comment by magnusguo** [comment]
> @magnusguo 我看错了，tls可以关闭

感觉链路好像也不算特别好 ping丢包率在10%几

**Comment by Alvin9999** [comment]
可以换服务器位置

**Comment by magnusguo** [comment]
> 可以换服务器位置

好的 谢谢大神 目前用的是hostwinds， 有推荐的vps么？ 他家好处是ip如果被封了可以免费换ip

**Comment by magnusguo** [comment]
> 可以换服务器位置

另外想请教一下 v2ray + ws + tls 和 Trojan 和一个好像叫brook的 哪个更稳一些？ 最近梯子不稳定 是在狂躁。。。谢谢

**Comment by bannedbook** [comment]
v2ray 似乎比 ss/ssr稳一些，brook 没有大规模测试过

**Comment by magnusguo** [comment]
> 测试

多谢多谢

> v2ray 似乎比 ss/ssr稳一些，brook 没有大规模测试过

多谢多谢， 那Trojan可以不用考虑了？

**Comment by bannedbook** [comment]
我感觉 Goflyway  似乎比较稳定

**Comment by magnusguo** [comment]
> Goflyway

又多一个新选择啊。。哈哈，不过刚才您的意思是 我这里不稳定是VPS的问题 不是被墙盯上了是么。。。

**Comment by Dabrit** [comment]
现阶段v2ray+ws+tls是最稳定安全的翻墙方式，和trojan并驾齐驱，trojan理论速度更快但是不支持反向代理，无法套接CDN，建议二选一

**Comment by ciscoxll** [comment]
recommender vpn https://shop.v2ss.bid/users/aff.php?aff=2742.

**Comment by bannedbook** [comment]
2020年6月4日公告：若干更新，增加V2rayB翻墙通道，请下载新版软件来使用。
[Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)

**Comment by FreeSlaver** [comment]
真的没撒折腾的必要，都是一路折腾过来的人。
还是用别人的机场把，便宜稳定，撒事都不用操心，<a href="https://user.by.ltd/aff.php?aff=17672">bywave</a>。
你那折腾的几个小时玩会游戏，刷会视频，学习下，它不香吗？
这个机场我18年末用到现在，当初有个套餐是80块钱250gb流量，包终生。
后面遇到3次还是几次故障，只要时间够久都会赔偿，有一次好像是赔偿了100多g。
我就白嫖到了现在，当时冲了100块，现在还有35块余额了。
专业的事情还是交给专业的人干把。
