### ISSUE TITLE
Goflyway无法观看Youtube

### ISSUE THREAD

**Issue by ygr088** [bannedbook/fanqiang#502]
这是怎么一回事昨天看清单视频还很欢的今天就不行了？

**Comment by Alvin9999** [comment]
ip1和ip2都不行？

**Comment by ygr088** [comment]
> ip1和ip2都不行？

是的。显示没有数据传输。有的时候甚至连不上去

**Comment by ygr088** [comment]
> ip1和ip2都不行？

现在没试过，之前几个小时用法X功的FG去了、、、。。。

**Comment by Alvin9999** [comment]
集成版有10多款不同的工具，可以切换使用的哦

**Comment by ygr088** [comment]
> 集成版有10多款不同的工具，可以切换使用的哦

Em主要是我这边速度很慢，还经常掉，只有Goflyway是还算可以的

**Comment by ygr088** [comment]
不过这东西有时候好有时候不好啦。我刚用的时候还可以的。尽管比较慢，但是不管怎么样，还是要感谢你们！加油！
