### ISSUE TITLE
关于ChromeGo使用之后 其他软件连不上网问题

### ISSUE THREAD

**Issue by DeusSapiens** [bannedbook/fanqiang#505]
您好，我在使用了ChromeGo一段时间之后，ChromeGo还能正常fq，但其他的许多软件都不知道为什么连不上网了，包括以下软件及功能：
1. QQ的文件，空间功能
2. Chrome的无痕模式功能
3. Microsoft Edge
4. Onenote的同步功能
请问这是什么原因造成的呢？

**Comment by bannedbook** [comment]
是不是 有 翻墙软件 自动启动了，比如蓝灯？或塞风

**Comment by bannedbook** [comment]
蓝灯 塞风 会设置系统全局代理，不用了就退出。如果有问题，检查ie代理设置，是不是软件退出时代理没取消

**Comment by DeusSapiens** [comment]
> 蓝灯 塞风 会设置系统全局代理，不用了就退出。如果有问题，检查ie代理设置，是不是软件退出时代理没取消

十分感谢！因为重启之后也一样，所以查了一下ie代理设置来着
果然代理服务器是这个样子的
![image](https://user-images.githubusercontent.com/64881388/81170862-fb92f000-8fcd-11ea-8910-66c1df1b17e1.png)
所以说出现这种情况手动关掉代理就ok了吧？

**Comment by bannedbook** [comment]
对，把这个取消就行了。
