### ISSUE TITLE
又出售翻墙账号的大佬吗？我要买，我做外贸行业的啊

### ISSUE THREAD

**Issue by mikeluochengwei** [bannedbook/fanqiang#513]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？

**Comment by bannedbook** [comment]
https://github.com/killgcd/justmysocks/blob/master/README.md

**Comment by mikeluochengwei** [comment]
有没有  大佬自建的梯子呀

**Comment by bannedbook** [comment]
你可以自己建呀
[V2Ray之TLS+WebSocket翻墙方法](https://github.com/bannedbook/fanqiang/blob/master/v2ss/V2Ray%E4%B9%8BTLS%2BWebSocket%E7%BF%BB%E5%A2%99%E6%96%B9%E6%B3%95.md)

**Comment by mikeluochengwei** [comment]
> 你可以自己建呀
> [V2Ray之TLS+WebSocket翻墙方法](https://github.com/bannedbook/fanqiang/blob/master/v2ss/V2Ray%E4%B9%8BTLS%2BWebSocket%E7%BF%BB%E5%A2%99%E6%96%B9%E6%B3%95.md)

可以加您的联系方式吗，我想直接向个人购买账号，不想去某个网站上选套餐这些太麻烦了

**Comment by bannedbook** [comment]
抱歉，我们暂且没有这项业务

**Comment by ssrshare** [comment]
有的 加我吧 https://t.me/xiaowei51

**Comment by NXc9H7EC** [comment]
海归服务器:https://rs.aboutai.xyz
