### ISSUE TITLE
不能用了

### ISSUE THREAD

**Issue by P-King999** [bannedbook/fanqiang#525]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
昨天还用了 XX 和v2ray 今天都不行了

**Comment by bannedbook** [comment]
v2ray 更新ip 了吗

**Comment by TomCrui** [comment]
都是这样，自从开两会，我的就一直不能用了。

**Comment by TomCrui** [comment]
[Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://www.free6666.net/f4be5506/):  > dial tcp 104.16.55.38:443: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by P-King999** [comment]
😂是吗，那等几天吧，看看自己会好不



---原始邮件---
发件人: "李毅杰"<notifications@github.com&gt;
发送时间: 2020年5月28日(周四) 下午3:31
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"P-King"<2792181963@qq.com&gt;;
主题: Re: [bannedbook/fanqiang] 不能用了 (#525)




 
都是这样，自从开两会，我的就一直不能用了。

**Comment by bannedbook** [comment]
更新ip，你没更新ip

**Comment by TomCrui** [comment]
> 更新ip，你没更新ip

我更新了，在启动脚本的时候。IP1和IP2都试过，没有用。以前都可以的。

**Comment by P-King999** [comment]
我也是，更新了没有用



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "李毅杰"<notifications@github.com&gt;; 
发送时间: 2020年5月28日(星期四) 下午3:40
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;; 
抄送: "pking"<2792181963@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [bannedbook/fanqiang] 不能用了 (#525)





  
更新ip，你没更新ip
  
我更新了，在启动脚本的时候。IP1和IP2都试过，没有用。以前都可以的。

**Comment by bannedbook** [comment]
更新成功，还是没成功，更新界面会有显示啊
你这个 www.free6666.net 是老的失效的服务器

**Comment by TomCrui** [comment]
按enter以后





再打开V2ray





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"如何翻墙"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 下午4:15
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"2393999659"<2393999659@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 不能用了 (#525)





 
更新成功，还是没成功，更新界面会有显示啊
 你这个 www.free6666.net 是老的失效的服务器

**Comment by bannedbook** [comment]
看不见，空白

**Comment by TomCrui** [comment]
> 看不见，空白

errrr.....这图片显示不出来

**Comment by TomCrui** [comment]
更新提示成功。至于服务器的问题，我不是很清楚，这个ChromeGo翻墙包我4天前更新到本地了，所以应该是最新的。

**Comment by TomCrui** [comment]
--2020-05-28 17:03:50--  https://gitlab.com/free9999/ipupdate/-/raw/master/v2rayN/guiNConfig.json
Resolving gitlab.com (gitlab.com)... 172.65.251.78
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1221 (1.2K) [text/plain]
Saving to: 'guiNConfig.json'

100%[==============================================================================>] 1,221       --.-K/s   in 0s

2020-05-28 17:03:52 (8.07 MB/s) - 'guiNConfig.json' saved [1221/1221]

已复制         1 个文件。

已更新完成最新可用v2ray配置,请按回车键或空格键启动程序！

**Comment by bannedbook** [comment]
v2ray 实在不行，试试别的通道吧

**Comment by bannedbook** [comment]
https://github.com/fqnews/bnews/blob/master/readme.md
这个可以临时救救急

**Comment by TomCrui** [comment]
其他的也不行

**Comment by TomCrui** [comment]
我觉得是IP的问题，因为貌似其他的翻墙工具更新的IP和V2ray是一样的，所以V2ray用不了，其他的也用不了。

**Comment by bannedbook** [comment]
如果有安卓手机，可以用这个app
https://github.com/bannedbook/fanqiang/wiki/%E5%AE%89%E5%8D%93%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6#ssvpn

**Comment by TomCrui** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"如何翻墙"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月28日(星期四) 下午5:27
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"2393999659"<2393999659@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 不能用了 (#525)





 
如果有安卓手机，可以用这个app
 https://github.com/bannedbook/fanqiang/wiki/%E5%AE%89%E5%8D%93%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6#ssvpn
