### ISSUE TITLE
大佬好久更新阿，不能用了

### ISSUE THREAD

**Issue by mr537** [bannedbook/fanqiang#527]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？

**Comment by bannedbook** [comment]
v2ray 更新ip 了吗

**Comment by 237615742** [comment]
我今天早上还可以用，中午就不行了，每个都连不上。
v2ray ：

> 2020/05/28 18:44:18 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: failed to find an available destination > v2ray.com/core/common/retry: [v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://tr8.free6666.net/c3e707df/):  > read tcp 192.168.31.146:57075->104.19.195.10:443: wsarecv: An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://tr8.free6666.net/c3e707df/):  > read tcp 192.168.31.146:57076->104.19.195.10:443: wsarecv: An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://tr8.free6666.net/c3e707df/):  > read tcp 192.168.31.146:57077->104.19.195.10:443: wsarecv: An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://tr8.free6666.net/c3e707df/):  > read tcp 192.168.31.146:57078->104.19.195.10:443: wsarecv: An existing connection was forcibly closed by the remote host. v2ray.com/core/transport/internet/websocket: failed to dial WebSocket > v2ray.com/core/transport/internet/websocket: failed to dial to (wss://tr8.free6666.net/c3e707df/):  > dial tcp 104.19.195.10:443: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

XX-Net：

> 2020-05-28 18:50:09.831 [gae_proxy][DEBUG] report_connect_fail:142.250.8.189
2020-05-28 18:50:09.832 [gae_proxy][DEBUG] connect 142.250.8.189 fail:error("conn fail, sni:None, top:p1y5y54pp1iyp1-006.appspot.com e:timeout('timed out',)",)
2020-05-28 18:50:10.865 [gae_proxy][WARNING] 59.18.30.18 h1_request:Exception('time out',) inactive_time:61 task.timeout:60
2020-05-28 18:50:10.870 [gae_proxy][WARNING] 59.18.30.18 trace: 0:connect, 205:init, 1099:request,:60007, processed:0, transfered:0, sni:None
2020-05-28 18:50:10.870 [gae_proxy][WARNING] retry_task_cb: GET xxnet-update.appspot.com/update.json?uuid=60038d55-cb3d-4f2c-b4a3-d7ca350c5a3e&version=3.15.9&platform=Windows-10-10.0.18362
2020-05-28 18:50:10.871 [gae_proxy][WARNING] GET xxnet-update.appspot.com/update.json?uuid=60038d55-cb3d-4f2c-b4a3-d7ca350c5a3e&version=3.15.9&platform=Windows-10-10.0.18362 response_fail:retry timeout:77
2020-05-28 18:50:10.871 [gae_proxy][DEBUG] 59.18.30.18 worker close:down fail
2020-05-28 18:50:14.833 [gae_proxy][WARNING] not enough ip

Goflyway:

> 2020-05-28 18:51:47.892 CST,main.go:267, INFO ,goflyway 181021015134
2020-05-28 18:51:47.969 CST,main.go:436, INFO ,Upstream config: cf://www.free99999.com:8880
2020-05-28 18:51:47.969 CST,main.go:416, INFO ,Client b76c393 started: you->127.0.0.1:8100->cloudflare->www.free99999.com:8880
2020-05-28 18:51:47.969 CST,main.go:412, INFO ,Web console started at 127.0.0.1:8110
2020-05-28 18:51:48.169 CST,client.go:394, ERROR ,"Dial failed: dial, lookup www.free99999.com: no such host"
2020-05-28 18:51:48.223 CST,client.go:394, ERROR ,"Dial failed: dial, lookup www.free99999.com: no such host"

更新了ip一样连不上，希望能早日修复。

**Comment by bannedbook** [comment]
试试这个
https://github.com/bannedbook/fanqiang/wiki/%E5%AE%89%E5%8D%93%E7%BF%BB%E5%A2%99-%E7%A6%81%E9%97%BB%E6%B5%8F%E8%A7%88%E5%99%A8

**Comment by 237615742** [comment]
> 试试这个
> https://github.com/bannedbook/fanqiang/wiki/%E5%AE%89%E5%8D%93%E7%BF%BB%E5%A2%99-%E7%A6%81%E9%97%BB%E6%B5%8F%E8%A7%88%E5%99%A8

没有window平台的吗？

**Comment by bannedbook** [comment]
v2ray下载这个文件，替换一下同名文件
https://raw.githubusercontent.com/bannedbook/fanqiang/master/ChromeGo/v2ray/guiNConfig.json

**Comment by mr537** [comment]
> v2ray下载这个文件，替换一下同名文件
> https://raw.githubusercontent.com/bannedbook/fanqiang/master/ChromeGo/v2ray/guiNConfig.json

打不开欸

**Comment by mr537** [comment]
> > v2ray下载这个文件，替换一下同名文件
> > https://raw.githubusercontent.com/bannedbook/fanqiang/master/ChromeGo/v2ray/guiNConfig.json
> 
> 打不开欸

我也是 一样的情况 更新ip也不行了  就今天用谷歌浏览器查阅资料的时候

**Comment by bannedbook** [comment]
```
{
  "inbound": [
    {
      "localPort": 10808,
      "protocol": "socks",
      "udpEnabled": false,
      "sniffingEnabled": false
    }
  ],
  "logEnabled": false,
  "loglevel": "warning",
  "index": 0,
  "vmess": [
    {
      "configVersion": 2,
      "address": "v16u.eurodns.cf",
      "port": 80,
      "id": "930ab934-c00e-403a-818c-171804966a22",
      "alterId": 2,
      "security": "auto",
      "network": "ws",
      "remarks": "v16u",
      "headerType": "none",
      "requestHost": "",
      "path": "/R3rhEuAHBZ",
      "streamSecurity": "",
      "allowInsecure": "",
      "configType": 1,
      "testResult": "718ms",
      "subid": ""
    }
  ],
  "muxEnabled": true,
  "domainStrategy": "IPIfNonMatch",
  "routingMode": "0",
  "useragent": [],
  "userdirect": [],
  "userblock": [],
  "kcpItem": {
    "mtu": 1350,
    "tti": 50,
    "uplinkCapacity": 12,
    "downlinkCapacity": 100,
    "congestion": false,
    "readBufferSize": 2,
    "writeBufferSize": 2
  },
  "sysAgentEnabled": false,
  "listenerType": 0,
  "urlGFWList": "",
  "allowLANConn": false,
  "remoteDNS": "",
  "subItem": null,
  "uiItem": {
    "mainQRCodeWidth": 600
  }
}
```
自己保存替换吧

**Comment by 237615742** [comment]
感觉应该不是更不更新这个文件的原因！从cmd更新ip，从网页复制到config.json，重新下载CG一样找不到host，从昨天中午开始我知道的大多数工具都用不了，要么就是连上了一会马上就断掉。是不是防火墙加强了？

**Comment by bannedbook** [comment]
把上面的文件，用记事本保存替换 guiNConfig.json
如果还不行，再来反馈

**Comment by 237615742** [comment]
可以用了，谢谢！

**Comment by cc332** [comment]
为什么我替换了guiNConfig.json文件还不行啊？昨天还用的好好的

**Comment by bannedbook** [comment]
报什么错？
注意完整拷贝，不要错
用记事本
不要用word之类的

**Comment by cc332** [comment]
大佬得空还是更新下吧，造福劳苦大众

**Comment by cc332** [comment]
记事本，完整的。怎么查看报什么错？

**Comment by bannedbook** [comment]
v2rayN 的界面下边，有个日志窗口

**Comment by cc332** [comment]
谢谢大佬，已经成功了！感谢能让我们普通人看到外面的世界。

这次的问题应该是防火墙的原因吧？另外三个免费的V2RAY也是不能用了，貌似全体挂了

**Comment by Alvin9999** [comment]
已更新

**Comment by TomCrui** [comment]
> 已更新

其实我想问从ChromeGo下载点下载的翻墙包是最新的吗，我以前都是用这种方式更新的，但上次作者和我说我的服务器用的还是www.free6666.net的旧版服务器，我就有点怀疑自己下载的ChromeGo是不是最新的？

**Comment by Alvin9999** [comment]
用ip更新文件就可以同步到最新的服务器了

**Comment by Ripo-za** [comment]
> ```
> {
>   "inbound": [
>     {
>       "localPort": 10808,
>       "protocol": "socks",
>       "udpEnabled": false,
>       "sniffingEnabled": false
>     }
>   ],
>   "logEnabled": false,
>   "loglevel": "warning",
>   "index": 0,
>   "vmess": [
>     {
>       "configVersion": 2,
>       "address": "v5u.eurodns.cf",
>       "port": 80,
>       "id": "d378a896-ccaf-4e57-bf13-fd2116da9c61",
>       "alterId": 64,
>       "security": "auto",
>       "network": "ws",
>       "remarks": "v5u",
>       "headerType": "none",
>       "requestHost": "",
>       "path": "/sdudyenglish",
>       "streamSecurity": "",
>       "allowInsecure": "",
>       "configType": 1,
>       "testResult": "<0.26 M/s",
>       "subid": ""
>     }
>   ],
>   "muxEnabled": true,
>   "domainStrategy": "IPIfNonMatch",
>   "routingMode": "0",
>   "useragent": [],
>   "userdirect": [],
>   "userblock": [],
>   "kcpItem": {
>     "mtu": 1350,
>     "tti": 50,
>     "uplinkCapacity": 12,
>     "downlinkCapacity": 100,
>     "congestion": false,
>     "readBufferSize": 2,
>     "writeBufferSize": 2
>   },
>   "sysAgentEnabled": false,
>   "listenerType": 0,
>   "urlGFWList": "",
>   "allowLANConn": false,
>   "remoteDNS": "",
>   "subItem": null,
>   "uiItem": {
>     "mainQRCodeWidth": 600
>   }
> }
> ```
> 
> 记事本保存替换 guiNConfig.json
> 注意完整拷贝，不要错
> 用记事本
> 不要用word之类的



> 大佬得空还是更新下吧，造福劳苦大众

你用第一个啊，goflyway那个
