### ISSUE TITLE
火狐和铬的翻墙软件都不能用

### ISSUE THREAD

**Issue by rrq0514** [bannedbook/fanqiang#531]
安装的WIN10系统、Chrome翻墙无法打开Chrome浏览器、火狐浏览器可以打开i、但无法翻墙、请大佬帮忙……

**Comment by bannedbook** [comment]
试试v2ray，先更新ip

**Comment by zhyz18csy** [comment]
今天怎么什么都无法翻过去？更新IP什么的都不行

**Comment by zhyz18csy** [comment]
https://git.io/fanqiang 而且这个网站国内好像被禁了，说是存在违法信息，不给访问

**Comment by zhyz18csy** [comment]
主页被禁用了，其他副页不会被禁用吧？

**Comment by zhyz18csy** [comment]
主页被禁用了，其他副页不会被禁用吧？

**Comment by zhyz18csy** [comment]
主要就是说无法翻墙出去以及无法登陆Github主页

**Comment by zhyz18csy** [comment]
Github主页说的是上面的网页链接

**Comment by foho8080** [comment]
@zhyz18csy https://git.io/fanqiang  這個不fq都可以訪問

**Comment by bannedbook** [comment]
> https://git.io/fanqiang 而且这个网站国内好像被禁了，说是存在违法信息，不给访问

不用使用国内浏览器，用chrome浏览器
https://github.com/bannedbook/fanqiang/wiki/Chrome%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%8B%E8%BD%BD

**Comment by bannedbook** [comment]
ip更新后，v2ray 可用

**Comment by zhyz18csy** [comment]
不好意思，白天很忙，无法回复消息，只好晚上回复了。
现在我只能晚上使用，7点多的时候我打开v2ray都能够更新，一到晚上8点多不知怎么就更新不了了，retry二十次以失败告终，总之无法fq了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 上午9:09
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
ip更新后，v2ray 可用

**Comment by bannedbook** [comment]
白天更新后，晚上用就好了

**Comment by zhyz18csy** [comment]
白天更新，晚上使用？但是好像晚上更新有点慢，retry16次，以前晚上好像也没有这么慢。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 晚上8:27
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
白天更新后，晚上用就好了

**Comment by bannedbook** [comment]
并不是每次使用都需要更新ip，ip失效了才更新。
平时使用跳过ip更新，连不上服务器时再更新。

**Comment by zhyz18csy** [comment]
我刚刚更新了V2ray的配置，现在也打不开fq后的网站（以前更新以后直接打开都没有问题的），不知道是不是最近端口出现了什么问题？是不是说现在更新要等个一天半天才能正常使用？
另外，GitHub不fq的话也要用谷歌才能访问了，看来dalu管控加强了，现在不关掉360运行一定会出错（以前不会，可能现在360更新了）
最后，现在管控加强了，我们是否要注意更多事项了？

**Comment by zhyz18csy** [comment]
刚才的邮件中我忘了问一个问题：fq软件更新了，我是否要重新上去下载新版来使用？不下载会不会影响使用？

**Comment by bannedbook** [comment]
大陆安全类软件都是监控软件，大陆浏览器都是封锁帮凶。
尽量避免这些软件，否则一点隐私都没有。

**Comment by bannedbook** [comment]
正常应该更新后即可食用。一般不需要重新下载。

**Comment by zhyz18csy** [comment]
也就是说百度，360浏览器都是监控软件喽，而且这些软件会封锁GitHub等网站，对吧？那以后我还是少些使用这些浏览器登陆吧。
那我要是使用了谷歌上网助手登陆谷歌会怎样？谷歌上网助手算不算大陆监控软件？这样子登陆谷歌算不算fq，算不算被大陆监控呢？（只有使用V2ray等程序f过去才算真的fq）
我还有许多问题没搞懂，只好辛苦您解答了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 晚上9:59
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
大陆安全类软件都是监控软件，大陆浏览器都是封锁帮凶。
 尽量避免这些软件，否则一点隐私都没有。

**Comment by zhyz18csy** [comment]
那么这样，我今晚先更新V2ray（不需要下载的话），看看明天是否能够使用（我觉得今晚是不可能再使用了）。
不出意外的话，明天晚上我应该能成功操作了吧？（最近的fq软件没有之前那么给力了）
而且最近的软件更新常常会失败，这在之前没有出现过啊，这是怎么回事？
又得麻烦您了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 晚上10:06
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
正常应该更新后即可用。一般不需要重新下载。

**Comment by bannedbook** [comment]
更新ip后，如果能用的话，马上就能用。
是你自己说白天能更新，晚上更新不了，所以我才告诉你白天更好，晚上用。

**Comment by bannedbook** [comment]
这里发了一下网络上搜集的一些免费v2ray账号，可以试试看
https://github.com/bannedbook/fanqiang/issues/530

**Comment by zhyz18csy** [comment]
抱歉！我的话语可能表达的不准确，给您造成误会了。
其实我是想说：我现在晚上更新ip可以成功，但是就是软件运行后它无法顺利跳转到jww那个首界面，总是连接超时。那我想问问您这是怎么回事？
又给您增加工作量了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 下午4:49
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
更新ip后，如果能用的话，马上就能用。
 是你自己说白天能更新，晚上更新不了，所以我才告诉你白天更好，晚上用。

**Comment by bannedbook** [comment]
先 3.v2ray翻墙.cmd 启动，如果打不开jww页面，刷新几次，还不行的话。

用上面 #530  里面我发的免费 v2ray 账号，导入v2rayN，批量校验，把最快的服务器设为活动服务器，然后再刷新页面

**Comment by zhyz18csy** [comment]
最近软件的连接是不是太慢了（服务器是不是响应超时了？）？我等了1个小时，jww（首页）才打开！

**Comment by bannedbook** [comment]
用上面 #530 里面我发的免费 v2ray 账号，导入v2rayN，批量校验，把最快的服务器设为活动服务器，然后再刷新页面

**Comment by zhyz18csy** [comment]
十分弱智的问一下：v2rayN在哪里？怎么导入？（也行找到v2rayN我就会了）

**Comment by bannedbook** [comment]
3.v2ray翻墙.cmd 启动
这个启动后，就会启动v2rayn了，windows 托盘区 找 v 字图标

**Comment by zhyz18csy** [comment]
校验是不是测试服务器延迟、此时服务器速度（我觉得没有其他按键了）？刷新就是重启服务（不太可能有其他键）吧？但是测试的两个按键是用不了，它说此功能要依赖HTTP全局代理，请先设置正确。

**Comment by bannedbook** [comment]
在主界面，点右键

**Comment by zhyz18csy** [comment]
？在服务器列表里面点右键只会出现批量导入URL、设为活动服务器等啊？看了十遍了也没有找到校验这两个字……




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 晚上8:55
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
在主界面，点右键

**Comment by bannedbook** [comment]
#530
看这里，已经说的很清楚了
测试服务器真连接延迟

**Comment by bannedbook** [comment]
2020年6月4日公告：若干更新，增加V2rayB翻墙通道，请下载新版软件来使用。
[Chrome一键翻墙包](https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85)

**Comment by foho8080** [comment]
@bannedbook  几时更新火狐一键翻墙包

**Comment by bannedbook** [comment]
已经更新了

**Comment by zhyz18csy** [comment]
不好意思，我可能让您误解了！其实是我使用V2rayN的时候遇到了一些问题，一下子没想到怎么整，但后来自己又解决了。（虽然是服务器延迟，我还是没翻过去）
我昨天晚上比较忙，也没有时间回复您，给您添加工作量了，抱歉！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月4日(星期四) 上午7:16
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
#530
 看这里，已经说的很清楚了
 测试服务器真连接延迟

**Comment by bannedbook** [comment]
使用电脑，软件，就是自己要多动手，当我告诉你批量校验的时候
那批量测试延迟，是不是一种批量校验，包括测试服务器延迟ping tcping 测试服务器速度等等，都是属于批量校验的范畴么。而且，另一个帖子里明确提到了 测试服务器真连接延迟

**Comment by Alvin9999** [comment]
刚更新了SSR，可以再运行一下ip更新文件

**Comment by zhyz18csy** [comment]
SSR很快，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 晚上6:47
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
刚更新了SSR，可以再运行一下ip更新文件

**Comment by zhyz18csy** [comment]
是的，我这方面太欠缺了（总是被我的一些朋友吊打）。自己还是得去多摸索一下，理解一下这些功能到底做什么的。
自己对电脑的了解太少了，得加强啊，毕竟未来都要长期使用的！
感谢你们这几天抢修fq软件，这样大家都能用了；我不仅代表自己，也替所有人感谢你们！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 晚上6:43
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
使用电脑，软件，就是自己要多动手，当我告诉你批量校验的时候
 那批量测试延迟，是不是一种批量校验，包括测试服务器延迟ping tcping 测试服务器速度等等，都是属于批量校验的范畴么。而且，另一个帖子里明确提到了 测试服务器真连接延迟

**Comment by Alvin9999** [comment]
> 是的，我这方面太欠缺了（总是被我的一些朋友吊打）。自己还是得去多摸索一下，理解一下这些功能到底做什么的。 自己对电脑的了解太少了，得加强啊，毕竟未来都要长期使用的！ 感谢你们这几天抢修fq软件，这样大家都能用了；我不仅代表自己，也替所有人感谢你们！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"foho8080"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月5日(星期五) 晚上6:43 收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;; 抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531) 使用电脑，软件，就是自己要多动手，当我告诉你批量校验的时候 那批量测试延迟，是不是一种批量校验，包括测试服务器延迟ping tcping 测试服务器速度等等，都是属于批量校验的范畴么。而且，另一个帖子里明确提到了 测试服务器真连接延迟 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

没关系，慢慢来。

**Comment by zhyz18csy** [comment]
谢谢您的鼓励！我会继续努力探索的，加油！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 晚上7:15
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)

 
没关系，慢慢来。

**Comment by zhyz18csy** [comment]
今天又发现fq速度非常慢（当然我不是什么时候都在用，隔几天需要会使用），好久好久才能打开一点点主界面，里面的内容更别说能不能看了。
V2rayB全部都显示无法连接……更新也不行；其他软件速度也很慢，几乎用不了。
又得麻烦您来解答一下这些疑难杂症了！

**Comment by zhyz18csy** [comment]
我不理解为什么fq速度现在一瞬间又快起来了？？？？？
又什么都能加载了，很好用了

**Comment by zhyz18csy** [comment]
高兴过早了，还没用上10分钟，fq软件连接又延迟了！
不知道这些软件到底有什么BUG，那就只能烦请您来解答一下了！

**Comment by bannedbook** [comment]
用最新 V2rayB翻墙通道试试看
---注意注意注意，V2rayB翻墙通道的服务器收集自互联网免费分享，不是本库直接提供！！！---

1、启动后如果Chrome页面打不开，点桌面右下角托盘区蓝色V图标，打开V2rayN软件；

2、然后在V2rayN主界面，按Ctrl+A键选中所有服务器，然后点右键，再点：测试服务器真连接延迟（多选）

3、测试完毕后，测试结果为数字的是可用服务器，测试结果数字越小越快,点测试结果列头可排序;

4、鼠标点击选中一个可用服务器，按回车键激活，然后回到已打开的chrome浏览器刷新页面；如果还打不开页面可从最快到最慢的服务器挨个尝试；

5、如果第4步挨个测试所有可用服务器都不行，那么点V2rayN左上角“订阅/更新订阅”，然后重复第2-4步。

**Comment by bannedbook** [comment]
另外，目前一些翻墙通道 的 ip1 和 ip2 是不同节点，可以分别尝试

**Comment by zhyz18csy** [comment]
这些我肯定会尝试的，谢谢提醒（我不想再麻烦您提醒更多）！
其实我就是发现连接可能出现不稳定的情况而已，可能卡了十几分钟，但最后总能使用。一点小问题，应该没事




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"foho8080"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月17日(星期三) 上午10:35
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
用最新 V2rayB翻墙通道试试看
 ---注意注意注意，V2rayB翻墙通道的服务器收集自互联网免费分享，不是本库直接提供！！！---
 
1、启动后如果Chrome页面打不开，点桌面右下角托盘区蓝色V图标，打开V2rayN软件；
 
2、然后在V2rayN主界面，按Ctrl+A键选中所有服务器，然后点右键，再点：测试服务器真连接延迟（多选）
 
3、测试完毕后，测试结果为数字的是可用服务器，测试结果数字越小越快,点测试结果列头可排序;
 
4、鼠标点击选中一个可用服务器，按回车键激活，然后回到已打开的chrome浏览器刷新页面；如果还打不开页面可从最快到最慢的服务器挨个尝试；
 
5、如果第4步挨个测试所有可用服务器都不行，那么点V2rayN左上角“订阅/更新订阅”，然后重复第2-4步。

**Comment by zhyz18csy** [comment]
距离最后一次fq软件的更新过了两个月了，这两个月fq软件使用的十分顺利，但是最近软件似乎又有点慢了（又需要我等待它更新ip很久），所以，能不能麻烦你们抽空再去检查更新一下？谢谢！

**Comment by killgcd** [comment]
更新了

**Comment by zhyz18csy** [comment]
昨天收到邮件后我打开软件，确实比较通畅了，但是为什么今天又会卡呢？能否麻烦你们再看一下？谢谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bannedbook/fanqiang"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月18日(星期二) 晚上7:18
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
更新了

**Comment by Alvin9999** [comment]
@zhyz18csy 里面有10多种工具，而且每款工具的ip更新地址有多个，几乎都是不同的ip，请问都尝试了吗

**Comment by Alvin9999** [comment]
@zhyz18csy 如果不知道怎么选择，可以推荐一下，优先尝试v2ray ip1和ip2，ss-kcptun，brook，如果都不好用再尝试其它工具。

**Comment by zhyz18csy** [comment]
那个文件里的1-9fq软件全都尝试过了，v2rayB那么多个端口全都无法连接，更新v2rayB都显示无法连接！（有点小无奈）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bannedbook/fanqiang"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上10:32
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
@zhyz18csy 里面有10多种工具，而且每款工具的ip更新地址有多个，几乎都是不同的ip，请问都尝试了吗

**Comment by zhyz18csy** [comment]
十几个软件，上百种端口，怎么今天都不行？（难道是连接有点故障？）我就真的很疑惑了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bannedbook/fanqiang"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上10:33
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
@zhyz18csy 如果不知道怎么选择，可以推荐一下，优先尝试v2ray ip1和ip2，ss-kcptun，brook，如果都不好用再尝试其它工具。

**Comment by Alvin9999** [comment]
目前有很多人正在使用. 请关闭电脑防火墙和杀毒软件,自行排查一下其它干扰软件.

**Comment by Alvin9999** [comment]
所有的服务器器均正常.

**Comment by zhyz18csy** [comment]
我天天都关闭的，不然肯定被卡。谢谢您的提醒！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bannedbook/fanqiang"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上10:44
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
目前有很多人正在使用. 请关闭电脑防火墙和杀毒软件,自行排查一下其它干扰软件.

**Comment by zhyz18csy** [comment]
在我收到前一个消息时，我立马打开软件，结果——好了！（这是不是太玄学了？）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bannedbook/fanqiang"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月19日(星期三) 晚上10:44
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"为梦“棋”航"<2641584375@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 火狐和铬的翻墙软件都不能用 (#531)





 
所有的服务器器均正常.

**Comment by Alvin9999** [comment]
有可能是你的网络不稳定的缘故。能用就好哦。

**Comment by FreeSlaver** [comment]
真的没撒折腾的必要，都是一路折腾过来的人。
还是用别人的机场把，便宜稳定，撒事都不用操心，<a href="https://user.by.ltd/aff.php?aff=17672">bywave</a>。
你那折腾的几个小时玩会游戏，刷会视频，学习下，它不香吗？
这个机场我18年末用到现在，当初有个套餐是80块钱250gb流量，包终生。
后面遇到3次还是几次故障，只要时间够久都会赔偿，有一次好像是赔偿了100多g。
我就白嫖到了现在，当时冲了100块，现在还有35块余额了。
专业的事情还是交给专业的人干把。
