### ISSUE TITLE
证书不安全ummmm

### ISSUE THREAD

**Issue by niconi23333** [bannedbook/fanqiang#533]
XX-Net 提示证书有问题，如果这时候选不信任就会一直循环，ctrl+c也不行，本当に大丈夫ですが…？
而且为什么要夹带那么多私货啊...我知道真正的天安门事件真相，不是这里面说的那样

**Comment by niconi23333** [comment]
强制重启后会导致连不上网umm 手动把ip改回来就可以了 话说这个脚本真的安全吗

**Comment by bannedbook** [comment]
第一次运行时，提示导入证书不要跳过

**Comment by niconi23333** [comment]
唔......好的，谢谢~
