### ISSUE TITLE
系统找不到指定的文件。 拒绝访问。 已复制         0 个文件。  

### ISSUE THREAD

**Issue by 2091449962** [bannedbook/fanqiang#536]
--2020-06-08 19:10:56--  https://gitlab.com/free9999/ipupdate/-/raw/master/goflyway/goflyway.bat
Resolving gitlab.com (gitlab.com)... 172.65.251.78
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 113 [text/plain]
Saving to: 'goflyway.bat'

100%[==============================================================================>] 113         --.-K/s   in 0s

2020-06-08 19:10:57 (53.9 MB/s) - 'goflyway.bat' saved [113/113]

找不到 D:\ChromeGo\Goflyway\goflyway.bat_backup
系统找不到指定的文件。
拒绝访问。
已复制         0 个文件。

已更新完成最新可用Goflyway配置,请按回车键或空格键启动程序！
无论打开哪个,除了XX-Net都显示这个怎么办?

**Comment by bannedbook** [comment]
用
8.v2rayB翻墙.cmd
试试看

1、启动后如果Chrome页面打不开，点桌面右下角托盘区蓝色V图标，打开V2rayN软件；

2、然后在V2rayN主界面，按Ctrl+A键选中所有服务器，然后点右键，再点：测试服务器真连接延迟（多选）

3、测试完毕后，测试结果为数字的是可用服务器，测试结果数字越小越快,点测试结果列头可排序;

4、鼠标点击选中一个可用服务器，按回车键激活，然后回到已打开的chrome浏览器刷新页面；如果还打不开页面可从最快到最慢的服务器挨个尝试；

5、如果第4步挨个测试所有可用服务器都不行，那么点V2rayN左上角“订阅/更新订阅”，然后重复第2-4步。
