### ISSUE TITLE
caddy如何添加伪装站?

### ISSUE THREAD

**Issue by joshatt** [bannedbook/fanqiang#537]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
brook

根据楼主的系列文章:
https://github.com/bannedbook/fanqiang/blob/master/v2ss/Brook%E4%B9%8BTLS%2BWebSocket%2BWeb%E7%BF%BB%E5%A2%99%E6%95%99%E7%A8%8B.md
部署了Brook+TLS+WebSocket+Caddy Web服务器
成功了, 挺好用. 

不过, 直接访问域名的话, 404 不通. 因为没有设置主页吧? 最好是个伪装站.
于是学习了一下, 尝试修改caddyfile:
```
www.mydomain.com
{
  log ./caddy.log
  proxy / https://www.kernel.org {
    except /a
  }
  proxy / localhost:18000 {
    websocket
    header_upstream -Origin
  }
}
```
也尝试了:
```
www.mydomain.com
{
  log ./caddy.log
  proxy / https://www.kernel.org {
    except /a
  }
  proxy /a localhost:18000 {
    without /a
    websocket
    header_upstream -Origin
  }
}
```
结果翻墙都不通了. brook客户端显示 HTTP/1.1 404 Not Found

照猫画虎就是不行啊. 请教高人, 怎么添加伪装站?

**Comment by bannedbook** [comment]
brook 当前貌似不支持伪装站，因为无法设置  ws 的path 参数，直接使用了 根目录

所以，如果想用伪装站，推荐用v2ray

**Comment by joshatt** [comment]
> brook 当前貌似不支持伪装站，因为无法设置 ws 的path 参数，直接使用了 根目录
> 
> 所以，如果想用伪装站，推荐用v2ray

谢谢解答

**Comment by joshatt** [comment]
> brook 当前貌似不支持伪装站，因为无法设置 ws 的path 参数，直接使用了 根目录
> 
在根目录只放一个伪装的index.html文件, 行不行?

**Comment by bannedbook** [comment]
应该是不行的
proxy / localhost:18000
这个指令，就把所有连接都转到brook了，candy不会自己提供任何网页。
