### ISSUE TITLE
运行翻墙软件，使用chrome浏览器时不弹出Internet Download Manager浮动条，并弹出警告窗

### ISSUE THREAD

**Issue by gitgrime** [bannedbook/fanqiang#539]
请问有办法解决吗？
![Snipaste_2020-06-13_15-49-47](https://user-images.githubusercontent.com/66864780/84563458-56b6c000-ad8e-11ea-90ab-185db66c31e4.png)

**Comment by bannedbook** [comment]
装这个插件
https://chrome.google.com/webstore/detail/download-by-internet-down/lgbipmmmnjifkiiikaffhceflifbmhib?hl=en

注意，要先设置好idm的代理，否则可能idm就直连了

**Comment by gitgrime** [comment]
> 装这个插件试试看
> https://chrome.google.com/webstore/detail/download-by-internet-down/lgbipmmmnjifkiiikaffhceflifbmhib?hl=en
> 
> 注意，要先设置好idm的代理，否则可能idm就直连了

装了这个扩展还是没弹窗；
之前idm代理设置选择“使用系统设置”是可以下youtube视频的，现在连浮动条都没有了。

**Comment by bannedbook** [comment]
idm代理设置选择“使用系统设置”，只有在 翻墙软件会设置系统代理时才保险。

**Comment by bannedbook** [comment]
那你的浏览器是不是 用管理员权限启动的

**Comment by bannedbook** [comment]
你用谷歌搜索：
idm 管理员权限启动

**Comment by gitgrime** [comment]
> 那你的浏览器是不是 用管理员权限启动的

看了一下任务管理器，是。但这是开了8.v2rayB翻墙.cmd、1.Goflyway翻墙.cmd等等的时候才这样，不翻墙的时候用chrome是非管理员状态运行的。我猜会不会作者在设计程序的时候就写下管理员运行chrome了？
![Snipaste_2020-06-14_07-38-09](https://user-images.githubusercontent.com/66864780/84581260-0719d800-ae12-11ea-9597-fdb5cbcafa63.png)
![Snipaste_2020-06-14_07-38-33](https://user-images.githubusercontent.com/66864780/84581263-19941180-ae12-11ea-9dbf-3cf2d90d9595.png)

**Comment by bannedbook** [comment]
也许可以试试其它的，fdm 等

**Comment by gitgrime** [comment]
> 也许可以试试其它的，fdm 等

用过FDM XDM NeatDM,觉得效果一般。如果解决不了只能用FirefoxFQ了，这个还是能翻墙的同时出浮动条的。
