### ISSUE TITLE
2020年6月18日下载的最新ChromeGo今天就无法更新IP，所有的软件都不能使用

### ISSUE THREAD

**Issue by dangweijun** [bannedbook/fanqiang#541]
2020年6月18日下载的最新ChromeGo今天就无法更新IP，所有的软件都不能使用，请问发生了什么事

**Comment by bannedbook** [comment]
ip1 和 ip2 都无法更新吗
有什么错误提示

**Comment by dangweijun** [comment]
早上更新IP1的时候连接不上，IP2更新的时候更新了但是打开浏览器后连不上。现在IP1可以更新，更新后也可以上了，谢谢楼主。
