### ISSUE TITLE
现在节点的速度都很慢很难过千

### ISSUE THREAD

**Issue by ask7696** [bannedbook/fanqiang#549]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
![图片](https://user-images.githubusercontent.com/52815730/88393342-0ea8a580-cdf0-11ea-97da-7e0eb97b032b.png)

**Comment by Alvin9999** [comment]
请明确说明您反馈的问题是有关哪一个软件，或哪一个服务

**Comment by ask7696** [comment]
V2rayn

**Comment by Alvin9999** [comment]
一键翻墙浏览器里面有很多工具，可以试试其它的工具

**Comment by ask7696** [comment]
基本都试了 都很难过千刷新了好久一直都是

**Comment by ask7696** [comment]
![图片](https://user-images.githubusercontent.com/52815730/88394829-a6a78e80-cdf2-11ea-9afe-db3d16fa0b50.png)
这个是SS的

**Comment by Alvin9999** [comment]
多发点截图。顺便问下，你家的宽带是什么类型？电信、联通、移动、教育网？

**Comment by ask7696** [comment]
电信200M

**Comment by Alvin9999** [comment]
好的，知道了。goflyway等工具的速度截图也可以发一下，goflyway ip1和ip2节点不一样，分别测试。

**Comment by Alvin9999** [comment]
有人反馈goflyway速度1万多kbps

**Comment by ask7696** [comment]
嗯 我试试

**Comment by ask7696** [comment]
brook速度可以但是做成了一体的了大佬把那些一体自连的分离成V2rayn有客户端的吗

**Comment by Alvin9999** [comment]
目前不考虑

**Comment by ask7696** [comment]
嗯

**Comment by Alvin9999** [comment]
做成集合版，一是为了大家使用方便，当网络封锁的时候，一种工具不好用，很快就能换其它的工具。二是维护起来也很方便，不用维护多个版本，节省维护时间成本。

**Comment by ask7696** [comment]
嗯

**Comment by RainSilver** [comment]
电信什么都慢

**Comment by Alvin9999** [comment]
最近我们对线路进行了优化，电信网络可以优先尝试v2ray ip1和ip3 以及etgo ip1，采用CN2回程线路，晚高峰期速度会快一点。
