### ISSUE TITLE
求助 为什么appid上传成功 直接失效了

### ISSUE THREAD

**Issue by qq496941015** [bannedbook/fanqiang#55]
访问http://woyoupp.appspot.com/ 提示Error: Not Found   The requested URL / was not found on this server.

**Comment by bannedbook** [comment]
用记事本打开app.yaml，把里面的第一行的YourAppid  替换为你自己申请到的appid ，这一步做好了没

**Comment by luellue1989814** [comment]
成功上传了 知道原因了

2017-01-17 6:40 GMT+08:00 如何翻墙 <notifications@github.com>:
