### ISSUE TITLE
蓝灯高速流量用完了可以刷新吗

### ISSUE THREAD

**Issue by Feng1909** [bannedbook/fanqiang#553]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
蓝灯
高速流量
更新流量

**Comment by bannedbook** [comment]
好像需要花钱购买吧。
你可以试试其它通道。比如 clash 、 v2rayb 等

**Comment by Feng1909** [comment]
好的，非常感谢，感觉蓝灯最快
