### ISSUE TITLE
安装成功，但是启动不起来，查看状态如下。

### ISSUE THREAD

**Issue by harryheng** [bannedbook/fanqiang#554]
service v2ray status  
Redirecting to /bin/systemctl status v2ray.service
● v2ray.service - V2Ray Service
   Loaded: loaded (/etc/systemd/system/v2ray.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2020-08-03 16:46:35 CST; 4s ago
     Docs: https://www.v2ray.com/
           https://www.v2fly.org/
  Process: 13653 ExecStart=/usr/bin/v2ray/v2ray -config /etc/v2ray/config.json (code=exited, status=218/CAPABILITIES)
 Main PID: 13653 (code=exited, status=218/CAPABILITIES)

Aug 03 16:46:35 HostKvm-fba05a systemd[1]: Unit v2ray.service entered failed state.
Aug 03 16:46:35 HostKvm-fba05a systemd[1]: v2ray.service failed.
Aug 03 16:46:35 HostKvm-fba05a systemd[1]: v2ray.service holdoff time over, scheduling restart.
Aug 03 16:46:35 HostKvm-fba05a systemd[1]: Stopped V2Ray Service.
Aug 03 16:46:35 HostKvm-fba05a systemd[1]: start request repeated too quickly for v2ray.service
Aug 03 16:46:35 HostKvm-fba05a systemd[1]: Failed to start V2Ray Service.
Aug 03 16:46:35 HostKvm-fba05a systemd[1]: Unit v2ray.service entered failed state.
Aug 03 16:46:35 HostKvm-fba05a systemd[1]: v2ray.service failed.

**Comment by bannedbook** [comment]
你的vps时间好像不对，时区、时间都要正确

**Comment by bannedbook** [comment]
看你的日志，CST 时区，时间却是北京时间
