### ISSUE TITLE
订阅地址无法链接

### ISSUE THREAD

**Issue by ask7696** [bannedbook/fanqiang#563]
更新订阅开始
1->开始获取订阅内容
无法连接到远程服务器
![图片](https://user-images.githubusercontent.com/52815730/90386698-86988180-e0b7-11ea-817f-2a7d39637333.png)

**Comment by bannedbook** [comment]
这是哪个软件

**Comment by ask7696** [comment]
火狐的v2rayB

**Comment by bannedbook** [comment]
订阅网址被封了，先试试别的吧

**Comment by bannedbook** [comment]
更新了，请下载新版

**Comment by ask7696** [comment]
嗯 谢谢
