### ISSUE TITLE
pornhub访问不了

### ISSUE THREAD

**Issue by cz952266431** [bannedbook/fanqiang#570]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
尝试了很多次，翻墙之后访问http://pornhub.com/ 一直失败。 提示的也多种多样，比如：
1.read tcp 192.168.2.106:57332->89.163.224.92:8880: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
2.此网站无法提供安全连接
pornhub.com 发送的响应无效。
尝试运行 Windows 网络诊断。
ERR_SSL_PROTOCOL_ERROR
3.无法访问此网站pornhub.com 的响应时间过长。
请试试以下办法：

检查网络连接
检查代理服务器和防火墙
运行 Windows 网络诊断
ERR_TIMED_OUT

**Comment by cz952266431** [comment]
使用的是 1.Goflyway翻墙

**Comment by lhb8125** [comment]
老哥666

**Comment by Alvin9999** [comment]
屏蔽了黄色网站
