### ISSUE TITLE
修改IP地址翻墙后怎么恢复恢复原来的IP呢

### ISSUE THREAD

**Issue by share123321** [bannedbook/fanqiang#581]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
如题

**Comment by bannedbook** [comment]
怎么修改的，修改的什么ip

**Comment by share123321** [comment]
使用1.Goflyway翻墙.cmd修改的笔记本ip地址，可以翻墙，现在想恢复原来的ip，不知道怎么处理

**Comment by bannedbook** [comment]
我们的软件不会修改你的笔记本ip地址
ip更新是指 翻墙代理的ip

**Comment by share123321** [comment]
那怎么样恢复到不使用代理的ip呢

**Comment by bannedbook** [comment]
https://answers.microsoft.com/zh-hans/ie/forum/all/%E5%A6%82%E4%BD%95%E6%B8%85%E9%99%A4%E4%BB%A3/b4137742-7bd4-498a-b14a-5ac442db64ff
