### ISSUE TITLE
大佬厉害   请问ubuntu18下怎样使用v2ray账号呢？一串字母那个v2ray

### ISSUE THREAD

**Issue by henbucuoshanghai** [bannedbook/fanqiang#582]
多谢多谢

**Comment by bannedbook** [comment]
https://github.com/v2fly/v2ray-core/releases
这里下载 linux版

**Comment by henbucuoshanghai** [comment]
from the "assets"&nbsp; download the&nbsp; "v2ray-linux-64.zip", the only one file is enough?

**Comment by henbucuoshanghai** [comment]
你好，下载完成。解压linux64.zip。&nbsp; &nbsp;请问哪里运行呢，v2ray那一串字母放在哪里呢？怎样运行？新人不懂。多谢多谢。

**Comment by bannedbook** [comment]
又研究了一下，发现可以用这个软件
https://linger.ink/2020/linux-qv2ray-usage

**Comment by foho8080** [comment]
@bannedbook 又研究了一下，发现可以用这个软件
https://linger.ink/2020/linux-qv2ray-usage   這個軟件怎樣使用  能發個教程嗎

**Comment by bannedbook** [comment]
自己gogole搜索看看吧
