### ISSUE TITLE
@bannedbook  請問這個軟件怎樣使用

### ISSUE THREAD

**Issue by foho8080** [bannedbook/fanqiang#584]
@bannedbook  請問這個Qv2ray軟件怎樣使用

**Comment by bannedbook** [comment]
https://www.google.com/search?source=hp&ei=Vyt5X6PABcvB0PEPwoKquAc&q=Qv2ray+%E6%95%99%E7%A8%8B&oq=Qv2ray+%E6%95%99%E7%A8%8B&gs_lcp=CgZwc3ktYWIQAzICCAA6CAghEKABEIsDUKMCWOwiYPYkaAFwAHgAgAH-AYgBpwmSAQMyLTWYAQCgAQKgAQGqAQdnd3Mtd2l6uAEC&sclient=psy-ab&ved=0ahUKEwjjx8as6pnsAhXLIDQIHUKBCncQ4dUDCAk&uact=5
