### ISSUE TITLE
有没有Linux可用的一键工具？

### ISSUE THREAD

**Issue by wayne0926** [bannedbook/fanqiang#588]
有没有Linux(Ubuntu)可用的一键工具？

**Comment by Alvin9999** [comment]
可以用ssr或者v2ray，[linux方法](https://github.com/Alvin9999/new-pac/wiki/Linux%E7%B3%BB%E7%BB%9F%E7%BF%BB%E5%A2%99%E6%96%B9%E6%B3%95)
