### ISSUE TITLE
今天发现都用不了了，求更新啊。

### ISSUE THREAD

**Issue by WHLYA** [bannedbook/fanqiang#595]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？

**Comment by bannedbook** [comment]
v2rayb 更新订阅试试看
clash 也可以试试

**Comment by WHLYA** [comment]
都试过了，今天上午第一个还是可以用的，下午就不行了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bannedbook/fanqiang"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月25日(星期天) 下午3:49
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"青青草原"<2647480632@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 今天发现都用不了了，求更新啊。 (#595)





 
v2rayb 更新订阅试试看
 clash 也可以试试

**Comment by dangweijun** [comment]
我也是，全部用不了，请全部更新一下吧

**Comment by Alvin9999** [comment]
goflway、book、ssr已更新

**Comment by WHLYA** [comment]
感恩～♥------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;自由上网&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月25日(星期天) 下午4:44
收件人:&nbsp;&quot;bannedbook/fanqiang&quot;<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;&quot;WHLYA&quot;<2647480632@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 今天发现都用不了了，求更新啊。 (#595)

**Comment by foho8080** [comment]
我這裡只能用 Goflyway SS-Kcptun ssr v2b  其他不能用

**Comment by dangweijun** [comment]
主站的CH文件包没有更新啊

**Comment by Alvin9999** [comment]
云端更新了.运行ip更新文件即可同步

**Comment by dangweijun** [comment]
全部都用不了，之前用CH里面自带的蓝灯，今天下午蓝灯都用不了了

**Comment by Alvin9999** [comment]
> 全部都用不了，之前用CH里面自带的蓝灯，今天下午蓝灯都用不了了

关闭系统自带的防火墙试试看

**Comment by bannedbook** [comment]
请大家用这个安卓app
[SS VPN](https://github.com/bannedbook/fanqiang/wiki/%E5%AE%89%E5%8D%93%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6#v2vpn)
已恢复绝大部分内置节点

**Comment by WHLYA** [comment]
大佬，好像又挂了。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;自由上网&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年10月25日(星期天) 晚上7:09
收件人:&nbsp;&quot;bannedbook/fanqiang&quot;<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;&quot;WHLYA&quot;<2647480632@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 今天发现都用不了了，求更新啊。 (#595)

**Comment by asan855** [comment]
免费太难了，glados不错，目前只能邀请，https://glados.rocks/ 邀请码：O1GS9-M3Q1F-LJT5K-85G06

**Comment by WHLYA** [comment]
不行啊。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bannedbook/fanqiang"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月27日(星期二) 下午4:40
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"青青草原"<2647480632@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 今天发现都用不了了，求更新啊。 (#595)





 
免费太难了，glados不错，目前只能邀请，https://glados.rocks/ 邀请码：O1GS9-M3Q1F-LJT5K-85G06

**Comment by Alvin9999** [comment]
> 不行啊。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bannedbook/fanqiang" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月27日(星期二) 下午4:40 收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;; 抄送:&nbsp;"青青草原"<2647480632@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [bannedbook/fanqiang] 今天发现都用不了了，求更新啊。 (#595) 免费太难了，glados不错，目前只能邀请，https://glados.rocks/ 邀请码：O1GS9-M3Q1F-LJT5K-85G06 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

试试SSR，刚更新了

**Comment by Mrzhangfish** [comment]
免费翻墙梯子vpn 免费机场 免费vpn ss ssr v2ray trojan 科学上网 gfw 中国防火墙 防火长城 shadowsocks 自由上网 网络移民 免费翻墙软件 youtube 油管 脸书 推特 twitter facebook WhatsApp  Telegram Line Skype Messenger Twitch游戏直播

提供 免费翻墙梯子vpn 请联系客服微信： mrzhangfish 添加请备注"梯子"

VPN

翻墙梯子

梯子

免费机场

网络加速器

国际互联网  奈飞 HBOMAX  hulu BBCplayer Instagram Google 谷歌全家桶 Gmail邮箱

免费节点 免费ssr节点 免费v2ray节点 免费trojan节点 免费ss节点 WireGuard  SSTAP Netch AnyConnect  VLESS Vmess  PassWall ssrplus 外贸  跨境电商  英美剧 日韩剧 影视剧 手游国际服 美服 韩服 日服 欧服 游戏加速器 手游加速器  端游  主机游戏 网络加速器 翻墙路由器 外贸路由器 路由器翻墙 openwrt 梅林固件 老毛子固件 高恪固件 跨境路由器 跨境电商 外贸 Shopee Wish eBay Spotify音乐  Amazon-亚马逊全球开店  全球速卖通  阿里巴巴国际站 AfreecaTv  YouTubeLive  niconico  TikTok  Amazon Prime Video

shadowrocket shadowsocksr clash v2rayN igniter surfboard Pharos Pro  Qv2ray V2rayNG Kitsunebi  ClashX  Quantumult Surge ShadowsocksX  Quantumult（X） Quantumult X  Trojan-Qt5 苹果设备 安卓设备 pc mac ipad平板等等 路由器 软路由 硬路由 硬改路由  openwrt固件编译 基本支持全平台系统 4k 8k 免费机场节点 订阅地址 Netflix 一切只为看片。 

机场节点注册地址：https://panel.mrzhangfish.ml   注册之后请查看里面具体的使用文档

具体使用方法教程如下：

请参照菜单栏的 wiki ， https://github.com/XiaoLangCat/XiaoLangCat.github.io/wiki 有问题，也可以在这里提问题。

右侧wiki菜单栏介绍的是手动切换节点的代理客户端，电脑PC端 Windows版和安卓系统 的节点自动切换可以使用 clash 代理客户端，详细请链接个人博客：https://www.mrzhangfish.tk/ 或者 https://blogs.gooutside.website/
