### ISSUE TITLE
火狐集合包今天全挂了

### ISSUE THREAD

**Issue by ask7696** [bannedbook/fanqiang#596]
更新不出来IP
![图片](https://user-images.githubusercontent.com/52815730/97108175-de321980-1706-11eb-909e-f6da552228b8.png)

**Comment by Alvin9999** [comment]
Goflyway ip1、Brook、SSR、SS、Etgo，可以优先尝试这些工具

**Comment by ask7696** [comment]
都试了不行

**Comment by Alvin9999** [comment]
是无法正常更新，还是更新后无法正常使用？

**Comment by ask7696** [comment]
更新后无法使用昨天还好用今天全部都不行了重阳节墙又加高了

**Comment by Alvin9999** [comment]
我上面推荐那些工具目前已正常，很多人在用了。你试试关闭系统自带的防火墙以及杀毒软件后，再一个个去尝试看看。

**Comment by Alvin9999** [comment]
今天墙确实加高了。

**Comment by ask7696** [comment]
还是不行用不了了

**Comment by Alvin9999** [comment]
ssr、ss也用不了？截图看看

**Comment by Alvin9999** [comment]
ip更新完成后的黑色框截图、ssr客户端账号页面截图

**Comment by ask7696** [comment]
![图片](https://user-images.githubusercontent.com/52815730/97122184-dbfba980-175e-11eb-8681-539038743f1c.png)

![图片](https://user-images.githubusercontent.com/52815730/97122176-ca1a0680-175e-11eb-8824-a1cce80877b2.png)

**Comment by Alvin9999** [comment]
@ask7696 ssr和ss，不是ss-kcptun，ss-kcptun暂时用不了

**Comment by ask7696** [comment]
![图片](https://user-images.githubusercontent.com/52815730/97122341-1e71b600-1760-11eb-9fad-f9e6d3f37175.png)
![图片](https://user-images.githubusercontent.com/52815730/97122364-4bbe6400-1760-11eb-824e-26ec2654847b.png)
![图片](https://user-images.githubusercontent.com/52815730/97122380-642e7e80-1760-11eb-978b-135532080995.png)
![图片](https://user-images.githubusercontent.com/52815730/97122402-8b854b80-1760-11eb-8f42-48ee8bc97e73.png)
都不行，昨天瞬间全挂了

**Comment by Alvin9999** [comment]
用ip2来更新，你没有更新成功

**Comment by Alvin9999** [comment]
节点信息没有同步

**Comment by ask7696** [comment]
嗯 我再试试

**Comment by Alvin9999** [comment]
现在除了ss-kcptun、trojan-go，其它工具都已恢复正常。
