### ISSUE TITLE
工具用不了了

### ISSUE THREAD

**Issue by ask7696** [bannedbook/fanqiang#603]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？

**Comment by dangweijun** [comment]
可以是最近中央搞了个网络安全会议，那些人开始做工作了

**Comment by Alvin9999** [comment]
刚更新了v2ray和SSR，可以都试试看

**Comment by ask7696** [comment]
要不要重新下载包？你昨天说更新了，但是就是一直刷新不出来

**Comment by Alvin9999** [comment]
> 要不要重新下载包？你昨天说更新了，但是就是一直刷新不出来

不用。云端更新了ip，运行ip更新文件即可同步。v2ray有4个ip更新地址，SSR有2个ip更新地址。

**Comment by ask7696** [comment]
v2ray4个IP更新地址？我安装的包怎么就2个？

**Comment by bannedbook** [comment]
你从新下载下，你可能是旧版

**Comment by ask7696** [comment]
4个IP更新地址是在bat前端？

**Comment by bannedbook** [comment]
bat启动时，就会提示，有4个ip更新选项

**Comment by ZJU-LOSER** [comment]
我也都 用不了了... 有无付费稳定的梯子呀

**Comment by ZJU-LOSER** [comment]
不管怎么样 还是感谢答主

**Comment by bannedbook** [comment]
主页上有个推荐 https://github.com/bannedbook/fanqiang/wiki/V2ray%E6%9C%BA%E5%9C%BA

**Comment by ZJU-LOSER** [comment]
这个链接的有看到，请问这个是得先充值吗，还是说有试用期，我照教程的做没起作用...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bannedbook/fanqiang"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月28日(星期三) 晚上8:25
收件人:&nbsp;"bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;;
抄送:&nbsp;"Fate"<1395440228@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 工具用不了了 (#603)





 
主页上有个推荐 https://github.com/bannedbook/fanqiang/wiki/V2ray%E6%9C%BA%E5%9C%BA

**Comment by bannedbook** [comment]
需要先充值

**Comment by ask7696** [comment]
新版安装包的链接给一个，我刚刚又下了一遍V2的还是2个IP更新地址

**Comment by dangweijun** [comment]
现在我用自由门了，免费还比较稳定

**Comment by ZJU-LOSER** [comment]
哈哈哈好的，我用了主页贴的v2free了，还算便宜。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "dangweijun"<notifications@github.com&gt;; 
发送时间: 2020年10月29日(星期四) 下午4:00
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;; 
抄送: "Fate"<1395440228@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bannedbook/fanqiang] 工具用不了了 (#603)





 
现在我用自由门了，免费还比较稳定

**Comment by bannedbook** [comment]
> 新版安装包的链接给一个，我刚刚又下了一遍V2的还是2个IP更新地址

我试了一下 https://github.com/bannedbook/fanqiang/releases
这里的ChromeGo-v20200818
是4个ip更新

**Comment by bannedbook** [comment]
试了 https://d1.bdrive.cf/ChromeGo.7z 这个也一样

**Comment by bannedbook** [comment]
4个ip更新是指 
启动 2.v2ray翻墙.cmd 之后，有4个ip更新可选择

**Comment by ask7696** [comment]
> 
> 
> 试了 https://d1.bdrive.cf/ChromeGo.7z 这个也一样
哦 火狐PC的就2个

**Comment by bannedbook** [comment]
先用chrome吧

**Comment by hunterlam** [comment]
> 我也都 用不了了... 有无付费稳定的梯子呀

**[这里](https://www.makemedollar.com/VPS000)**有个敏感期也不会被封的VPN，走的是Cisco架构。

**Comment by hunterlam** [comment]
> > 我也都 用不了了... 有无付费稳定的梯子呀
> 
> **[这里](https://www.makemedollar.com/VPS000)**有个敏感期也不会被封的VPN，走的是Cisco架构。



> 我也都 用不了了... 有无付费稳定的梯子呀

[[这里](https://www.makemedollar.com/VPS000)](https://www.makemedollar.com/VPS000)有个敏感期也不会被封的VPN，走的是Cisco架构。

**Comment by SimpleSimple** [comment]
> 现在我用自由门了，免费还比较稳定

自由门现在稳定了吗，之前用一直不稳定啊！！！！

**Comment by Alvin9999** [comment]
> > 现在我用自由门了，免费还比较稳定
> 
> 自由门现在稳定了吗，之前用一直不稳定啊！！！！

可以试试看。不同的时期使用效果可能会不一样。自由门抗封锁性很强。

**Comment by FFFTQ** [comment]
我用的这个，最近还可以  https://nn.lausera.com/aff/a9CcQ

**Comment by wangwenqin123** [comment]
> 我用的这个，最近还可以 https://nn.lausera.com/aff/a9CcQ

这个确实是很好用的
