### ISSUE TITLE
为项目长久计，望作者修改一处文字表述

### ISSUE THREAD

**Issue by shenzhongjun** [bannedbook/fanqiang#610]
https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85
“它们与共匪金盾工程还有千丝万缕的关系!”，软件作者被请去喝茶不是第一遭了，尤其还是fanqiang软件，作者君谨慎啊

**Comment by bannedbook** [comment]
谢谢提醒，修改了一下
