### ISSUE TITLE
使用过Goflyway，关掉Goflyway,Chrome就不能上网了

### ISSUE THREAD

**Issue by StuInfo** [bannedbook/fanqiang#614]
再windows设置中已关闭使用代理，IE也关闭了代理。

**Comment by Alvin9999** [comment]
国内网站也打不开吗

**Comment by StuInfo** [comment]
> 国内网站也打不开吗

知道了，只有打开脚本弹出来的chrome才能翻墙，弹出来的chrome关闭cmd后就不能上网了，原本的chrome是可以上网的

**Comment by Alvin9999** [comment]
好的，是这样的
