### ISSUE TITLE
为什么每次用都要把收藏夹给改了，而且以前的收藏夹内容也不见了

### ISSUE THREAD

**Issue by kyz20** [bannedbook/fanqiang#615]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
能不能取消对于收藏夹的改动，这样造成了很多麻烦

**Comment by bannedbook** [comment]
是每次启动，还是每次 下载新的版本？

**Comment by kyz20** [comment]
> 是每次启动，还是每次 下载新的版本？

每次启动，所以我现在chrome都只敢游客状态访问，不然每次收藏夹都给改了，以前的也没了。

**Comment by bannedbook** [comment]
可能是你开启了chrome的 同步吧
chrome://settings/syncSetup

**Comment by kyz20** [comment]
> 可能是你开启了chrome的 同步吧
> chrome://settings/syncSetup

不开启同步会怎样？就不会修改收藏夹了吗？

**Comment by bannedbook** [comment]
我们软件没有修改 收藏夹，是chrome同步功能修改的

**Comment by chenting127** [comment]
同问，我的收藏夹已经被替换成一堆从来没见过的内容了，像“禁书网、禁新闻、墙外媒体”等等，很明显这些内容并非Chrome自带，而是被ChromeGo替换掉了。我的问题是：如何才能找回来我自己的收藏夹？因为第一次使用ChromeGo，并不清楚会出现收藏夹被替换的现象，而我之前是开启同步的，收藏夹里存了好多年的链接都消失了。

**Comment by bannedbook** [comment]
不是修改，启动的是一个新的独立浏览器，自带搜藏夹。
独立于你自己的浏览器
