### ISSUE TITLE
win10用了clash关掉之后，系统的手动代理过一会自动打开，导致浏览器不能正常上网

### ISSUE THREAD

**Issue by forest1989** [bannedbook/fanqiang#617]
![QQ截图20201223130946](https://user-images.githubusercontent.com/10951104/102961776-2b244780-4520-11eb-996e-7fc9be4ab545.png)

**Comment by bannedbook** [comment]
应该不是clash，可能是其它工具

**Comment by forest1989** [comment]
但我再次打开clash，这个手动代理就算开着，浏览器上网也是正常的。

**Comment by bannedbook** [comment]
那你手动把它关掉

**Comment by forest1989** [comment]
手动关掉，过一会也会自动打开，你们是有什么全局代理需要去手动关掉吗？

**Comment by bannedbook** [comment]
可能你还开着其它软件，你再找找
