### ISSUE TITLE
SSH连接VPS教程中 输入vps的root密码 即无法复制也无法输入

### ISSUE THREAD

**Issue by xuyixuyi** [bannedbook/fanqiang#623]
"在windows 命令窗口，或 Git for Windows 的 Git Bash 窗口，输入： ssh root@your-vps-ip ，然后回车，然后输入vps的root密码，密码可以点鼠标右键复制粘贴。"
这两个都无法输入密码，光标在闪，也已经复制成功了，在别的地方可以粘贴，但是在这两个地方就是不行，分别用的ctrl+v快捷键和鼠标右键，都无法粘贴。
请问该怎么处理？谢谢。

**Comment by killgcd** [comment]
如果是windows cmd 窗口，可能需要打开快速编辑模式

**Comment by xuyixuyi** [comment]
> 
> 
> 回车看看，可能是不显示而已

非常感谢回答！确实是不显示，但是又出现一个问题：
找了一个view console 成功出现login 弹出窗口的IP，输入密码后是出现“Permission denied, please try again.”
是这个IP的问题，还是别的原因所致？
