### ISSUE TITLE
Safari打不开a.dtwang.org

### ISSUE THREAD

**Issue by Jianchao-ICT** [bannedbook/fanqiang#63]
家里有两个无线网，其中一个成功了，另一个同样的配置之前也成功了，今天却失败了，浏览器打不开a.dtwang.org。pac.dtwang.org也试过了。很奇怪。请教下各位是什么可能的原因呢？

**Comment by bannedbook** [comment]
注意pac地址有更新，请看 [PAC翻墙](https://github.com/bannedbook/fanqiang/wiki/pacfq)
