### ISSUE TITLE
好像突然全部都不能用了

### ISSUE THREAD

**Issue by gaphrodite** [bannedbook/fanqiang#631]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
好像突然全部方式都不能用了

**Comment by SNOW713-gg** [comment]
我的也是

**Comment by Alvin9999** [comment]
部分工具ip失效，但有的工具没问题，比如ssrot ，ssr ip2，ss-kcptun，v2ray ip3都正常。
可以先用能用的工具，会尽快更换失效工具ip。

**Comment by gaphrodite** [comment]
感谢！v2ray ip3可用！

**Comment by zhyz18csy** [comment]
您好！在此我先祝您新春快乐，牛年大吉！
我想请问一下最近为什么所有的fq工具都无法使用了？何时能够逐渐恢复fq功能呢？
感谢您新春还在为我们服务，辛苦了！

**Comment by bannedbook** [comment]
墙发疯，封锁大陆ip，努力恢复中
着急可以先用这个
https://github.com/bannedbook/fanqiang/wiki/V2ray%E6%9C%BA%E5%9C%BA

**Comment by zhyz18csy** [comment]
好的，谢谢！
能否等ip恢复好了回复一下我这条消息？辛苦了！

**Comment by Alvin9999** [comment]
**北京时间2021年2月13日16点16分：最近封锁严重，部分工具ip失效，即使更新了很快又被封了，但有的工具没问题。推荐优先尝试clash，ssrot ，ssr ip2，ss-kcptun，v2ray ip3。**

**Comment by zhyz18csy** [comment]
您好！我刚刚试过了，所有这些都无效（怪封锁太严了）

**Comment by zhyz18csy** [comment]
您还是等ip（哪怕是一个绝对能用）更新好了再通知我，行吗？谢谢！

**Comment by Alvin9999** [comment]
> 您还是等ip（哪怕是一个绝对能用）更新好了再通知我，行吗？谢谢！

不同地区使用效果不同，有的人可以用的

**Comment by zhyz18csy** [comment]
可能是我们这里封锁紧吧，毕竟大城市
我的意思是等大家都可以用了再通知我一下，行吗？谢谢！

**Comment by Alvin9999** [comment]
> 可能是我们这里封锁紧吧，毕竟大城市
> 我的意思是等大家都可以用了再通知我一下，行吗？谢谢！

可以留个邮箱

**Comment by zhyz18csy** [comment]
2641584375@qq.com




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "foho8080"<notifications@github.com&gt;; 
发送时间: 2021年2月13日(星期六) 下午5:24
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;; 
抄送: "为梦“棋”航"<2641584375@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bannedbook/fanqiang] 好像突然全部都不能用了 (#631)





  
可能是我们这里封锁紧吧，毕竟大城市
 我的意思是等大家都可以用了再通知我一下，行吗？谢谢！
  
可以留个邮箱

**Comment by bannedbook** [comment]
北京时间2021年2月20日8点48分：最近封锁严重，可以优先尝试clash ip1 ip2，v2ray ip1、ip2、ip3、ip4，ssrot ，ssr ip1 ip2，ss-kcptun ip1 ip2。

**Comment by Reyna-Jin** [comment]
蹲一个，地处北京

电脑端、移动端在过年这几天都没打开过

**Comment by bannedbook** [comment]
不会吧，好像封锁到过去了

**Comment by zhyz18csy** [comment]
封锁在我发送上一邮件两天后就过了，谢谢您！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "foho8080"<notifications@github.com&gt;; 
发送时间: 2021年2月24日(星期三) 中午12:48
收件人: "bannedbook/fanqiang"<fanqiang@noreply.github.com&gt;; 
抄送: "为梦“棋”航"<2641584375@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [bannedbook/fanqiang] 好像突然全部都不能用了 (#631)





 
不会吧，好像封锁到过去了

**Comment by FreeSlaver** [comment]
真的没撒折腾的必要，都是一路折腾过来的人。
还是用别人的机场把，便宜稳定，撒事都不用操心，<a href="https://user.by.ltd/aff.php?aff=17672">bywave</a>。
你那折腾的几个小时玩会游戏，刷会视频，学习下，它不香吗？
这个机场我18年末用到现在，当初有个套餐是80块钱250gb流量，包终生。
后面遇到3次还是几次故障，只要时间够久都会赔偿，有一次好像是赔偿了100多g。
我就白嫖到了现在，当时冲了100块，现在还有35块余额了。
专业的事情还是交给专业的人干把。
