### ISSUE TITLE
Vultr注册问题

### ISSUE THREAD

**Issue by zhaipeidong** [bannedbook/fanqiang#645]
请问如何在Vultr中，只连接PayPal账户，来获得100美元邀请奖励？

**Comment by bannedbook** [comment]
* Duplicate accounts not eligible. Referred customer must link a valid credit card or Paypal method to be eligible for the $100 credit. Unused portion of $100 credit expires after 30 days.

并没有说 paypal 不行吧

**Comment by zhaipeidong** [comment]
> * Duplicate accounts not eligible. Referred customer must link a valid credit card or Paypal method to be eligible for the $100 credit. Unused portion of $100 credit expires after 30 days.
> 
> 并没有说  不行吧

但是莫名其妙连不上paypal...领不了奖励

**Comment by bannedbook** [comment]
要么 paypal ，要么信用卡，必须连一个 才能行

**Comment by zhaipeidong** [comment]
> 要么 paypal ，要么信用卡，必须连一个 才能行

怎么连接PayPal呢，我看只有支付啊

**Comment by bannedbook** [comment]
支付的时候，如果有一个  subscription 的支付选项，就选这个
如果没有的话，应该支付成功 就算连接上了吧

**Comment by zhaipeidong** [comment]
> 支付的时候，如果有一个 subscription 的支付选项，就选这个
> 如果没有的话，应该支付成功 就算连接上了吧

就是说，必须要充钱，才可以用吗？

**Comment by bannedbook** [comment]
可以充值充1块钱试试看

**Comment by zhaipeidong** [comment]
至少充5$啊，30多块

**Comment by bannedbook** [comment]
是吗，这个倒是没太注意。冲完了赠送的$100 到帐了吧

**Comment by zhaipeidong** [comment]
照理是不能让你这么白嫖的啊

**Comment by bannedbook** [comment]
![Snap1](https://user-images.githubusercontent.com/4361923/110111964-13a0ef00-7dec-11eb-8547-6f71f25dfded.jpg)
我这里试一下，最小是$1

**Comment by zhaipeidong** [comment]
![image](https://user-images.githubusercontent.com/58897821/110112099-3c28e900-7dec-11eb-8716-338283c0114a.png)
？？？我这里是$5

**Comment by bannedbook** [comment]
可能因为我是老帐号吧

**Comment by zhaipeidong** [comment]
看着100$却拿不到，难受QvQ
