### ISSUE TITLE
跪求自由门 for mac

### ISSUE THREAD

**Issue by czl0325** [bannedbook/fanqiang#647]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？

跪求自由门 for Mac
需要一个mac端免费的上网软件，稳定的，求自由门for mac

**Comment by bannedbook** [comment]
苹果MAC系统用自由门、无界的翻墙方法
https://www.bannedbook.org/forum23/topic4621.html

**Comment by czl0325** [comment]
https://www.bannedbook.org/forum23/topic4621.html

打不开，给个墙内地址吧

**Comment by bannedbook** [comment]
你可以先用我们提供的免费v2ray或免费ss
https://github.com/bannedbook/fanqiang/wiki/%E8%8B%B9%E6%9E%9C%E7%94%B5%E8%84%91MAC%E7%BF%BB%E5%A2%99
先翻出来，然后再查阅资料

**Comment by czl0325** [comment]
麻烦把WineBottlerCombo和GProxy上传到你的github这个项目下，没有找到这两款的下载。多谢了

**Comment by Luciausa** [comment]
WineBottlerCombo
https://winebottler.kronenberg.org/
GProxy
https://www.bannedbook.org/forum23/topic2138.html

**Comment by czl0325** [comment]
右键使用wine打开， 报错Prefix creation aborted。
mac11.1系统

**Comment by bannedbook** [comment]
这个您得自己研究研究啦，这个教程比较老，很多软件都升级了
