### ISSUE TITLE
对chrome一键翻墙的一些问题

### ISSUE THREAD

**Issue by muxiaou** [bannedbook/fanqiang#648]
我想问一下，通过chrome一键翻墙，为什么我可以找到chrome.exe了，但是为什么感觉这个浏览器页面是一个全新的页面呢，我之前的浏览器设置了一些插件还有一些标签，为什么都没了呢，有什么解决办法吗？

**Comment by bannedbook** [comment]
标签可以导出导入，
或者 考虑 登录谷歌帐号同步 不知道行不行

**Comment by muxiaou** [comment]
还有就是为什么我未一键翻墙之前打开了一个浏览器，但是翻墙之后打开浏览器又是一个全新的页面，有没有什么办法让两者关联在一起呢，都在一个窗口中，而不是又打开一个窗口？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午3:12
收件人: ***@***.***&gt;; 
抄送: "沐小悠@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bannedbook/fanqiang] 对chrome一键翻墙的一些问题 (#648)





 
标签可以导出导入，
 或者 考虑 登录谷歌帐号同步 不知道行不行

**Comment by bannedbook** [comment]
这个没办法，我们打开这个浏览器是独立的文件夹。
其实这样也挺好，一个用来翻墙，一个访问国内网站，互不干涉。

**Comment by muxiaou** [comment]
好的，谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午3:20
收件人: ***@***.***&gt;; 
抄送: "沐小悠@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bannedbook/fanqiang] 对chrome一键翻墙的一些问题 (#648)





 
这个没办法，我们打开这个浏览器是独立的文件夹。
 其实这样也挺好，一个用来翻墙，一个访问国内网站，互不干涉。

**Comment by bannedbook** [comment]
蓝灯 和 psiphon 会设置系统代理， 你可以用原来的浏览器窗口。
其它工具不设置系统代理，只设置 新打开的浏览器的代理。

**Comment by muxiaou** [comment]
嗯嗯，试了一下蓝灯确实可以用原来的浏览器窗口，但是psiphon好像连接过程会有点问题，速度特别慢，还会出现中断问题，不过整个工具还是很好用的，多谢分享。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午3:23
收件人: ***@***.***&gt;; 
抄送: "沐小悠@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bannedbook/fanqiang] 对chrome一键翻墙的一些问题 (#648)





 
蓝灯 和 psiphon 会设置系统代理， 你可以用原来的浏览器窗口。
 其它工具不设置系统代理，只设置 新打开的浏览器的代理。

**Comment by muxiaou** [comment]
刚才又试了一下蓝灯，好像不是很稳定，之前还可以关联窗口，现在好像又是独立的了，不过独立的也不错，两个分开不互相干扰。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月18日(星期四) 下午3:23
收件人: ***@***.***&gt;; 
抄送: "沐小悠@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bannedbook/fanqiang] 对chrome一键翻墙的一些问题 (#648)





 
蓝灯 和 psiphon 会设置系统代理， 你可以用原来的浏览器窗口。
 其它工具不设置系统代理，只设置 新打开的浏览器的代理。

**Comment by Songheyang1998** [comment]
书签不同步啊，真要命，好像就变成两个浏览器，账号不同步，是因为我原来的Chrome没有翻墙吗？没有翻墙就不会同步账号设置和收藏

**Comment by bannedbook** [comment]
书签 导出导入就可以
或者登录谷歌账号同步
