### ISSUE TITLE
IP挂了望管理大大修复下谢谢

### ISSUE THREAD

**Issue by ask7696** [bannedbook/fanqiang#649]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
ChromeGo 和firefox ip全部挂了刷了好久都刷不出  还有BAT打开前端之前能快捷操作更新IP选项的现在没了

**Comment by bannedbook** [comment]
为啥更新ip的选项会没了呢
需要更新ip才能用吧

**Comment by ask7696** [comment]
我也想知道为什么没了，现在点开直接跳转
![图片](https://user-images.githubusercontent.com/52815730/111748678-c896d980-88cb-11eb-928c-430acc59d32b.png)双击之后就这样 然后直接跳出浏览器

**Comment by bannedbook** [comment]
你是windows xp机器吗，或者是你系统问题 ，缺少了choice.exe 这个程序
