### ISSUE TITLE
ChromeGo打不开

### ISSUE THREAD

**Issue by XiuyuanWang** [bannedbook/fanqiang#650]
我下载了Chrome浏览器，在用clash脚本翻墙时打不开ChromeGo浏览器
![翻墙问题](https://user-images.githubusercontent.com/52308488/112032067-f6ec1180-8b76-11eb-83e6-659b4545f0cb.png)
运行卡在中间不动了。。

**Comment by bannedbook** [comment]
按图中的提示操作
