### ISSUE TITLE
下载的chrome一键翻墙包，双击任何一个脚本都是一闪而过，闪退啊，打不开

### ISSUE THREAD

**Issue by jiangossac** [bannedbook/fanqiang#656]
下载的chrome一键翻墙包，双击任何一个脚本都是一闪而过，闪退啊，打不开，另外一台电脑都没问题。

**Comment by bannedbook** [comment]
那你先进入命令行
cd 到目录
再执行 脚本，这样应该可以看清楚 都有什么提示信息

**Comment by jiangossac** [comment]
我已经cd到目录，执行脚本，结果还是一样，跳一下就闪退。

**Comment by jiangossac** [comment]
不过后来发现，把chromego文件夹直接放在一级目录就可以了。
