### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by zhangchao77** [bannedbook/fanqiang#657]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
各个节点打不开了 是怎么回事？

**Comment by wxt18066** [comment]
几个好像都试了

**Comment by bannedbook** [comment]
您反馈的是哪个软件？

**Comment by wxt18066** [comment]
Goflyway、clash、v2ray、v2rayb、SSR、SS、SS-Kcptun、Naiveproxy、Brook、Trojan-go、除了v2rayb都进行了尝试，浏览器一直转圈圈




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月16日(星期天) 晚上7:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bannedbook/fanqiang] 打不开 (#657)






您反馈的是哪个软件?

—
您正在接收此消息，因为您编写了线程。
直接回复此邮件，在GitHub上查看或者取消订阅.

**Comment by bannedbook** [comment]
重新下载新版，第一次使用先更新ip。以后连不上时，再次更新ip。
可先试试里面的v2free翻墙

**Comment by wxt18066** [comment]
怎么更新ip?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月16日(周日) 晚上8:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bannedbook/fanqiang] 打不开 (#657)




 
重新下载新版，第一次使用先更新ip。以后连不上时，再次更新ip。
 可先试试里面的v2free翻墙

**Comment by wxt18066** [comment]
怎么更新ip?



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月16日(周日) 晚上8:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bannedbook/fanqiang] 打不开 (#657)




 
重新下载新版，第一次使用先更新ip。以后连不上时，再次更新ip。
 可先试试里面的v2free翻墙

**Comment by bannedbook** [comment]
启动的时候有提示

**Comment by wxt18066** [comment]
那我更新过了，谷歌浏览器一直转圈
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bannedbook/fanqiang"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月16日(星期天) 晚上8:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bannedbook/fanqiang] 打不开 (#657)





 
启动的时候有提示

**Comment by bannedbook** [comment]
哪个
多试试，每个都试试

**Comment by wxt18066** [comment]
你好 现在打开界面 都链接不上 我之前装了几个插件 然后插件也崩溃了 就类似界面这样

**Comment by bannedbook** [comment]
下载新版，更新ip，按顺序挨个都试试看
