### ISSUE TITLE
别用它推荐的v2free机场

### ISSUE THREAD

**Issue by Hackergeek** [bannedbook/fanqiang#660]
别用它推荐的[v2free](https://w1.v2free.net/user)机场，流量计算有问题，完全不用流量都会慢慢消耗完的，真黑心，开源割韭菜，吃相别这么难看行不行，希望github官方能把这个项目删了，恶心到我了

**Comment by bannedbook** [comment]
不可能有这种事吧。vpn只要开着，系统就会自动有各种流量，不是说你非得打开浏览器浏览网站才有流量。
