### ISSUE TITLE
V2ray一键安装失败

### ISSUE THREAD

**Issue by Tangjhno1** [bannedbook/fanqiang#663]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
root@three:~# systemctl enable v2ray
Failed to enable unit: File v2ray.service: No such file or directory
执行最后一条时提示这个，用的阿里云

**Comment by bannedbook** [comment]
安裝和更新 V2Ray
// 安裝執行檔和 .dat 資料檔
# bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh)

删除
# bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) --remove

删除重装试试看

这个 systemctl enable v2ray，可以不用执行

**Comment by Tangjhno1** [comment]
Linux three 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u3 (2019-06-16) x86_64

Welcome to Alibaba Cloud Elastic Compute Service !

Last login: Wed Jun  9 13:46:00 2021 from 112.49.232.221
root@three:~# bash <(curl -L https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh) --remove
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21613  100 21613    0     0  59817      0 --:--:-- --:--:-- --:--:-- 59704
info: Stop the V2Ray service.
rm: cannot remove '/usr/local/bin/v2ray': No such file or directory
rm: cannot remove '/usr/local/bin/v2ctl': No such file or directory
rm: cannot remove '/etc/systemd/system/v2ray.service': No such file or directory
rm: cannot remove '/etc/systemd/system/v2ray@.service': No such file or directory
rm: cannot remove '/etc/systemd/system/v2ray.service.d': No such file or directory
rm: cannot remove '/etc/systemd/system/v2ray@.service.d': No such file or directory
error: Failed to remove V2Ray.
难受 莫名其妙 我昨晚用你的方法刚搭的别的服务器厂家的可以的呀

**Comment by bannedbook** [comment]
这些目录不存在，就是没装上
你再装一下试试看

**Comment by Tangjhno1** [comment]
找到问题了老哥 阿里有个网络安全组 他的入方向要把所有协议类型打开 我前面只开了tcp与icmp 感谢老哥！！！

**Comment by Tangjhno1** [comment]
老哥如果我现在的服务器ip被墙了，那我服务器换了ip后，是不是只需要改变客户端的ip就行，不需要重新安装一遍了吧。

**Comment by bannedbook** [comment]
服务器换了ip ,  客户端配置里面的服务器ip 要跟着变

**Comment by Tangjhno1** [comment]
老哥 我现在想实现一台服务器上面装两个网卡就是俩ip，那我的vpn能实现双访问嘛，两个地址都能用这样？

**Comment by bannedbook** [comment]
可以

**Comment by Tangjhno1** [comment]
网上找了好多，没看人有这需求，可以帮忙指导下嘛

**Comment by bannedbook** [comment]
这不用特别设置，
用我们这个例子配置文件
https://github.com/bannedbook/fanqiang/blob/master/v2ss/V2ray%E5%AE%98%E6%96%B9%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC.md
直接就可以吧

**Comment by Tangjhno1** [comment]
可是这时候另一个ip咋配置呢，远程连接后再安装一次v2ray嘛，但是v2ray安装路径一样会覆盖掉啊

**Comment by bannedbook** [comment]
装一次就行，程序自动监听本机所有ip

**Comment by Tangjhno1** [comment]
那我试试看

**Comment by Tangjhno1** [comment]
大佬可以哎，但是我分别用两个ip连vpn后查询自己ip地址，两个显示是一样的（显示其中一个），那相当于服务器用同一个ip向外网通信啊。

**Comment by mohanfeng3** [comment]
> 大佬可以哎，但是我分别用两个ip连vpn后查询自己ip地址，两个显示是一样的（显示其中一个），那相当于服务器用同一个ip向外网通信啊。
需要用到listin，添加tag，在route里面设置tag1进tag1出

**Comment by bannedbook** [comment]
> 大佬可以哎，但是我分别用两个ip连vpn后查询自己ip地址，两个显示是一样的（显示其中一个），那相当于服务器用同一个ip向外网通信啊。

2个ip a和b
入站连接的时候，客户端可以指定连哪个，但是出站的时候是系统里面有个 默认的路由配置，可能是a或者b
可以用
`ip route show` 
查看
