### ISSUE TITLE
默认的书签网址中有大量政治不正确的言论？

### ISSUE THREAD

**Issue by MachineL102** [bannedbook/fanqiang#664]
使用的是v2free，请撤销其中的有关政治的内容

**Comment by bannedbook** [comment]
v2free ， 你跟他们去反馈，我们这里不是v2free

**Comment by MachineL102** [comment]
好的感谢，也提醒下使用者不要被虚假言论误导，影响我们的软件使用

**Comment by MachineL102** [comment]
好的感谢，也提醒下用户不要被false message误导，影响我们的软件
