### ISSUE TITLE
SS搭建错误

### ISSUE THREAD

**Issue by aarons1996** [bannedbook/fanqiang#667]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？

按照文中方式搭建ss服务器，连接YouTube的时候连接不上，连接google出现500代理错误。
已经尝试过下面这些问题排除方法
1. configration OK， config文件放在/usr/local/etc/v2ray文件夹下，端口设置正确，密码设置正确
2. 重装过v2ray
3. sudo systemctl status v2ray 查看过运行状态，显示运行正常
4. 更改过端口设置，并且在SS中也做了相应更改，但是还是出现同样问题
5. ip地址可以ping通

**Comment by bannedbook** [comment]
打开客户端日志 看看有啥信息
