### ISSUE TITLE
自建v2ray失败

### ISSUE THREAD

**Issue by hushunda** [bannedbook/fanqiang#669]
以前成功了。最近新建的时候，尝试教程自建v2ray。vultr上的服务器能够ping通，登录。
但是完成这个v2ray搭建后，上不了网。

**Comment by bannedbook** [comment]
vultr debian 10 现在防火墙好像只开了  ssh 端口
执行下列命令试试看
ufw allow 端口/tcp
ufw allow 端口/tcp
比如
ufw allow 80/tcp
ufw allow 80/udp

用你需要开放的端口替代

**Comment by hushunda** [comment]
> vultr debian 10 现在防火墙好像默认只开了 ssh 端口
> 执行下列命令试试看
> ufw allow 端口/tcp
> ufw allow 端口/tcp
> 比如
> ufw allow 80/tcp
> ufw allow 80/udp
> 
> 用你需要开放的端口替代

大佬厉害，果然是这个问题。连我用debian10都猜到了

**Comment by Longder** [comment]
> vultr debian 10 现在防火墙好像默认只开了 ssh 端口
> 执行下列命令试试看
> ufw allow 端口/tcp
> ufw allow 端口/tcp
> 比如
> ufw allow 80/tcp
> ufw allow 80/udp
> 
> 用你需要开放的端口替代

大佬 开放了端口还是不得行 telnet也端口不通

**Comment by bannedbook** [comment]
你是不是开到了被墙的ip啊

**Comment by Longder** [comment]
> 你是不是开到了被墙的ip啊

ip能ping通呀

**Comment by bannedbook** [comment]
http://port.ping.pe/
测端口

**Comment by 769729647maidong** [comment]
同上,IP能ping通,端口不通,有解决方案么

**Comment by bannedbook** [comment]
vultr debian 10 现在防火墙好像默认只开了 ssh 端口
执行下列命令试试看
ufw allow 端口/tcp
ufw allow 端口/tcp
比如
ufw allow 80/tcp
ufw allow 80/udp

用你需要开放的端口替代

**Comment by 769729647maidong** [comment]
> vultr debian 10 现在防火墙好像默认只开了 ssh 端口
> 执行下列命令试试看
> ufw allow 端口/tcp
> ufw allow 端口/tcp
> 比如
> ufw allow 80/tcp
> ufw allow 80/udp
> 
> 用你需要开放的端口替代

不得行,telnet不通,弄了一天,准备放弃了

**Comment by bigdots** [comment]
IP和端口都通了，但是客户端连不上，是不是就是第五步的问题了

**Comment by bigdots** [comment]
10.9.80.168:14646->45.32.52.249:22822: wsarecv:A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
报这个错误，但是我明明ping的通

**Comment by hzy82218052** [comment]
看这个解决方案  alterID改成0
https://www.nixonli.com/24335.html

**Comment by Sadcrazy** [comment]
> > vultr debian 10 现在防火墙好像默认只开了 ssh 端口
> > 执行下列命令试试看
> > ufw allow 端口/tcp
> > ufw allow 端口/tcp
> > 比如
> > ufw allow 80/tcp
> > ufw allow 80/udp
> > 用你需要开放的端口替代
> 
> 大佬厉害，果然是这个问题。连我用debian10都猜到了

教程不是教你用Debian10吗 这需要猜吗
