### ISSUE TITLE
只能用启动脚本是启动的那个chrome吗？

### ISSUE THREAD

**Issue by wangzh6859** [bannedbook/fanqiang#674]
为什么电脑上自己安装的chrome无法科学上网？

**Comment by bannedbook** [comment]
需要自己设置代理

**Comment by wangzh6859** [comment]
启动脚本时启动的那个chrome什么也不用设置就可以直接翻，但是关了那个chrome，再打开自己的chrome的时候反而无法翻了，这种情况应该不是没设置代理的原因吧，而且设置全局也不行，用的是v2ray

**Comment by bannedbook** [comment]
你可以把自己的chrome 的标签、插件啥的到导入 脚本打开那个chrome就行了，用起来一样方便

**Comment by wangzh6859** [comment]
但是也不能一直打开那个窗口啊。只要把那个窗口关了就找不着了那个chrome，哪怕是固定在任务栏，关了再打开就是自己的浏览器了，也翻不了了。。。

**Comment by bannedbook** [comment]
那个窗口不能关闭，那个是代理程序。关掉了就翻不了了

**Comment by wangzh6859** [comment]
啊，还真是这样啊，那行吧，非常感谢

**Comment by 1239361527** [comment]
为什么打开的Chrome显示的都是一些不良言论，我想进google earth怎么进

**Comment by wangzh6859** [comment]
> 为什么打开的Chrome显示的都是一些不良言论，我想进google earth怎么进

直接搜索框搜索就行
