### ISSUE TITLE
之前一直用ChromeGo_SkyZip，挺好的，怎么找不着了？

### ISSUE THREAD

**Issue by terryandjing** [bannedbook/fanqiang#678]
在哪里下载ChromeGo_SkyZip

**Comment by bannedbook** [comment]
很久没更新了。
可以把ChromeGo的下载地址，最后的文件名替换成
ChromeGo_Skyzip.7z
下载看看

**Comment by terryandjing** [comment]
> 很久没更新了。
> 可以把ChromeGo的下载地址，最后的文件名替换成
> ChromeGo_Skyzip.7z
> 下载看看

替换了名字也下载不了，这个一直都在用，还不错的

**Comment by bannedbook** [comment]
https://d1.dns888.ml/ChromeGo_Skyzip.7z
