### ISSUE TITLE
旧版 v2rayB 的订阅

### ISSUE THREAD

**Issue by Creepercdn** [bannedbook/fanqiang#679]
之前使用的 v2rayB 中的订阅为 `https://cdn.jsdelivr.net/gh/fqnews/bnews@latest/vs/v2.txt` 目前已经失效，有没有其他的类似于这种订阅的方案？

**Comment by bannedbook** [comment]
看看这里
https://github.com/bannedbook/fanqiang/wiki/v2ray%E5%85%8D%E8%B4%B9%E8%B4%A6%E5%8F%B7
