### ISSUE TITLE
由于目标计算机积极拒绝，无法连接

### ISSUE THREAD

**Issue by 769729647maidong** [bannedbook/fanqiang#680]
自建Shadowsocks服务器, 日志显示:请问这是什么原因呀
由于目标计算机积极拒绝，无法连接,
2021-09-06 19:45:22.3912|WARN|Shadowsocks.Controller.TCPHandler|System.Net.Sockets.SocketException (0x80004005): 由于目标计算机积极拒绝，无法连接。
   在 Shadowsocks.Util.Sockets.WrappedSocket.EndConnect(IAsyncResult asyncResult)
   在 Shadowsocks.Proxy.DirectConnect.EndConnectDest(IAsyncResult asyncResult)
   在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)

**Comment by bannedbook** [comment]
参考这个
https://github.com/bannedbook/fanqiang/issues/669
