### ISSUE TITLE
Google谷歌账号无法登陆

### ISSUE THREAD

**Issue by Barry6** [bannedbook/fanqiang#681]
显示：无法登录
此浏览器或应用可能不安全。 了解详情
请尝试使用其他浏览器。如果您使用的是受支持的浏览器，可以重新尝试登录。

**Comment by bannedbook** [comment]
建议卸载国产杀毒软件，至少翻墙时不要用它们！因为很多国产杀毒软件，比如360安全卫生、360杀毒软件、腾讯管家、金山卫士等不仅仅会起干扰作用，造成软件无法正常使用或速度变慢，它们与金盾工程有千丝万缕的关系!其实win10自带的defender就有杀毒的功能，如果还需要安全软件，可以用推荐的杀毒软件，免费的，而且不会干扰翻墙。

**Comment by Barry6** [comment]
并没有解决

**Comment by bannedbook** [comment]
关掉 chrome 的所有插件看看
