### ISSUE TITLE
慢

### ISSUE THREAD

**Issue by zhangchao77** [bannedbook/fanqiang#695]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
谷歌一键开启的那个包没有了吗？而且目前好像有很多卡顿，网页直接无法打开

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85

**Comment by zhangchao77** [comment]
![image](https://user-images.githubusercontent.com/71696370/134889155-145ad5d8-d78a-4835-a1d6-151dd08ccdbe.png)
我说的是这个一键开启的shell命令这个软件包，这是我之前下的但是它最近都打不开网页，想重新下载一下这个来着

**Comment by bannedbook** [comment]
https://github.com/Alvin9999/new-pac/wiki/%E9%AB%98%E5%86%85%E6%A0%B8%E7%89%88
