### ISSUE TITLE
软件 包含木马

### ISSUE THREAD

**Issue by Leeatmy** [bannedbook/fanqiang#7]
＃最新版 ChromeGo 2016-08-31 的分析结果
https://www.virustotal.com/zh-cn/file/7dc1a7dacf44f0323d1767b28cb11ccfb47d8141b6e460c91ec2332cc1956b94/analysis/1472821007/

＃ 使用 Bitdefender Virus Scanner 发现 木马来自
goagent.exe
https://www.virustotal.com/zh-cn/file/8efc6d49d67e1f080122e0c9cb8f2b9a5a71d2c8eff4c43ad12e704e96bbd9de/analysis/1465035119/

＃老版本 使用 Bitdefender Virus Scanner 发现 木马来自 发现2个
goagent.exe
firefly_windows_386.exe
（https://www.virustotal.com/zh-cn/file/fba18b27037ff563c52108adb6c71daf031047ad7925f2d0038593f4ff7753eb/analysis/1471581222/）

**Comment by Leeatmy** [comment]
同样使用 Bitdefender Virus Scanner
火狐firefox一键翻墙包 也查出 goagent.exe 是木马

**Comment by bannedbook** [comment]
多半是误报吧.   我观察了一下那个报告, 好像报毒的都是不太有名的杀软
