### ISSUE TITLE
希望chromego支持Ubuntu操作系统

### ISSUE THREAD

**Issue by ubuntu2204** [bannedbook/fanqiang#700]
我在chtomego众多软件里，没找到支持ubuntu翻墙的，希望支持ubuntu操作系统

**Comment by bannedbook** [comment]
可以注册 [v2ray机场](https://github.com/bannedbook/fanqiang/wiki/V2ray%E6%9C%BA%E5%9C%BA)，获取免费v2ray节点，在 Ubuntu 下可以使用

**Comment by ubuntu2204** [comment]
感谢，但我还是希望能用方便快捷的一键fq
