### ISSUE TITLE
蓝灯翻墙专业版充值未收到服务，如何退费？

### ISSUE THREAD

**Issue by dajavuLi** [bannedbook/fanqiang#701]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
我下载了chrome一键翻墙包，在使用蓝灯翻墙时由于高速度流量的限制，充值了340RMB（充值成功）想升级为蓝灯专业版，但是并没有收到相应的服务信息。想请问一下楼主您如何退费呢？

**Comment by dajavuLi** [comment]
也许在充值时我的邮箱少输末尾后缀，即把“1414826853.com”输入为“1414826853.co”，因为我的专业版账户显示信息为”电子邮件：1414826853.co“、”专业版到期日:2022/11/5“。

**Comment by bannedbook** [comment]
您好，我们只是打包了蓝灯软件，关于付费的问题，可与这个邮箱联系：
support@getlantern.org
