### ISSUE TITLE
其他浏览器无法使用v2ray代理

### ISSUE THREAD

**Issue by LeoWang2007** [bannedbook/fanqiang#705]
**v2ray已开启全局代理模式，但只有firefox的ip是境外的，其他浏览器未使用代理，还是境内网络。请问如何解决？**
---
除了这个小问题，其他都非常好，感谢作者！

**Comment by LeoWang2007** [comment]
### 补充说明
![图片](https://user-images.githubusercontent.com/79351490/141611463-9c72ab04-237a-4483-a21c-36fd4f4bffe8.png)
v2ray已启动全局代理
![firefox可使用](https://user-images.githubusercontent.com/79351490/141611417-08834225-07c5-4d6b-b843-2ad57812944d.png)
firefox可使用
![图片](https://user-images.githubusercontent.com/79351490/141611520-2ae89d21-4a29-4b54-8e2d-4d1a77611cc7.png)
chrome无法使用

**Comment by bannedbook** [comment]
你是用 的 我们 火狐firefox一键翻墙包 吗？
我们还有  Chrome一键翻墙包  https://github.com/bannedbook/fanqiang/wiki/Chrome%E4%B8%80%E9%94%AE%E7%BF%BB%E5%A2%99%E5%8C%85

v2ray已开启全局代理模式 是用什么软件？是怎么开启的？

**Comment by LeoWang2007** [comment]
> 你是用的我们火狐firefox一键翻墙包吗？

用的是ChromeGo 关闭了自动打开的chrome浏览器
> v2ray已开启的动态代理模式是用什么软件？是什么开启的？

就是用的ChromeGo中的v2ray设置了自动配置系统代理

**Comment by bannedbook** [comment]
检查系统代理是否设置成功，检查是否有其它vpn或翻墙软件正在运行从而造成冲突。

检查是否有相关浏览器插件干扰，建议禁用所有浏览器插件试试看。

**Comment by LeoWang2007** [comment]
感谢！解决了，以前用过一款VPN插件忘记关了。
