### ISSUE TITLE
自建V2Ray+TLS翻墙配置方法

### ISSUE THREAD

**Issue by bigjimmy546** [bannedbook/fanqiang#715]
你好，我的设置是：

{
  "inbounds": [
    {
      "port": 443, // 建议使用 443 端口
      "protocol": "vmess",
      "settings": {
        "clients": [
          {
            "id": "xxxxxxxxxx",
            "alterId": 64
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls", // security 要设置为 tls 才会启用 TLS
        "tlsSettings": {
          "certificates": [
            {
              "certificateFile": "/etc/letsencrypt/live/xxxx..com/fullchain.pem", // 证书文件
              "keyFile": "/etc/letsencrypt/live/xxxxx.com/privkey.pem" // 密钥文件
            }
          ]
        }
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    }
  ]
}

我是使用certbot，所以密鑰文件地址這樣可以嗎？
请问我的设置有问题吗？这样链接之后无法访问所有网站

**Comment by bannedbook** [comment]
alterId  改成0，客户端也改成 0

**Comment by bannedbook** [comment]
chmod 777 /etc/letsencrypt/live/xxxx.com/fullchain.pem

**Comment by bigjimmy546** [comment]
最後需要更改certificate的location，只能copy cert 到v2ray的folder裡面，已解決，謝謝
