### ISSUE TITLE
自建v2ray升级4.440后无法使用

### ISSUE THREAD

**Issue by zzyalbert** [bannedbook/fanqiang#721]
使用install-release.sh脚本自建v2ray服务，之前正常使用，今天用脚本升级4.44.0之后ios（shadowLinks)无法使用，请问如何解决？或者有没有办法降v2ray版本？

**Comment by bannedbook** [comment]
用的 shadowsocks 协议吗，升级应该不影响啊

**Comment by zzyalbert** [comment]
> 用的 shadowsocks 协议吗，升级应该不影响啊

是用的vmess

**Comment by zzyalbert** [comment]
目前Mac上是OK的，就是IOS死活不行

**Comment by bannedbook** [comment]
换app，app太老了或者没升级，用不了新技术。
换这几个
Shadowrocket
QuantumultX  
Surge

**Comment by zzyalbert** [comment]
没有server端降级的办法吗？app用习惯了。。

**Comment by bannedbook** [comment]
在服务器端可以通过设置环境变量   v2ray.vmess.aead.forced = false 以强制开启对于 MD5 认证信息 认证机制的兼容

**Comment by zzyalbert** [comment]
> 在服务器端可以通过设置环境变量 v2ray.vmess.aead.forced = false 以强制开启对于 MD5 认证信息 认证机制的兼容

已解决，赞👍🏻
