### ISSUE TITLE
火狐和ChromeGo经更新后所有渠道全都无法使用

### ISSUE THREAD

**Issue by Henry-666** [bannedbook/fanqiang#725]
全部都是一联就断

**Comment by bannedbook** [comment]
下载新版试试

**Comment by Henry-666** [comment]
全都是重新下载最新版本的

**Comment by bannedbook** [comment]
建议卸载国产杀毒软件，至少翻墙时不要用它们！因为很多国产杀毒软件，比如360安全卫生、360杀毒软件、腾讯管家、金山卫士等不仅仅会起干扰作用，造成软件无法正常使用或速度变慢，它们与金盾工程有千丝万缕的关系!

**Comment by Henry-666** [comment]
使用时已全部关闭。是不是软件没问题，我这边有问题啊？

**Comment by bannedbook** [comment]
全部都是一联就断
那肯定是你的系统或网络有问题，你重新拨号换个ip试试

**Comment by Henry-666** [comment]
解决了！感谢。
我想起来之前选了360的DNS才连不上的，改了就好了
