### ISSUE TITLE
无法访问色情内容

### ISSUE THREAD

**Issue by russellthomas34** [bannedbook/fanqiang#742]
您好，我在使用您提供的一键翻墙包时遇到了一些烦恼。我使用了ssr和v2ray。

1. 谷歌搜索默认开启了“安全搜索”，不能显示色情内容，且无权限关闭。
2. 即使输入色情网站的地址也无法访问。
3. imagetwistcams是一个不用翻墙也能访问的色情网站，翻墙可以让观看体验更流畅。但今天，我翻墙后不能访问这个网站了，但不翻墙的时候却能访问。因此，可以推断是我们的节点出现了问题。
4. youtube、Google等健康网站可以正常访问。

**Comment by bannedbook** [comment]
色情网站被和谐了

**Comment by bannedbook** [comment]
[天眼所见、高人揭秘、邪淫非常可怕](https://www.bannedbook.org/forum57/topic4118.html)
