### ISSUE TITLE
打开CMD文件后，选择选项后在CHROME打开的同时，CMD窗口同时闪退

### ISSUE THREAD

**Issue by fayegolf** [bannedbook/fanqiang#750]
打开CMD文件，例如 0.v2go翻墙.cmd，选择1、2、3某个选项后，如果需要更新IP，则会自动更新，然后让点击任意键继续
然后，CHROME自动打开的同时，CMD窗口自动关闭。自从3月份的版本后的新版本都是同样的问题
![属性版本](https://user-images.githubusercontent.com/4123782/198314628-dd4804d9-0cbf-4fb5-8d15-06db0cdd8ede.png)
上面的是最后一个能运行不闪退的版本
后续的版本都是只能执行到如下的窗口，下一步就会闪退
![1666880703688](https://user-images.githubusercontent.com/4123782/198314340-1d8cdbaf-719a-4f35-ab3e-cc43a47b2a06.png)

已经关闭WINDOWS的全部杀毒软件和防火墙，包括安装的和内置的。
也试过其他人的说法，整个文件夹都放在根目录，都不起作用。
看过电脑 WINDOWS日志，在应用和系统里都没有任何错误日志记录。

**Comment by bannedbook** [comment]
这不是最新版本吧

**Comment by fayegolf** [comment]
能正常打开的是三月份以前的版本，之后的都是闪退，最下边的图是最新版本

**Comment by fayegolf** [comment]
跟IP几更新应该没关系，都是闪退，刚才试了一下，2一样闪退

**Comment by bannedbook** [comment]
你是说浏览器删退吗？那是你自己系统的问题了

**Comment by fayegolf** [comment]
不是浏览器退，就是截图的 CMD命令打开的窗口闪退，但是浏览器被成功调用打开了

**Comment by fayegolf** [comment]
有无大佬解释一下

**Comment by junwen666** [comment]
我也一样  两台电脑 台式机可以 笔记本就闪退  都是win11

**Comment by fayegolf** [comment]
我是一台WIN10，一台WIN11，都是笔记本电脑，自从今年三月份后的版本全都是

**Comment by bannedbook** [comment]
CMD命令窗口，是本来运行完就退出的吧

**Comment by fayegolf** [comment]
CMD命令行窗口是运行完就退出，但是会重新打开个新的运行日志的窗口

**Comment by fayegolf** [comment]
![image](https://user-images.githubusercontent.com/4123782/200171168-319eee9a-aec0-4810-a595-288102419c3d.png)
打开这个窗口

**Comment by fayegolf** [comment]
后期闪退的版本，不会打开这个窗口，但是会打开CHROME浏览器，只是后台代理没了，也就不能。。。。。

**Comment by bannedbook** [comment]
跳过更新ip呢

**Comment by fayegolf** [comment]
刚才试了，跳过也一样，闪退

**Comment by fayegolf** [comment]
大佬，有无地方可以查看运行日志的地方，我自己想办法分析一下

**Comment by bannedbook** [comment]
我测试没问题啊
是不是配置文件更新不完整导致的

**Comment by fayegolf** [comment]
肯定很多人没问题的，但是我这里确实这样，自从三月份后的新版本都是如此，好彩的是三月份的版本还能用。
配置文件，哪些配置文件，我下载的应该都是完整的

**Comment by fayegolf** [comment]
重新试验了一下，其他的没问题，基本上能正常打开，尽管只有一两个能用。
只是 《0.v2go翻墙》这个会有闪退，但是我觉得这个最好用。

**Comment by bannedbook** [comment]
更新了，应该修复了，请下载新版。

**Comment by fayegolf** [comment]
这次没问题了。多谢您的无私奉献！
