### ISSUE TITLE
自建v2ray失败

### ISSUE THREAD

**Issue by humorousno** [bannedbook/fanqiang#755]
服务器端搭建好了v2ray，并且24380端口也已经开放了
客户端使用的是v2rayN软件，添加服务器配置时客户端id有与服务器一样
但是使用火狐提示说代理服务器拒绝连接，这是为什么呀？

**Comment by humorousno** [comment]
问题解决了，使用谷歌浏览器成功了，具体原因还不清楚。

**Comment by Alvin9999** [comment]
好的

**Comment by Alvin9999** [comment]
可能是火狐浏览器没有配置浏览器代理。
