### ISSUE TITLE
ip能ping通 ，443端口不通

### ISSUE THREAD

**Issue by objdjm** [bannedbook/fanqiang#764]
debian10  已经手动开启了端口 VPS安全组也设置了

![image](https://user-images.githubusercontent.com/120356556/210354446-6b15c46e-058c-40f2-9295-a31c53a42007.png)

**Comment by bannedbook** [comment]
https://ping.pe/
这里测一下

**Comment by objdjm** [comment]
> https://ping.pe/ 这里测一下

测过了 还是不行 。vultr的机子

**Comment by bannedbook** [comment]
如果全部不通，就是你 端口根本没起来，或者自己防火墙没开。
如果只有中国不通，就是被墙了
