### ISSUE TITLE
v2ray启动失败，读取配置文件失败

### ISSUE THREAD

**Issue by objdjm** [bannedbook/fanqiang#765]
![image](https://user-images.githubusercontent.com/120356556/210387380-faa67d78-004a-47b6-a319-dcd0717a59d3.png)

![image](https://user-images.githubusercontent.com/120356556/210389835-ee489cd9-f311-42cb-b7df-6e41985c0b26.png)

配置文件如下
![image](https://user-images.githubusercontent.com/120356556/210389509-45d7b84a-a8b3-4f06-8892-a3d8eb7df2fe.png)

**Comment by bannedbook** [comment]
读取 v2ray.key 失败，检查文件权限
