### ISSUE TITLE
求救！！！！连不上

### ISSUE THREAD

**Issue by fayewong5406** [bannedbook/fanqiang#772]
![image](https://user-images.githubusercontent.com/117252945/218325027-00d0652f-4e04-48ac-b24d-b93701d3f84c.png)
请问有没有微信比较直接一点的沟通方式？

**Comment by bannedbook** [comment]
https://i.ping.pe/A/Z/img_AZxT51uR.png
https://i.ping.pe/8/n/img_8nEXh8Ny.png
机器没起来吧

**Comment by fayewong5406** [comment]
那我应该怎么处理呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月13日(周一) 上午8:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bannedbook/fanqiang] 求救！！！！连不上 (Issue #772)




 
https://i.ping.pe/A/Z/img_AZxT51uR.png
 https://i.ping.pe/8/n/img_8nEXh8Ny.png
 机器没起来吧

**Comment by bannedbook** [comment]
开机启动vps啊

**Comment by fayewong5406** [comment]
可以价格微信，指导一下吗？13631345406，这是我的微信手机号
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月13日(星期一) 上午8:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bannedbook/fanqiang] 求救！！！！连不上 (Issue #772)





 
https://i.ping.pe/A/Z/img_AZxT51uR.png
 https://i.ping.pe/8/n/img_8nEXh8Ny.png
 机器没起来吧
