### ISSUE TITLE
学习搭建同样绿色的VPN

### ISSUE THREAD

**Issue by PillerC** [bannedbook/fanqiang#778]
使用大神的VPN后，竟然启动了安全搜索模式，请问这个是怎样做到的，不但绿色了，而且把YouTube的广告也屏蔽掉了。我也想学着搭建一个这样的VPS，能否指教下，谢谢！

**Comment by bannedbook** [comment]
看看这里
https://one.one.one.one/family/

**Comment by PillerC** [comment]
非常感谢，但这种方式并不适用。电脑上可以适用Adguard插件屏蔽YouTube广告，但手机却不行。大神的节点却能都屏蔽掉，我也尝试寻找方法，却一直没有找到，还有指点下其它方式吗？

**Comment by bannedbook** [comment]
在vps上设置的
