### ISSUE TITLE
最近访问速度很慢，大家有没有同样的问题呀？

### ISSUE THREAD

**Issue by anwangwang** [bannedbook/fanqiang#780]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？

**Comment by HZYbest123** [comment]
尝试了ssr v2ray等，那几个节点好像都失效了，更新也一直不成功，卡在connecting

**Comment by Alvin9999** [comment]
用新版。ip更新成功才能用最新的ip。
