### ISSUE TITLE
网站证书过期，无法连接v2ray使用

### ISSUE THREAD

**Issue by Hardylee18** [bannedbook/fanqiang#782]
检查了部署完成的网站地址，证书有效期是3个月的，目前已经过期了，请问怎么续期这个证书或者更换呢？谢谢
我使用的项目是[v2ss](https://github.com/bannedbook/fanqiang/tree/master/v2ss)/V2Ray之TLS+WebSocket+Nginx+CDN配置方法.md

**Comment by bannedbook** [comment]
不会续就重新申请就完了呀
