### ISSUE TITLE
Clash .NET yaml: unmarshal errors: line 1: cannot unmarshal !!str 、dm1lc3M.. into config.RawConfig

### ISSUE THREAD

**Issue by xinbai240524** [bannedbook/fanqiang#783]
为啥我用clash（windows）报这个错误啊？

Clash .NET
yaml: unmarshal errors:
line 1: cannot unmarshal !!str
、dm1lc3M.. into config.RawConfig

**Comment by loveapple-pan** [comment]
我也是直接拷贝V2RayN的订阅链接然后在配置里直接订阅的也报了这个错误，请问该怎么解决呢

**Comment by bannedbook** [comment]
clash 当然要用 clash订阅链接，不能用v2ray的
