### ISSUE TITLE
内网设备，通过服务端squid代理之后可以上网（正常情况下不可上网），这种情况下，是否无法翻墙

### ISSUE THREAD

**Issue by lk101** [bannedbook/fanqiang#789]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？

我在内网环境（受网路岗限制，内网不能直接访问Internet）把ChromeGo里的所有命令行都尝试了一遍，发现都无法翻墙成功

我这种情况，是否能够不修改代理服务器设置就翻墙成功呢？

感激不尽

**Comment by bannedbook** [comment]
可以翻的
比如，自由门、无界，都可以设置一个前置代理
