### ISSUE TITLE
启动 V2Ray 服务失败。

### ISSUE THREAD

**Issue by Adam5921** [bannedbook/fanqiang#792]
● v2ray.service - V2Ray 服务
      已加载：已加载（/etc/systemd/system/v2ray.service；已禁用；供应商预设：已启用）
     插入：/etc/systemd/system/v2ray.service.d
              └─10-donot_touch_single_conf.conf
      活动：自周五 2023-04-14 09:31:33 UTC 以来失败（结果：退出代码）； 24 秒前
        文档：https://www.v2fly.org/
     进程：15211 ExecStart=/usr/local/bin/v2ray run -config /usr/local/etc/v2ray/config.json (code=exited, status=1/FAILUR>
    主 PID：15211（代码=退出，状态=1/失败）

这个应该怎么解决啊？

**Comment by Adam5921** [comment]
Apr 14 09:31:33 adam systemd[1]: v2ray.service: Main process exited, code=exited, status=1/FAILURE
Apr 14 09:31:33 adam systemd[1]: v2ray.service: Failed with result 'exit-code'.
Apr 14 09:31:33 adam systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Apr 14 09:31:33 adam systemd[1]: Stopped V2Ray Service.
Apr 14 09:31:33 adam systemd[1]: v2ray.service: Start request repeated too quickly.
Apr 14 09:31:33 adam systemd[1]: v2ray.service: Failed with result 'exit-code'.
Apr 14 09:31:33 adam systemd[1]: Failed to start V2Ray Service.

**Comment by Adam5921** [comment]
4 月 14 日 09:31:33 adam systemd[1]：v2ray.service：主进程退出，代码=退出，状态=1/失败
4 月 14 日 09:31:33 adam systemd [1]：v2ray.service：失败，结果为“退出代码”。
4 月 14 日 09:31:33 adam systemd[1]：v2ray.service：计划重启作业，重启计数器为 5。
4 月 14 日 09:31:33 adam systemd[1]：已停止 V2Ray 服务。
4 月 14 日 09:31:33 adam systemd[1]：v2ray.service：启动请求重复得太快。
4 月 14 日 09:31:33 adam systemd [1]：v2ray.service：失败，结果为“退出代码”。
Apr 14 09:31:33 adam systemd[1]: 启动 V2Ray 服务失败。

**Comment by YanDididi** [comment]
目前服务确实不可用，即使在更新了4.5日的新版本之后仍然无法连接

**Comment by YanDididi** [comment]
目前服务确实不可用，即使在更新了4.5日的新版本之后仍然无法连接

**Comment by bannedbook** [comment]
你说的是哪一个

**Comment by YanDididi** [comment]
哪一个都不能用

**Comment by YanDididi** [comment]
> 你说的是哪一个
现在看来是可以连上的

**Comment by bannedbook** [comment]
请提供报错信息，截图

**Comment by bannedbook** [comment]
换换 ip
