### ISSUE TITLE
  ChromeGo 个个翻墙都无法正常使用 

### ISSUE THREAD

**Issue by goodpersons** [bannedbook/fanqiang#794]
求大佬分析  ChromeGo   ssr 、v2ray 等个个翻墙都无法正常使用 
![image](https://user-images.githubusercontent.com/82384326/233392863-7ddc8c6b-fb78-4e0e-97b1-3a9590657a2b.png)
ip 能正常更新
![image](https://user-images.githubusercontent.com/82384326/233393019-8c7dc025-5aee-429a-8c1b-4b6ade16c84f.png)
也关闭了防火墙 和 杀毒软

**Comment by bannedbook** [comment]
每个都试了吗？

**Comment by bannedbook** [comment]
怎么在 system32目录下运行？

**Comment by goodpersons** [comment]
> 每个都试了吗？

试过了 偶尔会有能用的 但是不稳定 过一会就又不行了

**Comment by bannedbook** [comment]
为了更稳定、更安全的翻墙，建议卸载国产杀毒软件，至少翻墙时不要用它们！因为很多国产杀毒软件，比如360安全卫生、360杀毒软件、腾讯管家、金山卫士等不仅仅会起干扰作用，造成软件无法正常使用或速度变慢，它们与金盾工程有千丝万缕的关系

**Comment by PiPiTaDie** [comment]
选个付费的吧 https://balala.io/auth/register?code=AHNP  一个月就十块钱，有几十个接口包含多个国家，虽然是有流量限制的，但是至今没见过有人一个月把流量用完的
