### ISSUE TITLE
自建V2ray服务器简明教程

### ISSUE THREAD

**Issue by CodeGeassR0** [bannedbook/fanqiang#799]
自建V2ray服务器后，可以让多个Windows同时使用吗？可以让Android使用吗？

**Comment by Alvin9999** [comment]
可以的，没有设备数限制。

**Comment by CodeGeassR0** [comment]
我按照《自建V2ray服务器简明教程》，浏览器已经OK了。在这个基础上，怎么实现让整个电脑、Android或iOS也能成功。

**Comment by bannedbook** [comment]
Android或iOS
都有对应的客户端，可以安装使用
https://github.com/bannedbook/fanqiang#readme

**Comment by CodeGeassR0** [comment]
我以前用了“自建V2ray服务器简明教程”，可以顺利访问外面，速度飞快。为了怕影响到这个服务，我不再登录服务器，客户端配置也不再修改。用了10天后，突然就断连了，而且我ssh到云服务器，也是连几分钟就断了。换了服务器的静态IP，也是几分钟就断了。我以为是我用的技术太简单了，就按照“V2Ray之TLS+WebSocket+Nginx+CDN配置方法”进行操作，目前的状态是连接时断时续，用十几分钟几十分钟后就开始断连了。不断尝试修改客户端配置的子域名和端口，运气好能成功连上，过几十分钟又断了。

**Comment by bannedbook** [comment]
可能快到某个铭感日，封锁加重了
