### ISSUE TITLE
通过v2go连接时误关机，电脑重启后无法访问国内网站

### ISSUE THREAD

**Issue by comfortablely** [bannedbook/fanqiang#819]
通过v2go连接时误关机，电脑重启后连接原本的WiFi无法访问国内网站，但仍可正常科学上网，手机可正常连接原本的WiFi上网，电脑连接手机热点可正常上网，如何解决

**Comment by bannedbook** [comment]
清除系统代理

**Comment by bannedbook** [comment]
仍可正常科学上网
说明有翻墙工具正在运行，不一定是v2go
找到什么工具，停止它，清除系统代理

**Comment by comfortablely** [comment]
> 仍可正常科学上网 说明有翻墙工具正在运行，不一定是v2go 找到什么工具，停止它，清除系统代理
我的意思是
关闭v2go后电脑绝大部分网页不可访问
运行v2go跳过ip更新，可以流畅科学上网，但无法访问国内网站
求解答

**Comment by bannedbook** [comment]
v2go  打开的浏览器就是访问国外网站的
访问国内网站，用其它浏览器

**Comment by comfortablely** [comment]
> v2go 打开的浏览器就是访问国外网站的 访问国内网站，用其它浏览器

![百度](https://github.com/bannedbook/fanqiang/assets/81851671/d2711473-6094-4cf1-a97e-b9827a92d643)
谢谢，我知道这个，问题是我现在电脑处于出了科学上网不可上网的状态
暂时不麻烦您了，我去学习一下相关知识再详细描述给您
感谢

**Comment by bannedbook** [comment]
v2go 不会影响你的系统，可能是其它的软件
用完后关闭了软件，但没有关系系统代理

**Comment by free18** [comment]
分享两个长期免费订阅
v2ray订阅：https://ghproxy.com/https://raw.githubusercontent.com/free18/v2ray/main/v2ray.txt
Clash订阅：https://ghproxy.com/https://raw.githubusercontent.com/free18/v2ray/main/Clash.yaml

**Comment by baiwei0703** [comment]
看下控制面板 -- “Internet 选项” -- “连接”选项卡 -- "局域网设置"按钮 里面的 “代理服务器”。在不启用梯子的时候，那个勾不要勾着。
