### ISSUE TITLE
V2Ray之TLS+WebSocket+Nginx+CDN配置方法

### ISSUE THREAD

**Issue by bigjimmy546** [bannedbook/fanqiang#821]
V2Ray之TLS+WebSocket+Nginx+CDN配置方法

依照这个教程，无法访问nginx的网站， 也无法使用shadowrocket连接
nginx的配置使用github的通用配置文件 ，v2ray 也是依照教程里面的只是变更uuid 
测试都没有出错

nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

/usr/local/bin/v2ray test -config /usr/local/etc/v2ray/config.json
V2Ray 5.7.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.20.4 linux/amd64)
A unified platform for anti-censorship.
Configuration OK.

请问可以如何查错？
谢谢

**Comment by bannedbook** [comment]
无法访问nginx的网站，是哪个端口，是不是 防火墙没开端口 
用这个工具测下端口
https://ping.pe/

**Comment by bigjimmy546** [comment]
測試端口沒有反應
但是端口是開的
<img width="712" alt="Screenshot 2023-08-04 at 11 10 25 AM" src="https://github.com/bannedbook/fanqiang/assets/7572072/33735fd0-4ec4-4c7d-8338-3d1963c9c575">

**Comment by bannedbook** [comment]
ufw allow 80/tcp

**Comment by bigjimmy546** [comment]
Ufw disabled

**Comment by bannedbook** [comment]
是不是有其它防火墙

**Comment by bigjimmy546** [comment]
應該是沒有，oracle 的network也開啟了80,443

**Comment by bannedbook** [comment]
那就不清楚了
端口启动了，但是外面连不了，你自个研究研究吧

**Comment by Alvin9999** [comment]
alter id是多少

**Comment by bigjimmy546** [comment]
0

**Comment by bigjimmy546** [comment]
可以了，我另外有安裝VPN服務器。

編輯  /etc/iptables/rules.v4 
在这一行 -A INPUT -p tcp --dport 22 -j ACCEPT 紧接着下面添加需要的防火墙规则。

-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT

重啟所有的服務現在可以使用了太感謝。
