### ISSUE TITLE
chatgpt 翻墙后没法用

### ISSUE THREAD

**Issue by tone2158** [bannedbook/fanqiang#832]
chatgpt 翻墙后提示这个怎么办，目前用的是 ss ，机场是 ios的小火箭 。有什么办法吗。 unable to load site，Please try again later. If you are using a VPN, try turning it off. Check the [status page](https://status.openai.com/) for information on outages.

**Comment by tone2158** [comment]
vultr 的服务器，deploy 在美国

**Comment by bannedbook** [comment]
可以购买付费机场套餐 解决
或者 给vps 套上 warp
https://github.com/P3TERX/warp.sh

**Comment by tone2158** [comment]
> 可以购买付费机场套餐 解决 或者 给vps 套上 warp https://github.com/P3TERX/warp.sh

可以实现非常感谢
