### ISSUE TITLE
隐私问题

### ISSUE THREAD

**Issue by THEshyqaq** [bannedbook/fanqiang#857]
请问作者在各平台的网站包括GitHub收益还有相关广告什么禁书网之类的收益足够运营这个项目吗？怎么资助你们呢？这免费的我用来注册信息担心账号安全？还是付款好了 /clown

**Comment by bannedbook** [comment]
可以购买我推荐的 机场
https://github.com/bannedbook/fanqiang/wiki/V2ray%E6%9C%BA%E5%9C%BA

**Comment by THEshyqaq** [comment]
请问我已经用了edgego的clash mete翻墙 成功注册了 谷歌和gpt账号 换私人IP能亡羊补牢吗？

**Comment by bannedbook** [comment]
一般换同一个国家的IP，应该没啥问题，不要频繁换IP即可

**Comment by THEshyqaq** [comment]
需要将edge go删除吗？

**Comment by bannedbook** [comment]
可删可不删

**Comment by THEshyqaq** [comment]
非常感谢 但是我注意到他自动修改了我的edge设置 会有影响吗 因为edge的密码保存功能我很喜欢 edgego会在后台读取我的edge缓存数据吗？

**Comment by bannedbook** [comment]
你不启动它就不会改吧
