### ISSUE TITLE
脚本翻墙会闪退

### ISSUE THREAD

**Issue by Zach-Zhang** [bannedbook/fanqiang#869]
基于chromeGo插件配合翻墙的脚本，执行成功后，不到2分钟就会闪退，然后翻墙就会失败，1.clash.meta翻墙，2.Xray翻墙，3.hysteria翻墙等翻墙脚本都试过，都存在闪退问题，无法持续使用

**Comment by bannedbook** [comment]
https://github.com/bannedbook/fanqiang/issues/868

**Comment by bannedbook** [comment]
好不容易找到2个老版本，
ChromeGo-20230516.7z
ChromeGo-20231102.7z
还在用Windows7的网友可以试试，使用时请先更新IP。
https://github.com/bannedbook/fanqiang/releases/tag/ChromeGo-latest

**Comment by Zach-Zhang** [comment]
> 好不容易找到2个老版本， ChromeGo-20230516.7z ChromeGo-20231102.7z 还在用Windows7的网友可以试试，使用时请先更新IP。 https://github.com/bannedbook/fanqiang/releases/tag/ChromeGo-latest
补充一下，我得是win10系统，这个有效吗？

**Comment by Zach-Zhang** [comment]
禁止了深造播放器进程，卸载了360，现在不闪退了
