### ISSUE TITLE
所有涉及v2ray的翻墙软件都无法正常显示窗口

### ISSUE THREAD

**Issue by mark2330** [bannedbook/fanqiang#876]
使用过v2rayn,v2rayx等，在启动应用程序后进程都存在，没有闪退，但应用程序窗口都不显示，再次尝试运行会提示应用程序已经启动

**Comment by bannedbook** [comment]
用这个吧
https://github.com/bannedbook/fanqiang/tree/master/ChromeGo

**Comment by jafox-12** [comment]
> 用这个吧 https://github.com/bannedbook/fanqiang/tree/master/ChromeGo

也失败了

**Comment by mark2330** [comment]
> 用这个吧 https://github.com/bannedbook/fanqiang/tree/master/ChromeGo

这个下载后试着解压，也试了文件里写的解压方式，但所有的解压软件都会报毒不给解压，想问一下这个可以解决吗

**Comment by mark2330** [comment]
> 用这个吧 https://github.com/bannedbook/fanqiang/tree/master/ChromeGo

也关了自带的防火墙，没有用杀软

**Comment by bannedbook** [comment]
注意：软件都是采用加密方式的，但为了更稳定、更安全的翻墙，建议卸载国产杀毒软件，至少翻墙时不要用它们！因为很多国产杀毒软件，比如360安全卫生、360杀毒软件、腾讯管家、金山卫士等不仅仅会起干扰作用，造成软件无法正常使用或速度变慢，它们与金盾工程有千丝万缕的关系! 可以使用[windows自带的defender杀毒软件](https://docs.microsoft.com/zh-cn/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows?view=o365-worldwide)。
