### ISSUE TITLE
有关卸载ChromeGo的问题

### ISSUE THREAD

**Issue by hjh88317791** [bannedbook/fanqiang#878]
尊敬的ChromeGo开发者：
您好！
我接下来将要去到国外留学，不再需要翻墙软件，请问卸载ChromeGo是否只需要将整个文件夹删除就可以完全清理了呢？还是说有其他的注册表项、下载项或者生成在本地其他目录下的文件需要一并删除？
希望得到您的答复，谢谢！

**Comment by bannedbook** [comment]
ChromeGo 整个文件夹删除即可
