### ISSUE TITLE
Shadowrocket 可以使用前置代理么？

### ISSUE THREAD

**Issue by yray680** [bannedbook/fanqiang#886]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
我想用wrap前置代理，瓦工用ssr。
请问在Shadowrocket 可以操作么？

**Comment by bannedbook** [comment]
在VPS 里配置好 wrap 就行了吧
但不要用SSR, 很快就封了，
Shadowrocket 用vmess+ws
