### ISSUE TITLE
Not enough storage is available to process this command.

### ISSUE THREAD

**Issue by liuzhaoyzz** [bannedbook/fanqiang#887]
本项目提供多个软件和多项服务，请明确说明您反馈的问题是有关哪一个软件，或哪一个服务？
1.clash.meta翻墙
运行时，提示Not enough storage is available to process this command.
无法继续，怎么办？
已经是最新的翻墙包了。
![Not enough storage is available to process this command](https://github.com/bannedbook/fanqiang/assets/9776716/d4dae01f-f3a8-42f3-a36b-e30a573c1340)

**Comment by bannedbook** [comment]
你的硬盘是不是满了

**Comment by liuzhaoyzz** [comment]
还有10GB空间呢，一个批处理能要多少空间？C盘的空间还有33GB。

**Comment by liuzhaoyzz** [comment]
搞定了，是操作系统的问题，出了毛病，我重装了win10，就可以了。
