### ISSUE TITLE
运行CMD文件后，网页还是无法打开

### ISSUE THREAD

**Issue by tangA008** [bannedbook/fanqiang#897]
time="2024-09-14T10:05:19.8438994+08:00" level=info msg="Start initial configuration in progress"
time="2024-09-14T10:05:19.8900607+08:00" level=info msg="Geodata Loader mode: memconservative"
time="2024-09-14T10:05:19.8900607+08:00" level=info msg="Geosite Matcher implementation: succinct"
time="2024-09-14T10:05:19.9030784+08:00" level=info msg="Initial configuration complete, total time: 13ms"
time="2024-09-14T10:05:19.9030784+08:00" level=info msg="Sniffer is closed"
time="2024-09-14T10:05:19.9040962+08:00" level=info msg="Mixed(http+socks) proxy listening at: 127.0.0.1:7890"
time="2024-09-14T10:05:19.9051274+08:00" level=info msg="Start initial Compatible provider 🍃 应用净化"
time="2024-09-14T10:05:19.9051274+08:00" level=info msg="Start initial Compatible provider 🍎 苹果服务"
time="2024-09-14T10:05:19.905817+08:00" level=info msg="Start initial Compatible provider 📲 电报信息"
time="2024-09-14T10:05:19.905817+08:00" level=info msg="Start initial Compatible provider 🛑 全球拦截"
time="2024-09-14T10:05:19.905817+08:00" level=info msg="Start initial Compatible provider default"
time="2024-09-14T10:05:19.905817+08:00" level=info msg="Start initial Compatible provider ♻️ 自动选择"
time="2024-09-14T10:05:19.905817+08:00" level=info msg="Start initial Compatible provider 🚀 节点选择"
time="2024-09-14T10:05:19.905817+08:00" level=info msg="Start initial Compatible provider 🎯 全球直连"
time="2024-09-14T10:05:19.905817+08:00" level=info msg="Start initial Compatible provider 🐟 漏网之鱼"
time="2024-09-14T10:05:19.905817+08:00" level=info msg="Start initial Compatible provider 🌍 国外媒体"
time="2024-09-14T10:05:19.905817+08:00" level=info msg="Start initial Compatible provider Ⓜ️ 微软服务"
time="2024-09-14T10:05:21.7567093+08:00" level=info msg="[TCP] 127.0.0.1:64372 --> edge.microsoft.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:21.8198673+08:00" level=info msg="[TCP] 127.0.0.1:64376 --> api.edgeoffer.microsoft.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:21.8265701+08:00" level=info msg="[TCP] 127.0.0.1:64374 --> business.bing.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:22.3011259+08:00" level=info msg="[TCP] 127.0.0.1:64388 --> stat.download.xunlei.com:8099 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:22.3048512+08:00" level=info msg="[TCP] 127.0.0.1:64389 --> ext.scriptcat.org:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:22.5029903+08:00" level=info msg="[TCP] 127.0.0.1:64386 --> api-shoulei-ssl.xunlei.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:22.8629507+08:00" level=info msg="[TCP] 127.0.0.1:64378 --> www.bannedbook.org:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:22.9138305+08:00" level=info msg="[TCP] 127.0.0.1:64380 --> www.bing.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:23.1802301+08:00" level=info msg="[TCP] 127.0.0.1:64383 --> business.bing.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:23.2596675+08:00" level=info msg="[TCP] 127.0.0.1:64393 --> api-shoulei-ssl.xunlei.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:24.2783261+08:00" level=info msg="[TCP] 127.0.0.1:64399 --> substrate.office.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:24.3738358+08:00" level=info msg="[TCP] 127.0.0.1:64404 --> substrate.office.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:24.3778544+08:00" level=info msg="[TCP] 127.0.0.1:64401 --> ext.scriptcat.org:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:24.3843724+08:00" level=info msg="[TCP] 127.0.0.1:64405 --> update.googleapis.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:24.3988947+08:00" level=info msg="[TCP] 127.0.0.1:64402 --> api.edgeoffer.microsoft.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:24.3988947+08:00" level=info msg="[TCP] 127.0.0.1:64403 --> edge.microsoft.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:24.3988947+08:00" level=info msg="[TCP] 127.0.0.1:64407 --> client.wns.windows.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:24.6491582+08:00" level=info msg="[TCP] 127.0.0.1:64397 --> update.googleapis.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:24.9378196+08:00" level=info msg="[TCP] 127.0.0.1:64395 --> edge.microsoft.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:25.0646003+08:00" level=info msg="[TCP] 127.0.0.1:64413 --> www.bing.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:25.5969813+08:00" level=info msg="[TCP] 127.0.0.1:64421 --> served-by.pixfuture.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:25.597484+08:00" level=info msg="[TCP] 127.0.0.1:64423 --> served-by.pixfuture.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:25.597484+08:00" level=info msg="[TCP] 127.0.0.1:64424 --> served-by.pixfuture.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:25.605044+08:00" level=info msg="[TCP] 127.0.0.1:64419 --> www.google-analytics.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:25.6805075+08:00" level=info msg="[TCP] 127.0.0.1:64417 --> platform-api.sharethis.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:25.9744858+08:00" level=info msg="[TCP] 127.0.0.1:64431 --> cdn.pixfuture.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:26.1179615+08:00" level=info msg="[TCP] 127.0.0.1:64439 --> graph.microsoft.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:26.2335105+08:00" level=info msg="[TCP] 127.0.0.1:64415 --> www.bannedbook.org:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:26.3171522+08:00" level=info msg="[TCP] 127.0.0.1:64433 --> www.bannedbook.org:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:26.4008133+08:00" level=info msg="[TCP] 127.0.0.1:64441 --> www.googletagmanager.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:26.6593889+08:00" level=info msg="[TCP] 127.0.0.1:64427 --> aa.agkn.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:26.6930174+08:00" level=info msg="[TCP] 127.0.0.1:64429 --> securepubads.g.doubleclick.net:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:26.9350172+08:00" level=info msg="[TCP] 127.0.0.1:64434 --> www.bannedbook.org:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:26.9495129+08:00" level=info msg="[TCP] 127.0.0.1:64437 --> xpaywalletcdn.azureedge.net:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:27.1470041+08:00" level=info msg="[TCP] 127.0.0.1:64444 --> edge.microsoft.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"
time="2024-09-14T10:05:29.0140973+08:00" level=info msg="[TCP] 127.0.0.1:64446 --> prod-westus2.access-point.cloudmessaging.edge.microsoft.com:443 match Match using 🚀 节点选择[dongtaiwang.com_2]"

**Comment by tangA008** [comment]
运行wget.exe闪退

**Comment by bannedbook** [comment]
不要运行wget
运行IP更新

**Comment by Cheryl8679** [comment]
> 不要运行wget 运行IP更新
如何操作
