### ISSUE TITLE
美区账号没有怎么注册

### ISSUE THREAD

**Issue by xuxinglin** [bannedbook/fanqiang#913]
没有美区账号如何搞呢

**Comment by Alvin9999** [comment]
[共享账号](https://github.com/Alvin9999/new-pac/wiki/%E8%8B%B9%E6%9E%9C%E6%89%8B%E6%9C%BA%E7%BF%BB%E5%A2%99%E8%BD%AF%E4%BB%B6)

[iOS注册美区Apple ID教程](https://github.com/Alvin9999/new-pac/wiki/iOS%E6%B3%A8%E5%86%8C%E7%BE%8E%E5%8C%BAApple-ID%E6%95%99%E7%A8%8B)
